### ISSUE TITLE
Make volumio installable on an already running host

### ISSUE THREAD

**Issue by ning-yu** [volumio/Volumio2#10]
This has been requested previously, reopening to track here.

**Comment by jotak** [comment]
I think that even if it's not an "officially supported" feature, it would be nice to make it possible.

**Comment by jomo** [comment]
Indeed this would be nice, especially for development.
Maybe we could have a list of requirements, so that could at least be manually set up.

**Comment by jotak** [comment]
fyi some people already did it https://volumio.org/forum/volumio-ubuntu-t1299.html#p4917

**Comment by volumio** [comment]
The installation instructions are a possible way. Providing a clean .deb install is not an option unfortunately...
As for development, using a supported platform is the best way, since is the only way to achieve the system compliance needed

**Comment by arthurlutz** [comment]
Hi, am interested in this too. @volumio why is providing a clean .deb not an option ?

**Comment by volumio** [comment]
It will take really a lot of time...
