### ISSUE TITLE
Broken mt7601 wifi dongle driver

### ISSUE THREAD

**Issue by shoonoise** [volumio/Volumio2#1005]
Hi
I can't set up wifi on my raspberry because of error:
```
mt7601u 1-1.5:1.0: Direct firmware load for mt7601u.bin failed with error -2
mt7601u: probe of 1-1.5:1.0 failed with error -2
```
So no wlan interfaces appears.

The dongle works well with common raspberian (kernel 4.4.34+).

**Comment by macmpi** [comment]
you may want to look at this https://github.com/volumio/Volumio2/issues/1080#issuecomment-287686609
