### ISSUE TITLE
Volumio crashes when saving an alarm without time

### ISSUE THREAD

**Issue by 2lepus** [volumio/Volumio2#1018]
I had one alarm configured properly.
Then I added a new alarm and saved it without an entry for time and/or music source.
Going back to the alarm edit page all alarms had disappeared.
Then I again added alarms without chosing a time and saved the entry.
Then the Volumio UI crashed while the music was still playing.
After restarting Volumio my first entry was visible again.
I suppose that the entry should be validated before saving or invalid entries should be ignored

**Comment by volumio** [comment]
https://github.com/volumio/Volumio2/commit/0cef730619eee159b90bf0a74361f452ee740c26
Fixed!
