### ISSUE TITLE
USB DAC not recoginzed by Volumio

### ISSUE THREAD

**Issue by FABIOMOSKA** [volumio/Volumio2#1021]
Hello,

I own a ROTEL RDD-06 USB DAC and can't seem to make it appear on Volumio. It does not show in the graphic UI under Output Device nor in the terminal when I list output devices:

volumio@volumio:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
Subdevices: 8/8
Subdevice #0: subdevice #0
Subdevice #1: subdevice #1
Subdevice #2: subdevice #2
Subdevice #3: subdevice #3
Subdevice #4: subdevice #4
Subdevice #5: subdevice #5
Subdevice #6: subdevice #6
Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
Subdevices: 1/1
Subdevice #0: subdevice #0

Any ideas on how to get it to communicate with Volumio?

**Comment by volumio** [comment]
Probably its not compatible.. sorry
