### ISSUE TITLE
Library scanning counts tracks twice with duplicate sources.

### ISSUE THREAD

**Issue by chsims1** [volumio/Volumio2#1025]
Not very important in the scheme of things, but I thought it was worth noting.  I set up a cifs and an nfs share of the same material on a NAS (I was troubleshooting), and Volumio reports double the expected unique tracks in the library. Presumably, this also means that any duplicate tracks on a single source will not be differentiated??

**Comment by xipmix** [comment]
Do the shares have the same 'alias' in the MyMusic network drives listing? 
The URIs for the tracks include the mountpoint, it the two shares are mounted on different mountpoints this might explain what you see.

**Comment by chsims1** [comment]
I'm almost positive that they were different alias', but the paths are obviously very different.

**Comment by volumio** [comment]
Fixed
