### ISSUE TITLE
webUI display on small screen

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#103]
This post has been moved to webUI section : https://github.com/volumio/Volumio2-UI/issues/5

**Comment by balbuze** [comment]
In the queue, last song can't be removed

**Comment by volumio** [comment]
Can you please move this into the Ui repo?
https://github.com/volumio/Volumio2-UI

just to keep tidy...

**Comment by balbuze** [comment]
Sorry . of course. But tomorrow... I have to go now.
