### ISSUE TITLE
No sound on Raspberry Pi B with Hifiberry DAC

### ISSUE THREAD

**Issue by 7091lapS** [volumio/Volumio2#1035]
I'm not getting any sound after mounting the Hifiberry DAC rca ([this one](https://www.hifiberry.com/shop/boards/hifiberry-dac-rca/)) on my Raspberry Pi B. Volumio is correctly configured to use the correct DAC, and I have tried rebooting multiple times.
Any help would be greatly appreciated.

**Comment by gonace** [comment]
I've had the same problem since 22 Dec, I've downgraded (reinstalled) with a previous version and it seems to work.  (#927)  Tried 2.114 today and that didn't work either, so downgrading to a version before 2.041.

**Comment by damien122** [comment]
I had the same problem with raspberry pi 2 and hifyberry DAC+.
I had fix this with a reboot after the next day. As I understand sometimes volumio cant load the hifyberry board. Only if you go under the play settings and there is a third sub menü with some specific hifyberry settings then the board was loaded successful and can play sound.
