### ISSUE TITLE
NasMounts config.json missing 'Path' variable

### ISSUE THREAD

**Issue by ecto1a2003** [volumio/Volumio2#104]
the 'Name' is used as a path leading to mounts that are multiple folders deep. for example 'e/music' is the path to the share but the mount folder is created with the same path

**Comment by balbuze** [comment]
yep it's a known problem.  Name is used as path... you can edit config.json to correct it, waiting for a fix.

**Comment by volumio** [comment]
Yep, I accept suggestion on how the input fields should be named, and how many of them ...

**Comment by balbuze** [comment]
1 - There is still a problem mounting nfs share : name is used as path. 
2 -And it is not possible to mount the same folder once with cifs, once with nfs (to compare cpu use because cifs seems use up to 3% with a rpi2) because the mount path cannot be define properly ( trough webUI)

**Comment by mpasteur** [comment]
For me we should have : 
 * an host (IP adress or hostname) eg : 192.168.0.10 or mynas
 * a path which is relative to the host : mp3/classical
 * a name - fixed by user to easily find their shares : NAS1, NAS2 ...
 * maybe a login /password 

did i miss something ? i can work on this this wek-end i think.. (mostly with NFS i don't know if i can mount  a cifs share to test)

**Comment by balbuze** [comment]
With the last built (from today 12/01/16) I think that network drive configuration is not clear. With cifs files, it's rather easy even if the name of the share and the path should be separate. With nfs same thing but path is much more complicated.

**Comment by balbuze** [comment]
Mpasteur I read your comment after I post...

**Comment by mpasteur** [comment]
no problem. If you have some time to test my PR i would be glad to have some feedbacks...

**Comment by balbuze** [comment]
I'll try tonight. But I see a lot of activities !

**Comment by balbuze** [comment]
@mpasteur 
There is something I don't understand, with your last PR I see no difference. Maybe I miss something but I thought you add field to configure as you wrote above

**Comment by volumio** [comment]
You need to update both the UI and the Backend, plus you need to delete /data/configuration and reboot

**Comment by balbuze** [comment]
Hello,
I have tested the PR from mpasteur. For me, it's good, understandable settings etc. Some minor improvements : window is not refreshed when adding or removing share. We should disallow the use of space in name as it use to create the mount point and does not work.

**Comment by ecto1a2003** [comment]
i think im running the latest build and i dont see an option in the ui for path, how do i update both the backend and the ui.

**Comment by ecto1a2003** [comment]
... and it just magically fixed itself. weird?

**Comment by balbuze** [comment]
@ecto1a2003 you'll find some useful information here : https://gitter.im/volumio/Volumio2
