### ISSUE TITLE
upmpcli error

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#105]
get this message in console. Seems to appears when no use of the webUI for a long time (>5min, 10min ?) "info: [1448566078511] Upmpcli error: Error: stderr maxBuffer exceeded."

**Comment by volumio** [comment]
Should be fixed with https://github.com/volumio/Volumio2/commit/563fe3a52e17864a4a485746ff2760473b667aa4

Thanks a lot for reporting!

**Comment by balbuze** [comment]
As it seems to be fixed (no more error) I think this issues could be marked as resolved
