### ISSUE TITLE
Sounds Terrible

### ISSUE THREAD

**Issue by ecto1a2003** [volumio/Volumio2#106]
im running on a standard raspberry pi 2 and it sounds truly terrible no matter what i play or listen with. The previous version ran fine albeit that was through a hifiberry.

**Comment by jomo** [comment]
Are you sure this is a problem with Volumio2 and not with your RasPi or setup?

**Comment by balbuze** [comment]
If I understand, you use the onboard sound card to test V2?
If yes, you can't  compare the onboard output with a external DAC ( hifiberry in this case). The gap is very important.

**Comment by ecto1a2003** [comment]
Yes, I am using the internal card as the hifiberry is nonfunctional at this time. Even still the sound I'm getting is atrocious and sounds more like interference than the song in listening to. 1.55 sounded amazing but I was using the hifiberry at the time.

**Comment by tomatpasser** [comment]
The onboard output is terrible on the pi. What you describe sounds exactly like my experiences with onboard audio output. Try using volumio 1 without your hifiberry to verify.

**Comment by ecto1a2003** [comment]
I did a pull yesterday and everything sounds fine, maybe it was a connection issue, maybe not. This issue is resolved for me.
