### ISSUE TITLE
[webradio] Dirble list per country only fetches first page per country

### ISSUE THREAD

**Issue by Saiyato** [volumio/Volumio2#1068]
for (var i = 0; i < 1; i++) {
        var dirbleDefer = libQ.defer();
        self.getStationsForCountry(id, 30, i, dirbleDefer.makeNodeResolver());

        paginationPromises.push(dirbleDefer);
    }

Iteration only fires once, I've updated this to 30 locally, loading time degrades obviously. Maybe we can make this a setting?

**Comment by xipmix** [comment]
The first line of the for loop now (2018 Aug) reads
```
for (var i = 1; i < 3; i++) {
```
see 7fa32311.

I think we can close this one, do you agree?

**Comment by Saiyato** [comment]
Yes sir, I don't think there are many countries with over 90 stations.
