### ISSUE TITLE
Periodic "My Music" update

### ISSUE THREAD

**Issue by mattberther** [volumio/Volumio2#1074]
Perhaps I am missing something, but I would love to have some automated process that rescans (actually, I think the volumio terminology is updates) my music library (hosted on my NAS). Currently, I need to come in and manually click the update button.

Also, would love to see a list of "most recently added" music from the home screen. 

Thank you for considering.

**Comment by mattberther** [comment]
What was the resolution on this?

**Comment by volumio** [comment]
Volumio should automatically update itself when new files are added. 
as for the recently added, we're working on it

**Comment by mattberther** [comment]
I cant really seem to get this to work. I have a NAS setup as an NFS share. When I add music, unless I manually click update, they don't come in.

**Comment by volumio** [comment]
It already does it every 4 seconds

**Comment by mattberther** [comment]
I know you keep saying its supposed to work. But, it does not work for me. Are there logs that I can review somewhere to try to get to the bottom of this?

**Comment by kehugter** [comment]
Permissions?
You ssh as `volumio`, who also owns the nfs mounts, that's why you can see all files. But the scanning is done by mpd, which runs as `mpd:audio`. Thus, if your dirs/files in the nfs mount don't have enough world permissions, they can't be accessed and indexed.

You could change your local permissions, but as far as I can tell (after little testing), mpd can run as `volumio:audio` to access the whole mount and nothing breaks. @volumio what do you think?

@mattberther if you want to try it out, edit `/etc/mpd.conf`

```
user "volumio"
```

and then

```
sudo systemctl restart mpd.service
```

**Comment by mattberther** [comment]
Thanks for the thoughts, @kehugter. Unfortunately, no dice. I'm still not able to have it automatically rescan my library. I've even tried switching to a cifs share with no luck.

**Comment by kehugter** [comment]
I'm pretty sure my library isn't updating the files on my NFS share every 4 seconds either. Any suggestion on how to debug this further, @volumio?

**Comment by mattberther** [comment]
I *know* mine is not. I add new files; I can see them when I SSH; I can see them when I browse the NAS through the UI. But, unless I manually click update on the My Music tab, Im not able to search for it.

I've let the music sit for up to 3 days to see if it picks up. Ive also tried restarting. Nothing, except for clicking Update, makes the music searchable in the library.

**Comment by volumio** [comment]
Hi Matt,
I've finally came to the conclusion that inotify is not reliable over SMB\NFS. Therefore the auto update via NAS does not work.
To overcome this, I've added the "update this folder" function in every folder, just click the 3 dots on your NAS or any subfolder and you will be able to just update this subfolder.

**Comment by mattberther** [comment]
Huzzah! Thank you. That will work!

**Comment by marcolino7** [comment]
Hi,
just quick question, is possible to schedule a complete library rebuild or simply an update via cron?
In this way i do not need to reload manually everytime I add a new folder.

Thanks
