### ISSUE TITLE
shairport-sync crash while airplaying on version: 2.129

### ISSUE THREAD

**Issue by Nutcasey** [volumio/Volumio2#1093]
This is on volumio version:

VOLUMIO_VERSION="2.129"
VOLUMIO_HARDWARE="pi"

This happened on about the 3rd song of an album. The album is lossless and this always occurs at around the 10/15 minutes mark.

Here are the logs:

http://logs.volumio.org/volumio/qY3mA2q.html

**Comment by tim-felix-lange** [comment]
Same problem here, though for me the time that it survives varies heavily.

**Comment by Nutcasey** [comment]
I ended up using Max2Play. Seems to always work for me.
