### ISSUE TITLE
[2.129] Replace and play doesn't work

### ISSUE THREAD

**Issue by biva** [volumio/Volumio2#1098]
Since I installed 2.129, the function "Replace and play" doesn't work anymore.

Step to reproduce:
- Go to Albums
- Click on the 3 dots next to an album
- Chose the option "Replace and play"
- The queue is cleared, but then it's not populated with Album's tracks

**Comment by volumio** [comment]
Just fixed, expect a new release with this fix in a couple of days

**Comment by biva** [comment]
Wao, so fast Gi :) !
Thanks!
