### ISSUE TITLE
Muffled sound after updating to 2.129

### ISSUE THREAD

**Issue by mooop12** [volumio/Volumio2#1101]
The sound on S/PDIF output of my HiFiBerry DIGI+, as well as the Pis audio jack output is muffled after updating Volumio to 2.129. I tried reinstalling Volumio on the sd card with no result.

On a side note, the audio output options are finicky to say the least. Sometimes it shows it's outputting to my HiFiBerry when in reality it's outputting to audio jack. When I2S is disabled and you enable it, the DAC list doesn't show up and you can't set your DAC, you have to save it, refresh the page and then change your DAC and save again.

**Comment by mooop12** [comment]
Not sure why but going back to 2.118 doesn't fix the issue. The issue is only with Web Radio function, playing regular music files works fine. It surely is a bug in Volumio, because I tried the same stream on Raspbian (using mplayer) and it worked fine.

**Comment by xipmix** [comment]
Can you post an example web radio that exhibits the problem? Are there any web radios that work correctly?

**Comment by mooop12** [comment]
Sorry, I probably should've checked the earlier... Most of the radios from the Top 500 list actually work fine. The ones that don't work for me I added myself, for example: http://stream.open.fm/94 http://stream.open.fm/14 http://stream.open.fm/3
They use AAC codec if that's relevant.

**Comment by michalwu** [comment]
Same here. Open FM sound level is way too low, distorted. 
Is there a place we can enable debug to have logs of what's going on?

**Comment by xipmix** [comment]
Go to ```http://<volumioip>/dev/``` and click the 'send logs' link, then paste the log url here. This puts your log on the internetz but it is (lightly) scrubbed beforehand.
Otherwise, login with ssh and run
```sudo journalctl -f```

**Comment by michalwu** [comment]
http://logs.volumio.org/volumio/25D9o6d.html
xipmix, thank you.

**Comment by michalwu** [comment]
Open.fm is using AAC+ (HE-AAC v2) @ 48 kbps. Is Volumio supporting he-aac v2 profile?

**Comment by mooop12** [comment]
@volumio Why was this closed when the issue is not fixed?

**Comment by michalwu** [comment]
@volumio Explanation, please?

**Comment by mooop12** [comment]
A shame really, it looked like a promising project. I guess open issue statistics are more important than actually fixing bugs, there were over 200 open issues not so long ago, now there are less than 100. A lot of them were closed just like this one with zero response, but I guess it's your project so you're free to drive it into the wall.
