### ISSUE TITLE
[2.118] Can not update to 2.129

### ISSUE THREAD

**Issue by THEJAJO** [volumio/Volumio2#1102]
I'm not able to update the Volumio 2 (on R Pi 2) to newer version.
Every time I hit Update and restart the Volumio it stays at 2.118.

Is there a way to update via console and don't lose the user data?

**Comment by volumio** [comment]
Did you install stuff via apt-get ? Edit manually /etc/os-release? Enabled TEST mode?

**Comment by bablat** [comment]
I had the same issue, did not install anything via apt-get. I had to reset all user settings and then upgrade worked.

**Comment by THEJAJO** [comment]
I also did not log on to Volumio console and change anything.

Is there a way to backup the user preferences before resetting and upgrading?

**Comment by THEJAJO** [comment]
I cleared the data and the Volumio was updated, however old issues came back - Pause button when playing web radio, can not add more than 1 radio from pls playlist (only the first is added, I already submitted the issue few months ago) and probably more.

**Comment by GetMike** [comment]
Same problem for me: could not upgrade to 2.129, it even was no longer possible to connect via SSH. After deleting user data the upgrade and also SSH connection worked again.
But now I cannot get any sound out of my hifiberry dac - but it worked with the previous version 2.118.

**Comment by chpanag** [comment]
same here

**Comment by THEJAJO** [comment]
Few minutes ago I updated the V2 to 2.163 version without any issue.
