### ISSUE TITLE
Improve robustness by using atomic writes when saving configuration

### ISSUE THREAD

**Issue by earlchew** [volumio/Volumio2#1110]
As a user, I want the configuration to be saved atomically, so that I can be certain that I will always be able to read a valid configuration.

Support for achieving this goal was added in https://github.com/fanciulli/v-conf/issues/3

https://github.com/fanciulli/v-conf/commit/7f3e921a8f773c1991dd525de2e1a753b6020963

**Comment by volumio** [comment]
Interesting indeed, did not notice this... Good hint @earlchew

**Comment by xipmix** [comment]
Thanks for pointing this out, it could help with updates of /boot/config.txt as well (#946)
