### ISSUE TITLE
Any chances to update mpd & mpc to the latest versions?

### ISSUE THREAD

**Issue by kowalcj0** [volumio/Volumio2#1124]
Latest version of `Volumio` `v2.129` which was released March 23, 2017, runs:
* `mpd` v0.19.19 released August 23, 2016
* `mpc` v0.26 released June 3, 2014

Quite a few changes/fixes were introduced since then to both projects. Release log on the mpd's home page https://www.musicpd.org/
Current latest version of:
* `mpd` is v0.20.6 released  March 10, 2017
* `mpc` is v0.28 released August 18, 2016

Thanks

**Comment by volumio** [comment]
We are working on it, but got some stability issues. As soon as we solve this, new mpd will be added.
