### ISSUE TITLE
Spopd ?

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#113]
I filled credential for spopd in /etc/spopd.conf.
I see it starting and running. But nothing in the webUI. Is it suppose to appears somewhere or not yet ?

**Comment by atcapollo** [comment]
Still the case as of January build.

**Comment by apinner** [comment]
@balbuze is this still current?

**Comment by atcapollo** [comment]
@apinner yes still current.

**Comment by apinner** [comment]
@balbuze fixed in RC2?

**Comment by volumio** [comment]
fixed
