### ISSUE TITLE
Time delay from boot to wifi access

### ISSUE THREAD

**Issue by meaz** [volumio/Volumio2#1138]
Hello,

I have Volumio 2 installed on Raspberry Pi Zero with a raspiaudio DAC. It works fine, I just have a question about the time to access the webUI

I plugged the pi to a screen to check, and it takes only about 30 sec to boot and have the login screen. So it's pretty quick.

Then, from another computer, I still have to wait another good 30-40 sec so that I can ssh. At this point, I still can't access to the webUI, I have to wait again... Why does it take more that a minute from the login screen to get access from the webUI? Is that normal? Is that because I'm using a pi Zero? Or because my wifi dongle is slow? Or is it a bug?

Thanks

**Comment by volumio** [comment]
Fixed
