### ISSUE TITLE
Setting manual DNS entry in GUI not always working

### ISSUE THREAD

**Issue by gwlevans** [volumio/Volumio2#1141]
Hi,

I ran into an issue when setting the DNS manually via the GUI. Resolvconf appears to still be picking up DNS from DHCP and using that first. This caused an issue installing the volspotconnect2 plugin as my ISP DNS server seems to have issues (Virgin Media UK). Setting the DNS in /etc/resolc.conf.head to use Google DNS via: 

nameserver 8.8.8.8
nameserver 8.8.4.4 

Seems to have fixed this as it ensures those DNS servers are used first rather than anything from DHCP. It might be an idea to change the GUI to set the DNS in /etc/resolv.conf.head. 

Cheers,

Gareth

**Comment by macmpi** [comment]
Yes, it's a known issue and fix is ongoing as per https://github.com/volumio/Volumio2/pull/1061.
You may wan to test that PR change.
