### ISSUE TITLE
New webradio providers www.lesindesradios.fr

### ISSUE THREAD

**Issue by Sigmun** [volumio/Volumio2#1148]
I was wondering if this site (www.lesindesradios.fr) can be used to automatically add web-radio, as a web-radio provider. 
This is a French site on which you can find independent radio listenable on internet. There are two kind of radio listed on it (and listenable from it): true radios with live streaming and pure web-radios

**Comment by volumio** [comment]
Unfortunately no, but we'll build a Volumio webradio directory in the future
