### ISSUE TITLE
Add the ability to control volume with phone buttons

### ISSUE THREAD

**Issue by Madseason41** [volumio/Volumio2#1151]
I would like to request the ability to control the volume with the buttons on a phone.

Example. While the harmony hub app (iPhone) is open, you can use the side volume buttons to increase or decrease the volume of whatever activity you are controlling. 

I am not sure this can be down thru the web ui, but since I use the web ui like an app from my home screen I thought I would give it a shot.

Please close if this is not possible.

**Comment by volumio** [comment]
This works using Volumio Android app, not possible with the UI
