### ISSUE TITLE
netbios name

### ISSUE THREAD

**Issue by Warter21** [volumio/Volumio2#1160]
Hi,

If I change the name on the UI doesn't change the name in the samba configuration file. So the netbios name stays volumio.

Thanks
Warter

**Comment by xipmix** [comment]
Possibly related to #357, #293. Can you post a log after trying this, (go to /dev url, press 'send logs' button)

**Comment by Warter21** [comment]
I did some grep. It seems volumio don't touch /etc/samba/smb.conf at all.

root@volumio:/volumio# grep -R "/etc/samba/smb.conf" -> empty

**Comment by macmpi** [comment]
as per https://github.com/volumio/Volumio2/issues/974#issuecomment-290250206
