### ISSUE TITLE
Remove Google-Analytics

### ISSUE THREAD

**Issue by NicoHood** [volumio/Volumio2#1165]
When I run the web frontend it requires me to run a script from the frontend itself (which is okay) and google-analytics scripts. Please remove those, as I don't want to be tracked.

**Comment by xipmix** [comment]
Duplicate, please close.
See vigorous discussion in volumio/Volumio2-UI#310 . Any help you can offer would be welcome.

**Comment by NicoHood** [comment]
Thanks. I swear I searched for this in the issue tracker!
