### ISSUE TITLE
Unable to connect via SSH with last release 

### ISSUE THREAD

**Issue by Arthurin** [volumio/Volumio2#1180]
Trying to connect with Putty via ssh on my local network, Fatal Error "Server unexpectedly closed network connection". 
I rolled back to a backup image (VERSION="2.041"), can't work on my rpi without it!

**Comment by macmpi** [comment]
Already largely discussed here https://github.com/volumio/Volumio2/issues/1045
Please read it carefully: only option is to re-image.
Some links if you want to manually save/restore your data.
You may close this issue.

**Comment by Arthurin** [comment]
Thanks!
