### ISSUE TITLE
Installing libasound2-dev fails in VERSION: 2.175

### ISSUE THREAD

**Issue by Labzz** [volumio/Volumio2#1184]
Hi, 

I noticed the same issue tryed to install snapcast server + client

After flashed volumio VERSION: 2.175 on my Raspberry Pi 2B i tryed everything above and a few more fixes, some broke the entire volumio image so I restarted from scratch. 

Commands I used for installing snapcast can be found [https://github.com/badaix/snapcast/blob/master/doc/build.md#linux-native](here).
 
Another thing to notice is that installing for example 'git and build-essentials' goes well and the installation steps from snapcast worked well on my Pi 3 running raspbian Jessy lite but not on the Volumio image.

![afbeelding](https://cloud.githubusercontent.com/assets/17926205/26278665/5f79eb06-3da0-11e7-8079-bc872e8c3ac7.png)

Okay, I figured out that I can simply change libasound2-dev to libasound2, and yes, the installation will run correctly. 
But when i run "make" in de snapcast folder, the following appears. It seems like the libary will be added in the "dev" install. 
![afbeelding](https://cloud.githubusercontent.com/assets/17926205/26278695/ebe4ef96-3da0-11e7-87f3-fbf94bbd115e.png)

Tryed different routes even manually installing it.
![afbeelding](https://cloud.githubusercontent.com/assets/17926205/26279018/1e6cfdde-3da9-11e7-9f49-0bf5d010f625.png)

**Comment by volumio** [comment]
I will include libasound's new version on Volumio in the next release so you won't have such problem...

**Comment by Labzz** [comment]
Great thanks, can you tell me something about the new update release date?

**Comment by Labzz** [comment]
Maybe it works better when I try it to installing and configuring from: https://github.com/volumio/Build
Instant of the Preinstalled image. I'll try to test it later this week.

**Comment by volumio** [comment]
Done

**Comment by Labzz** [comment]
Thanks
