### ISSUE TITLE
Issue when deleting alarms when multiple alarms are defined

### ISSUE THREAD

**Issue by cldebuhr** [volumio/Volumio2#1199]
In the course of testing the fix for the alarm disable bug (#1190), I discovered another more minor issue.  This one only crops up when there are multiple alarm settings.  When there are multiple alarms defined, each one has its own "delete" button.  But pressing any of them only ever deletes the alarm at the top of the list.  To replicate this behaviour, just define 5 or 6 alarms (each with its own playlist or activation time to assist in discriminating one alarm from another) and try to delete the middle one.  Or the last one.  Only the top alarm on the list ever gets deleted.

Issue observed in v2.185 with alarm switch plugin running on RPi3 using on board WiFi and Allo Boss DAC.

**Comment by volumio** [comment]
Fixed https://github.com/volumio/Volumio2-UI/commit/6d7205b3124d9f62485105fd76bf5ccdcf2f42c6

**Comment by cldebuhr** [comment]
Thank you!
