### ISSUE TITLE
I2s dac wrong outputdevice number

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#1208]
In a fresh install 2.186 RPI2
After enabling loopback device, the outputdevice value is wrong for the dac.
aplay -l gives
`aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: IQaudIODAC [IQaudIODAC], device 0: IQaudIO DAC HiFi pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`
but no sound because in /data/configuration/audio_interface/alsa_controller/config.json 
`{
  "volumestart": {
    "type": "string",
    "value": "disabled"
  },
  "volumemax": {
    "type": "string",
    "value": "100"
  },
  "volumecurvemode": {
    "type": "string",
    "value": "logarithmic"
  },
  "outputdevice": {
    "type": "string",
    "value": "1"
  },
  "mixer_type": {
    "type": "string",
    "value": "Hardware"
  },
  "mixer": {
    "type": "string",
    "value": "Digital"
  },
  "volumesteps": {
    "type": "string",
    "value": "10"
  },
  "outputdevicename": {
    "type": "string",
    "value": "IQaudIO DAC Plus"
  }
}
`
Even after reboot, save, change for jackoutput. But sometimes it works. As result no sound.
edit when disabling i2s in UI, select iqaudio as output and save, the correct value is saved.
edit 2 There is no link with loopback as I removed the module and get the same behaviour

**Comment by balbuze** [comment]
seems to be the same problem than https://github.com/volumio/Volumio2/issues/1195

**Comment by M-I-Kessler** [comment]
Did the work around work for you?

**Comment by balbuze** [comment]
yes !

**Comment by balbuze** [comment]
To be more precise, on a fresh install, it works. But if snd_aloop is loaded, and i2s activated, then the outputdevice number is wrong, and all the system is configured with this wrong value with no sound as result.

**Comment by volumio** [comment]
We should add options snd-aloop index=8" >> /etc/modprobe.d/alsa-base.conf

This way we will have the loopback module always in 8th position and nothing will break

**Comment by balbuze** [comment]
ok thanks ! I'll test it !

**Comment by volumio** [comment]
How do you load snd aloop?

**Comment by balbuze** [comment]
In install.sh modprobe snd_aloop to use without reboot and write in /etc/modules for next boot. Plus now write in /etc/modprobe.d/alsa-base.conf snd_aloop index=7

**Comment by volumio** [comment]
Does it work?

**Comment by balbuze** [comment]
Yes it seems ok. Loopback is loaded with the good number index. But I met some other problems. I'll ask you in a other thread

**Comment by volumio** [comment]
Ok, however the ideal situation is that we put the mod in etc/modprobe.d/alsa-base.conf from the build of the image. If you write on this with the plugin, it can create some problems in the future.
I am looking at it now
