### ISSUE TITLE
playplaylist REST command doesn't work with curl on RPI3 v2.193

### ISSUE THREAD

**Issue by cortegedusage** [volumio/Volumio2#1214]
When I try to load a playlist with:
curl http://volumio.local:3000/api/v1/commands/?cmd=playplaylist&name=FIP
it reports:
{"time":1497168594269,"response":"playplaylist Success"}
but playing doesn't start
when giving the command throug a browser, it does play, and it reports the same...

other commands given with curl ?cmd=play or stop do work.
it doesn't matter if I'm giving the curl command from the rpi itself or from an other rpi...

**Comment by liberatorcnx** [comment]
Try:
curl 'http://volumio.local:3000/api/v1/commands/?cmd=playplaylist&name=FIP'

**Comment by liberatorcnx** [comment]
Ohh - also worth mentioning:  You must URL encode any name with unsafe ASCII characters (spaces etc).

curl 'http://volumio.local:3000/api/v1/commands/?cmd=playplaylist&name=AC DC' will not work.
curl 'http://volumio.local:3000/api/v1/commands/?cmd=playplaylist&name=AC%20DC' will work fine.

**Comment by cortegedusage** [comment]
Ok rtfm for me
Thank you so much for this!
