### ISSUE TITLE
Volumio  2.201: SSH connection refused

### ISSUE THREAD

**Issue by jumping2000** [volumio/Volumio2#1230]
Hi,
after the upgrade to v2.201 I can use the web based GUI, but I can't access the raspberry with SSH, is it a known bug? Thanks

iMac:~ Gianpi$ ssh volumio@192.168.1.118
ssh: connect to host 192.168.1.118 port 22: Connection refused
iMac:~ Gianpi$ ssh volumio@volumio.local
ssh: connect to host volumio.local port 22: Connection refused

**Comment by volumio** [comment]
https://volumio.github.io/docs/User_Manual/SSH.html
