### ISSUE TITLE
Airplay 2

### ISSUE THREAD

**Issue by andre-dw** [volumio/Volumio2#1232]
Will Volumio 2 support Airplay 2 in the future?

**Comment by volumio** [comment]
No idea since nothing is known about the new protocol and its advantages over airplay1

**Comment by snikcers** [comment]
Multiroom support! Just to name the biggest advantage!

**Comment by benjaminwood** [comment]
Worth noting the discussion going on over here: https://github.com/mikebrady/shairport-sync/issues/535

I too would love airplay 2 for multiroom support. I'm sure somebody is working to reverse engineer the protocol. Perhaps when details are shared this issue can be reopened?

**Comment by Neustradamus** [comment]
@volumio: Can you reopen this ticket or I need to create a new?

**Comment by NickBNY** [comment]
airplay2 is key feature https://www.google.com/amp/www.iphonehacks.com/2019/12/airplay-2-cracked-stream-audio-unsupported-speakers.html/amp

**Comment by volumio** [comment]
There is still nothing that can be implemented.

**Comment by acresp** [comment]
@volumio AirPlay 2 is now supported in the dev branch of [shairport-sync](https://github.com/mikebrady/shairport-sync)
Do you think it would be possible to implement it in a beta or something?

**Comment by kimdiallo** [comment]
AirPlay2 works already on HifiBerryOS (dev branch) - maybe interesting:

 https://github.com/hifiberry/hifiberry-os/blob/668fdf8b72ffa8c87875ac856e12c83725b7ce77/buildroot/package/hifiberry-shairport/hifiberry-shairport.mk

Would love to get this feature also from Volumio!
