### ISSUE TITLE
Sleep mode not work

### ISSUE THREAD

**Issue by suypportedox** [volumio/Volumio2#1240]
Hello

Thanks for this wonderfull works !! 

i juste have a little problem, the sleep mode not work on my RPi3, i use the .img install

if i do a sleep, i have the confirmation pop-up shows " NaN " ...
![2017-06-28_113753](https://user-images.githubusercontent.com/29750949/27630596-40cc5a26-5bf6-11e7-8cbf-bd2b470ae94a.png)

Thanks

**Comment by xipmix** [comment]
Can you tell us what version this is please. Look in the 'system' page of right-side menu.

**Comment by suypportedox** [comment]
Version is 2.201   from  volumio-2.201-2017-06-13-pi.img.zip

**Comment by xipmix** [comment]
This seems to be a cosmetic issue. Does it actually go to sleep when you want it to?

**Comment by suypportedox** [comment]
ok the sleep mode work and if i do just 1 hour , i have not the NaN but replace by will ... 
it is just a cosmetic so.

but i have to sleep at a time fixed not with timing ... it is possible ,
