### ISSUE TITLE
UPnP browser disabled

### ISSUE THREAD

**Issue by nbonamy** [volumio/Volumio2#1256]
Hello,

I just installed Volumio 2.201 on a Raspeberry Pi B 2.0, I UPnP browsing is disabled.

From the logs:

2017-07-09T06:17:06.865Z - info: Loading plugin "upnp"...
2017-07-09T06:17:07.958Z - info: Plugin upnp_browser is not enabled

How I can enable it?

Thanks for the great stuff!

**Comment by nbonamy** [comment]
I even tried to force it in plugins.json but to no avail.

**Comment by volumio** [comment]
It is disabled because its not ready yet to be used.
