### ISSUE TITLE
2.201 - pushMethod not implemented

### ISSUE THREAD

**Issue by GlennV** [volumio/Volumio2#1268]
In the WebSockets API, there is a reference of "pushMethod". 
https://github.com/volumio/Volumio2/wiki/WebSockets-API-Reference#callmethod-on-plugin

I am trying to use "callMethod" to return a config parameter, in this case "volumemax" to handle the UI of my iOS app. I am using the following parameters for this:

```swift
socket.emit(.callMethod, [
  "endpoint": "audio_interface/alsa_controller",
  "method": "getConfigParam",
  "data": "volumemax"
])
```

However, there seems to be no way to get the result back. 

Is this not yet implemented or is there another trick to this?

**Comment by volumio** [comment]
callmethod is not meant to give back any data (if not explicitly set on the function you're calling). Your best bet is to use getUiConfig and then parse results

**Comment by geeks-r-us** [comment]
Could you please give us a complete example on howto use the pushMethod?
I still struggle with the return value ... even I set it in the called method with defer.resolve(result) 
On the other side the listener for pushMethod is never executed
