### ISSUE TITLE
I can login as root

### ISSUE THREAD

**Issue by ShalokShalom** [volumio/Volumio2#1273]
Your README: Root login has been disabled by default, however user volumio can become root.

I do: root
psw: volumio

Works

**Comment by volumio** [comment]
login as: root
root@192.168.1.89's password:
Access denied
root@192.168.1.89's password:

Which version are you using?

**Comment by ShalokShalom** [comment]
The current one.

**Comment by dhoffend** [comment]
local login has different rules then login via ssh. Remote root login is disabled, local not
