### ISSUE TITLE
Current solution to use as client is improveable

### ISSUE THREAD

**Issue by ShalokShalom** [volumio/Volumio2#1276]
Currently, its a pain to setup the Pi in a way, that i can use it as server and client.
I installed lxde and xorg-server, while it does not make any difference. 

startx: command not found

**Comment by ShalokShalom** [comment]
Ignore an issue for one month and close it then: That is why your software is so buggy.

**Comment by volumio** [comment]
Closed because it does not make any sense since there is a display plugin which achieves what you want without manually installing lxde

**Comment by ShalokShalom** [comment]
Then, you may like to add it: https://volumio.github.io/docs/User_Manual/Quick_Start_Guide.html

**Comment by volumio** [comment]
You're right. I will do it now

**Comment by ShalokShalom** [comment]
I think also that your super fancy website looks a bit to the contrary to your documentation, which might be the reason why you hide it. Thanks for the nice interaction. +1

**Comment by volumio** [comment]
Yep our doc just sucks visually (and also in content)... If you have a suggestion for a better one or can improve a bit the look of it, that would be greatly appreciated

**Comment by ShalokShalom** [comment]
Lets think about. Do you love static site generators? Which parts of the documentation are fine?

**Comment by volumio** [comment]
Yep I love static generator because they are handy... We just write it and a travis CI task publishes it to gh-pages...
I just love the menu on the left and page on the right, which I guess is common to all docs

**Comment by ShalokShalom** [comment]
Gitbook does that. It also offers black themes and so on. For me, the interface of Gitbook sucks.
There is an alternative from Rust, mdbook: https://azerupi.github.io/mdBook/

https://doc.rust-lang.org/book/second-edition/

**Comment by ShalokShalom** [comment]
Gitlab hosts nearly each static site, IPFS does too. Github hosts Jekkyl only, afaik.

**Comment by volumio** [comment]
Sorry Shalok, nothing really convincing... Maybe a little css tuning on ours?

**Comment by ShalokShalom** [comment]
Not really.

**Comment by ShalokShalom** [comment]
You want something more fancy?

**Comment by volumio** [comment]
If there is,yes. What don't you like of ours?

**Comment by ShalokShalom** [comment]
I prefer something without manual CSS handling.
