### ISSUE TITLE
Not possible to connect to WiFi OPEN 

### ISSUE THREAD

**Issue by digx77** [volumio/Volumio2#1278]
It seems it is not possible to connect Volumio via WiFi if the WiFi connection is an OPEN connection (no WEP and no WPA).

I think this should be fixed soon.

Thanks

**Comment by volumio** [comment]
Grazie Diego, fixerò asap

**Comment by philthecat** [comment]
Hi. Same problem here. Any chance to get a fix ?
Thanks a lot.

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Volumio2/commit/5854b4cb0389c50f88d49e3a3daf48cb5615bab3
