### ISSUE TITLE
Plugin helper does not differentiate between armhf and i386

### ISSUE THREAD

**Issue by volumio** [volumio/Volumio2#1280]
@Ghembs  When publishing from i386, the plugin zip and the json files are still updated on armhf

**Comment by Ghembs** [comment]
corrected!
[https://github.com/volumio/Volumio2/commit/45f0507e4536673028de37f3ca1eb8aa174b3ab0](url)

**Comment by macmpi** [comment]
BTW: how can we simply publish one same plugin code for all architectures (if no platform specific dependencies)?
