### ISSUE TITLE
Opt out for Google Analytics

### ISSUE THREAD

**Issue by fmslottje** [volumio/Volumio2#1310]
I noticed that every request to Volumio gets logged by Google Analytics. I do not believe this is compliant with EU data protection law. I suggest to clearly indicate in the UI that information about Volumio usage is shared with third parties and would like to have a opt-out possibility (without modifying the source code) for this data collection. A simple switch in the system menu would be sufficient.

**Comment by xipmix** [comment]
This has already been requested see, volumio/Volumio2-UI#310. Work seems to have stalled, if you are able to help, please dive in.
