### ISSUE TITLE
Support for JustBoom Smart Remote

### ISSUE THREAD

**Issue by gdau** [volumio/Volumio2#1313]
Hi!

Great project - loving it. Please could support be added for the JustBoom Smart Remote? It comes with a plug-and-play dongle for the pi. More info can be found here:

https://www.justboom.co/product/justboom-smart-remote/

Thanks!

**Comment by marcolino7** [comment]
Hi,
I would like to know if now JustBoom Smart Remote is supported or not via "IR Remote Plugin".

Thanks

**Comment by ashthespy** [comment]
@marcolino7 - you should be looking over at the [IR Remote Plugin repo](https://github.com/volumio/volumio-plugins/tree/master/plugins/accessory/ir_controller/configurations/JustBoom%20IR%20Remote)
