### ISSUE TITLE
apt-get install triggerhappy: "Unable to locate package"

### ISSUE THREAD

**Issue by 2oh1** [volumio/Volumio2#1352]
How do I install triggerhappy on a Raspberry Pi 3 running the latest version of Volumio?

apt-get install triggerhappy: "Unable to locate package"
Also: "apt-get update" gives me the following result with errors:

Err http://archive.raspbian.org jessie InRelease
  
Err http://archive.raspberrypi.org jessie InRelease
  
Err http://archive.raspberrypi.org jessie Release.gpg
  Temporary failure resolving 'archive.raspberrypi.org'
Err http://archive.raspbian.org jessie Release.gpg
  Temporary failure resolving 'archive.raspbian.org'
Reading package lists... Done
W: Failed to fetch http://archive.raspberrypi.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://archive.raspbian.org/raspbian/dists/jessie/InRelease  

W: Failed to fetch http://archive.raspbian.org/raspbian/dists/jessie/Release.gpg  Temporary failure resolving 'archive.raspbian.org'

W: Failed to fetch http://archive.raspberrypi.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'archive.raspberrypi.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Saiyato** [comment]
Looks like a networking problem, does the problem persist after a reboot? 
How are you connected (Wifi/ethernet)? 
Did you set a manual DNS (if not, does this help)?
