### ISSUE TITLE
CONSTANT REBOOT WHEN MUSIC IS IN THE QUEUE

### ISSUE THREAD

**Issue by nick-moshulu** [volumio/Volumio2#1362]
I'm using a PI B3 +, version 2.246 and same on 2.285.

When I was connected to a Synology NAS and added songs to the play queue, they played no problem. When trying a Lenovo NAS mounted fine, updated fine but added to play queue it would reboot, come back up for a minute or so and rebooted and kept doing that until I could eventually remove everything from the play queue.
I then tried with a share on my own PC and it did exactly the same as the Lenovo NAS.

**Comment by volumio** [comment]
Can you please send logs?
https://volumio.github.io/docs/User_Manual/Sending_logs_for_troubleshooting.html

**Comment by nick-moshulu** [comment]
http://logs.volumio.org/volumio/SxGAm6W.html

**Comment by volumio** [comment]
Thanks, its an error in the album-art module, notified here https://github.com/lacymorrow/album-art/issues/8

thanks

**Comment by nick-moshulu** [comment]
How do I fix this?

**Comment by nick-moshulu** [comment]
I just disabled album art work and it works now, 
Thanks

**Comment by johnsonlam** [comment]
I got the same problem, now click the queue and it reboot, is the bug still exist?
