### ISSUE TITLE
Sparky, Volumio 2.282: repeated journal error

### ISSUE THREAD

**Issue by chsims1** [volumio/Volumio2#1364]
This doesn't appear to affect Volumio's operation, but I have just noticed in 'journalctl -f' an infinitely repeated error message:

`Oct 14 12:46:19 Volumiokitchen kernel: owl_i2c: owl_i2c_fifo_irq(): [i2c1] no ACK, fifostat 0x10013
Oct 14 12:46:19 Volumiokitchen kernel: gsl_ts_read set data address fail!
Oct 14 12:46:19 Volumiokitchen kernel: ======read 0xb0: 0 0 0 0 ======
Oct 14 12:46:19 Volumiokitchen kernel: owl_i2c: owl_i2c_fifo_irq(): [i2c1] no ACK, fifostat 0x10013
Oct 14 12:46:19 Volumiokitchen kernel: gsl_ts_read set data address fail!
Oct 14 12:46:19 Volumiokitchen kernel: owl_i2c: owl_i2c_fifo_irq(): [i2c1] no ACK, fifostat 0x20013
Oct 14 12:46:19 Volumiokitchen kernel: owl_i2c: owl_i2c_fifo_irq(): [i2c1] no ACK, fifostat 0x10013
Oct 14 12:46:19 Volumiokitchen kernel: gsl_ts_read set data address fail!
Oct 14 12:46:19 Volumiokitchen kernel: ------gslX680 test_i2c error------
`
Anyone know the significance or otherwise of this?

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Build/commit/a7099cc1102c3952334f5cc73879380c48dc2e0c
