### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by kaffeeringe** [volumio/Volumio2#1367]
I try to update from 2.114 - Volumio tells me it has to update to 2.224 first. But every time the update is done and I restart the Raspi the Wifi is reset to hotspot and the version is still 2.114...

**Comment by volumio** [comment]
Which PI do you have? Did you modified your system manually in any way? Can you give more context?

**Comment by kaffeeringe** [comment]
It's a Raspy2 with a HiFiBerry DAC+. I use a Belkin wifi adapter.
I didn't change anything manually, IIRC. It could be that I tried to add bluetooth audio output. But I am not completely sure. 
Maybe it's easier to reinstall ;-)

**Comment by volumio** [comment]
Yes, you changed it by trying to add bt audio out.
Easiest thing is to reflash

**Comment by kaffeeringe** [comment]
Wow! The configuration assistent - the whole setup ist amazing! Awesome work!! Thank you so much!

**Comment by volumio** [comment]
Great to hear that you like it!
