### ISSUE TITLE
Volumio does not start after rpi-update

### ISSUE THREAD

**Issue by kloeggaa** [volumio/Volumio2#1371]
Same issue like this one
https://volumio.org/forum/volumio-041-doesn-start-after-rpi-update-t5460.html

Reproduce:
sudo apt-get update
sudo apt-get install binutils
sudo rpi-update
sync
sudo reboot

Expected result:
Volumio starts
volumio.local/ is accessible

Actual result:
Volumio does not start
ping is not successful, even in LAN mode

Version:
2.296

**Comment by volumio** [comment]
rpi-update will break Volumio. It's by design since we need to have matching system and kernel.

**Comment by MoonshineSG** [comment]
any way to revert a "rpi-update" ?

**Comment by volumio** [comment]
no

**Comment by MoonshineSG** [comment]
Yup. Had to reinstall ;) 
Maybe you can remove rip-update from the original image?
