### ISSUE TITLE
Clicks and pops on Volumio 2.31 + RPI 3 + Sabre ES9018S

### ISSUE THREAD

**Issue by nagogam** [volumio/Volumio2#1393]
Hi,

I have a setup with Volumio 2.31 on the Raspberry Pi 3 and DIY pcb with a Sabre ES9018S DAC.
The "Generic I2S DAC" model is used in Volumio. Everything is fine except the annoying
clicks and pops when putting the current track on pause or just changing position within it.

I could look with an oscilloscope what happening at these events. The reason is the I2S bitclock signal.
For a few milliseconds (10 msec typically), the bitclock remains at the high state. That produces the clicks.

I have also another I2S source, an Amanero board. Amanero continues to produce the bitclock even
on pause or after a stop. I suppose it remembers the last frequency of the bitclock and finally even if there is
nothing playing the DAC remains in the "Locked" state and there are no clicks and pops.

Is it possible to "tune" the Volumio in the way it always sends a bitclock signal or there is another way to
get rid of clicks? I tried to use a MPD script (daemon) on the RPI, which set a GPIO pin (mute) when there is no audio signal but it
changes nothing. The bit is set too late.

Any ideas? =)

Michael

**Comment by volumio** [comment]
Hi Michael, the problem with this DAC is that ESS did not release the driver as open source. So there's not much we can do about it
