### ISSUE TITLE
Volumio and Cover Art via shairport-syc

### ISSUE THREAD

**Issue by wolfgang-reutz** [volumio/Volumio2#1394]
has anyone cover art using shariport-sync working?

some versions ago i knew that i saw the covers when playing music from itunes in volumio using airplay, but now the covers are gone and i see the default cover image from volumio.

i edited /volumio/app/plugins/music_service/airplay_emulation/shairport-sync.conf.tmpl and added a password for airplay and set include_cover_art = "yes"; but this doesn't work.

any ideas how to (re-)enable cover art dirsplay for airplay in Volumio 2.3.10?

**Comment by volumio** [comment]
It is disabled because shairport is not very responsive with it enabled. It might be re-enabled in the future
