### ISSUE TITLE
CLI deamon stop command

### ISSUE THREAD

**Issue by dmnc-net** [volumio/Volumio2#1427]
https://github.com/volumio/Volumio2/blob/f49ac565fb0c463f65dbc5166c1f779059c6f1a1/app/plugins/system_controller/volumio_command_line_client/volumio.sh#L62

This script contains `vstop()` but L138 and L142 are calling just `stop`.

**Comment by xipmix** [comment]
Yes, there is no 'stop' function defined. I wonder if those three controls should be named vstart, vstop, vrestart?

**Comment by dmnc-net** [comment]
Command `vstop` is because `stop` is used for the playback control. There is `start|vstop|restart` commands for the deamon but `vstart|vstop|vrestart` will be nicer, you are right.

Technical problem at this moment is just on line 62 (fix: change `vstop()` to `stop()`) or lines 138 and 142 (fix: change `stop` to `vstop` twice). I'm just lazy to clone/fix/push/PR, better just to announce the bug :)
