### ISSUE TITLE
output setting

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#143]
only the current output device is displayed : bcm2835 Alsa
If manually changed in /boot/config.txt (ex iqaudio-dacplus ) reboot and back to webUI, only this is displayed

**Comment by gkkpch** [comment]
just to confirm this works fine on an Odroid C1, incl. USB Audio. There is a small glitch when hot-plugging the usb audio device: when you select this, save and then remove the USB device, it will show 'VALUE NOT FOUND BETWEEN SELECT OPTIONS' the next time you go to the playback options.

**Comment by balbuze** [comment]
On RPI 2, when 2 output device exist, only the first (bcm2835) selected is used even when choosing the other one, save and reboot

**Comment by Sceedster** [comment]
Sound output: I have a RPI2 + Hifiberry, please make it possible to choose my hardware. Oh, and thank you all for your hard work!

**Comment by Sceedster** [comment]
adding the line to config.txt does not work....

**Comment by apinner** [comment]
DACs introduced in RC1
