### ISSUE TITLE
if id3tag %track% are empty, enabling "show track number" result in UNDEFINED

### ISSUE THREAD

**Issue by Bescio** [volumio/Volumio2#1441]
When enabling "Show Track Numbers" in the Volumio options, tracks without the ID3 %track% populated, show a "UNDEFINED" value before the title. I'm using latest version of Volumio installed from scratch. 

Please look at the screnshoots:

![undefined](https://user-images.githubusercontent.com/34973944/34458630-4519cd36-edda-11e7-8695-7a77dd646353.JPG)
![undefined1](https://user-images.githubusercontent.com/34973944/34458631-484e86ae-edda-11e7-9ae4-0c38e73e3595.JPG)
![undefined2](https://user-images.githubusercontent.com/34973944/34458632-4b161ab4-edda-11e7-8653-8c5c9495602f.JPG)

Thank you.

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Volumio2/commit/5d40d4bd58a14e01628dc89d348c95cd3018d1d5
