### ISSUE TITLE
Need to add support for Orchard Audio ApplePi DAC

### ISSUE THREAD

**Issue by orchardaudio** [volumio/Volumio2#1444]
Hello,

I need help adding support for my ApplePi DAC to the dacs.json file.

On the raspberry pi the device can be configured with:
dtoverlay=applepi-dac

I have attached the compiled overlay as well.

Please let me know what else I need provide.

[ApplePi-DAC_dtbo_dts.zip](https://github.com/volumio/Volumio2/files/1599176/ApplePi-DAC_dtbo_dts.zip)

**Comment by volumio** [comment]
Hi, it probably was included in the latest kernel. Do you know from which kernel version the ApplePi module is included?

**Comment by orchardaudio** [comment]
I am not sure, can you tell from this thread?
https://github.com/raspberrypi/linux/issues/2302

**Comment by macmpi** [comment]
@volumio from 4.9.68.
Is at 4.9.73 now.

**Comment by orchardaudio** [comment]
Does that mean that it will automatically work with Volumio or does something else need to be done?

**Comment by macmpi** [comment]
In addition to kernel update, [dacs.json](https://github.com/volumio/Volumio2/blob/master/app/plugins/system_controller/i2s_dacs/dacs.json) would need to be populated with relevant info.

**Comment by orchardaudio** [comment]
That is what I am asking, can somebody please help me updated the [dacs.json](https://github.com/volumio/Volumio2/blob/master/app/plugins/system_controller/i2s_dacs/dacs.json) file. I am not that familiar with linux and don't know how to do pull request.

**Comment by volumio** [comment]
Added

**Comment by orchardaudio** [comment]
Thanks for adding.
