### ISSUE TITLE
Limit or eliminate the creation of dummy-albums for orphaned tracks

### ISSUE THREAD

**Issue by andreas-henning** [volumio/Volumio2#1453]
Dummy albums are created to serve as a container for orphaned tracks (i.e. tracks without an album).

I propose that dummy-albums should be removed from Artists, Genres and Albums views. In the Artists and Genres views, orphaned tracks will remain accessible through the tracks-list. Orphaned tracks would no longer be accessible from the Albums view, which might pose a problem for some.

On the other hand, I can't imagine this being useful in a practical sense. If we want to play an artist's tracks (including orphaned tracks), we can do that from the 'Artists' view. If we want to play tracks of a certain genre (including orphaned tracks), we can do that from the 'Genres' view. What exactly is the use case where somebody would want to play only an artist's orphaned tracks?

For people with music collections with many orphaned tracks, removing dummy-albums will dramatically shorten the list of albums in the 'Albums' view, making it much easier to find real albums.

For people who have a clean music collection, where every track is assigned to an album, this proposal would change nothing.

Ideas? Feedback?

UPDATE:
Previously I mentioned that dummy-albums can occasionally have no tracks, making them non-functional. I've since created a separate issue for that, which is now here:
https://github.com/volumio/Volumio2/issues/1458

**Comment by xipmix** [comment]
One use I can think of for displaying orphaned tracks is so they could be cleaned up, ie assigned to some parent by moving to the subdirectory in the music collection the user deems appropriate. I think flagging them as orphans in the 'Album' view, while making them available as normal under 'Artist' or 'Genre', as you propose, is a reasonable approach. 

Does it make any sense to collate all orphans, from whatever artist, in one 'orphans' dummy album in the 'Album' view? That also tidies up the Album listng.

**Comment by andreas-henning** [comment]
@xipmix 

> I  think flagging them as orphans in the 'Album' view, while making them available as normal under 'Artist' or 'Genre', as you propose, is a reasonable approach.

Did I understand you correctly:

It would be okay to remove dummy-albums from the 'Artists' view (as is already the case in the 'Genres' view), because in both of those views orphaned tracks are still accessible in the list of tracks.

I would certainly agree with that. I also like your idea to collate orphans in the 'Albums' view. IMHO that would nicely clean up collections with many orphans without sacrificing functionality.

I could get behind all of that.

I'd give it a shot at preparing a PR if you think that sort of change isn't going to cause hordes of users to descend on volumio-HQ with pitchforks, because they were using all those dummy-albums in some legitimate way that I just can't think of.  ;-)

**Comment by xipmix** [comment]
> It would be okay to remove dummy-albums from the 'Artists' view (as is already the case in the 'Genres' view), because in both of those views orphaned tracks are still accessible in the list of tracks.

Yes, this is what I was suggesting. I think the danger of fomenting revolution is low. It could be lowered further by documenting the thinking behind orphan handling in [docs](https:/github.com/volumio/docs).

I just noticed volumio/Volumio2-UI#448. I don't think your orphan handling proposal here has an impact there but your PR #1447 might.

**Comment by andreas-henning** [comment]
#448 may be responsible for the non-functional dummy-album I've not yet looked into.

The code introduced by #1447 would likely be modified again as part of this task... at least if we want the orphan-album to be the last entry in the Albums view.

I'll give it a shot.

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Volumio2/commit/5d40d4bd58a14e01628dc89d348c95cd3018d1d5
