### ISSUE TITLE
Non-functional dummy-albums in Genre and Artist views

### ISSUE THREAD

**Issue by andreas-henning** [volumio/Volumio2#1458]
I will be providing a PR for this soon. This just provides a description so I have something to reference from the commit.

In the Genres and Artists views, orphaned tracks (i.e. tracks that don't belong to an album) are grouped into a dummy-album. Clicking on the dummy-album typically lists all of the album-artist's orphaned tracks. It is currently possible for the dummy-album to list no orphaned tracks at all, making it non-functional.

Problem:

This issue arises if the last (or only) track returned by:
```js
ControllerMpd.prototype.listArtist(curUri,index,previous,uriBegin)
	self.clientMpd.sendCommand(cmd(findartist, []), function (err, msg)
```
is an orphaned track. The subsequent call to:
```js
self.searchFor(lines, i + 1, 'Album:')
```
is expected to either find the track's 'Album:' entry, or, if it's an orphaned track,
find the the next track's "file:" entry signaling to the procedure that the "Album:" entry is missing.

If the orphaned track is the last track in the list, the procedure will not encounter a subsequent "file:" entry, which causes the function to exit without a return value. The lhs value at the call site (a variable intended to contain the album name) becomes undefined. This of course causes other issues, like the inability for volumio to find any tracks belonging to an album with that name.

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Volumio2/commit/5d40d4bd58a14e01628dc89d348c95cd3018d1d5
