### ISSUE TITLE
Chord Mojo Hardware Control Not Working

### ISSUE THREAD

**Issue by maxengel** [volumio/Volumio2#1470]
While I can select the mojo as the hardware output device and choose “Mojo Validity” as the mixer, I cannot control the volume via the UI.

**Comment by volumio** [comment]
It means that this is not a proper hardware volume control

**Comment by maxengel** [comment]
Is there a proper place to request hardware volume control for this DAC?

**Comment by volumio** [comment]
Hardware Volume control (as the name suggests) is a property of the DAC itself, nothing that can be added via software
