### ISSUE TITLE
Upload plugin option gone

### ISSUE THREAD

**Issue by jgottlander** [volumio/Volumio2#1480]
I reinstalled Volumio on my RPi3 + HifiBerry Dacplus, yesterday, but noticed that the upload plugin link under plugins wasn't there. I'm using my Rpi as a mediaserver, and are using the Kodi plugin from Saiyato.

I know it was there one or two versions ago, but not with the current version (2.362). Had do install it manually.

Is it purposely removed? And why, in that case. And is the only option to install it manually, through ssh/shell?

**Comment by volumio** [comment]
See here:
https://volumio.org/forum/require-plugins-uploaded-plugins-repo-t8116-10.html

The kodi plugin will be available soon in the official repo
