### ISSUE TITLE
volume controle problems (with iOS and rotary encoder)

### ISSUE THREAD

**Issue by Hyldig01** [volumio/Volumio2#1491]
Hi

I'm having trouble adjusting the volume.

The first time I experience the problem is on my iphone when I turn up or down the volume, it starts jumping uncontrollably. and suddenly lands on a random setting. That problem can I live with, as I do not use my iphone so often.

Then I have recently installed a rotary encoder to adjust the sound without having to use my computer or ipad. But when I use it, the sound jumps around just like when I use the phone ...

Anyone know what the problem is and maybe have a solution?

**Comment by volumio** [comment]
This should have been fixed with https://github.com/volumio/Volumio2/commit/382128d6057c2c6852f8028c63a643d0d9494926
