### ISSUE TITLE
Odd behaviour installing plugins in 2.368

### ISSUE THREAD

**Issue by teq0** [volumio/Volumio2#1498]
A great release, but when I decided to rebuild one of my Pi's from scratch, I installed the Spotify, Spotify Connect and Kodi plugins. When I went to the Installed Plugins tab to start putting in settings, Kodi wasn't showing, Spotify Connect appeared twice.

Didn't do any real debugging, went to the home page, then back to Plugins and it had resolved itself.

A bit painful to reproduce, I'll admit.

**Comment by balbuze** [comment]
This an old bug. And yes, refresh the page solve it.

**Comment by teq0** [comment]
I'll close this then.

In case I find some time to take a look, any clues as to whether it's client side or server side?
