### ISSUE TITLE
how to use USB DAC?

### ISSUE THREAD

**Issue by sumondigi** [volumio/Volumio2#1578]
hello everyone! being in a deep trouble , i am here!!
i am using using volumio version :2.413 on Rpi zero w.
i wnat to use PCM2704 USB DAC because there is no sound output/3.5 mm .
i have tired off after searching the option " 'i2s' switch is in the 'Off' position and Choose the correct DAC model " mentioned in volumio's FAQ.
how can i choose the usb dac option ?
so, what should i Do! is there any hoPe!!??

**Comment by volumio** [comment]
Switch off i2s, in the dropdown of audio device you should see your dac. if you don't then it's not compatible
