### ISSUE TITLE
Unable to upgrade from 2.444

### ISSUE THREAD

**Issue by elcuevero** [volumio/Volumio2#1601]
Been able to upgrade from the last 3 versions with current changes ( had implemented https://github.com/antiprism/mpd_oled successfully) but with the latest I get this. Is there a log where I can see what failed? should I submit a log when it fails?
I now get this:
System Software Integrity check failed, manually edited files were detected. System Software Update is not possible under those circumstances. Please execute a Factory Reset or Delete User Data, then retry.

**Comment by xipmix** [comment]
Good idea to submit a log if it is failing. 

Can you also specify what version you are starting with; ideally ```cat /etc/os-release```.

There is a command line option for capturing logs - ```volumio logdump <filename>``` so you can capture the log to local disk and save it somewhere for analysis.

You could also try looking at the git state
```
$ cd /volumio
$ git status
$ git log
```
Hopefully this will give some clues

**Comment by elcuevero** [comment]
Let's see:
I've attached the dump, loaded log here:
http://logs.volumio.org/volumio/yvF5Xbl.html

And the rest:
volumio@volumio:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
VOLUMIO_BUILD_VERSION="b38474a34dd6501a9ca2801645a6a861fdbc549d"
VOLUMIO_FE_VERSION="f027ce75738c64189018057558e04cba7a74a080"
VOLUMIO_BE_VERSION="a98512120222cc847d1586e8d2068e08cb058c79"
VOLUMIO_ARCH="arm"
VOLUMIO_VARIANT="volumio"
VOLUMIO_TEST="FALSE"
VOLUMIO_BUILD_DATE="Thu Jul 26 16:22:33 CEST 2018"

VOLUMIO_VERSION="2.444"
VOLUMIO_HARDWARE="pi"
VOLUMIO_HASH="7f1396787ccc441a3d64fa9fc7c6c303"
volumio@volumio:~$ volumio@volumio:~$ cat /etc/os-release
-bash: volumio@volumio:~$: command not found
volumio@volumio:~$ PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
volumio@volumio:~$ NAME="Raspbian GNU/Linux"
volumio@volumio:~$ VERSION_ID="8"
volumio@volumio:~$ VERSION="8 (jessie)"
volumio@volumio:~$ ID=raspbian
volumio@volumio:~$ ID_LIKE=debian
volumio@volumio:~$ HOME_URL="http://www.raspbian.org/"
volumio@volumio:~$ SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
volumio@volumio:~$ BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
volumio@volumio:~$ VOLUMIO_BUILD_VERSION="b38474a34dd6501a9ca2801645a6a861fdbc549d"
volumio@volumio:~$ VOLUMIO_FE_VERSION="f027ce75738c64189018057558e04cba7a74a080"
volumio@volumio:~$ VOLUMIO_BE_VERSION="a98512120222cc847d1586e8d2068e08cb058c79"
volumio@volumio:~$ VOLUMIO_ARCH="arm"
volumio@volumio:~$ VOLUMIO_VARIANT="volumio"
volumio@volumio:~$ VOLUMIO_TEST="FALSE"
volumio@volumio:~$ VOLUMIO_BUILD_DATE="Thu Jul 26 16:22:33 CEST 2018"
volumio@volumio:~$
volumio@volumio:~$ VOLUMIO_VERSION="2.444"
volumio@volumio:~$ VOLUMIO_HARDWARE="pi"
volumio@volumio:~$ VOLUMIO_HASH="7f1396787ccc441a3d64fa9fc7c6c303"

volumio@volumio:/volumio$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   app/plugins/music_service/mpd/mpd.conf.tmpl

Untracked files:
  (use "git add <file>..." to include in what will be committed)


        app/plugins/system_controller/network/wireless.js
        http/www/
[logondemand.log](https://github.com/volumio/Volumio2/files/2342298/logondemand.log)


no changes added to commit (use "git add" and/or "git commit -a")
volumio@volumio:/volumio$ git log
commit a98512120222cc847d1586e8d2068e08cb058c79
Author: Volumio <info@volumio.org>
Date:   Thu Jul 26 14:13:34 2018 +0000

    adding help menu section
volumio@volumio:/volumio$

**Comment by volumio** [comment]
As you can see you modified app/plugins/music_service/mpd/mpd.conf.tmpl 
So in fact it's working as supposed: if you edit files manually, no update for you...

**Comment by elcuevero** [comment]
Ok, reverted file to original 'changed content back to original one in
github' but still get the same error. Any pointers? I should add that this
change (of mpd.conf.tmpl) passed the last version upgrade.

**Comment by volumio** [comment]
The thing is that even if you reverted, your changes will stay on our "overlay" partition, preventing proper updates. The only solution is to do delete user data or factory reset
