### ISSUE TITLE
Fatal Error: ReferenceError: stopAirPlay is not defined

### ISSUE THREAD

**Issue by MistakenIdeas** [volumio/Volumio2#1611]
I’ve seen the Volumio UI crash and restart a few times since upgrading to 2.457. This appears to happen when attempting to play a radio stream or audio file from the Volumio UI after having previously been streaming to the device using AirPlay/ShairportSync 
Relevant logs http://logs.volumio.org/volumio/cMs9hal.html

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Volumio2/commit/7606b384c151a9c13c5f646f1448cc9f69703dd3

Thanks for reporting

**Comment by MistakenIdeas** [comment]
Updated to fe0c1408a4070942e04aeaf4d0389511d8333af8 with git and stopping of airplay now seems to work fine, thanks!
