### ISSUE TITLE
Consistant code style

### ISSUE THREAD

**Issue by ashthespy** [volumio/Volumio2#1612]
As Volumio grows, so does it's codebase. 
Going by this nice quote from [`idiomatic.js`](https://github.com/rwaldron/idiomatic.js/):
>All code in any code-base should look like a single person typed it, no matter how many people contributed.

Would there be a Volumio specific style guide? If not, [`standardjs`](https://github.com/standard/standard) seems to be the most widely used, and has wide IDE support!

**Comment by volumio** [comment]
Good idea. Would you like to help setting it up and fixing code?

**Comment by volumio** [comment]
I feel silly, but... https://github.com/Flet/semistandard ?

Hate to say goodbye to semicolons...

**Comment by ashthespy** [comment]
Haha, I just linted some code and it felt strange not to have semicolons. 

In terms of workflow, we could add a CI to run and commit the lints, or use some git hooks to run `standard --fix` before any commits. But then in depends on the devs individual workflow.

**Comment by volumio** [comment]
Deal! Semistandard and githooks!

**Comment by xipmix** [comment]
+1```;```
