### ISSUE TITLE
BBC stations are missing from Radio

### ISSUE THREAD

**Issue by atcapollo** [volumio/Volumio2#163]
UK BBC Radio 1 and Radio 6 are present.

Radio 2, 3 and 4 are missing. Possibly due to pagination issue.

**Comment by atcapollo** [comment]
Update as of v 830 no BBC Radio stations are present, all are missing.

**Comment by apinner** [comment]
@atcapollo is this because BBC have changed all of their streams?

I don't think this is a Volumio issue unfortunately.

**Comment by Tihmann** [comment]
https://gist.github.com/noodlebug/0e5e3754f4e8dbf608e72431b9c34484
Shouldn't this be a solution for BBC Radio ?
