### ISSUE TITLE
Wireless

### ISSUE THREAD

**Issue by jncraig** [volumio/Volumio2#164]
Alpha 4 is working for me, but I need some help with wireless.

Can someone please point me to some decent instructions on installing my usb wireless device?

Much appreciated!

**Comment by purpleferret** [comment]
Hi jncraig,
you can configure wlan from the text console (keyboard and monitor connected).
Just edit two files like the following example (MYSSID is your wlan name and passphrase the password):
```
editor /etc/wpa_supplicant/wpa_supplicant_mywlan.conf
```
```
network={
    ssid="MYSSID"
    psk="passphrase"
}
```
```
editor /etc/network/interfaces
```
```
auto wlan0
iface wlan0 inet dhcp
    wpa-conf /etc/wpa_supplicant/wpa_supplicant_mywlan.conf
```
With this configuration it should connect automatically with every reboot or you can use ifup wlan0 to enable wlan right away.
If you need a more specific setup, have a look at the wpa_supplicant documentation.
Here is a nice HowTo documentation: https://wiki.debian.org/WiFi/HowToUse .

**Comment by jncraig** [comment]
Thanks!

Your suggestions gets me part of the way there.

I can see wireless networks after making the configuration changes.  But, trying to connect to compufest-ap3 (or any other network for that matter) gives this error:

![image](https://cloud.githubusercontent.com/assets/4732485/12406507/a01f8126-be1b-11e5-8da6-752920a80a73.png)

For what it's worth, the compufest-ap3 network has no security key -- simplifies testing.  After setting wpa_supplicant.conf to a minimal configuration

network={
    ssid="compufest-ap3"
}

it now looks like this:

ctrl_interface=/var/run/wpa_supplicant
network={
ssid="compufest-ap3"
key_mgmt = NONE
}network={
    ssid="compufest-ap3"
}

**Comment by jncraig** [comment]
The first one is wpa_supplicant_mywlan.conf, the second is supplicant.conf.

**Comment by volumio** [comment]
Please, wait for the official wi-fi conf to be released.

**Comment by jncraig** [comment]
Thanks!

**Comment by jbmfg** [comment]
This still happening?

**Comment by jncraig** [comment]
I don't know.  I've stayed away from playing with wi-fi until "official wi-fi conf" is released.  Has that happened?

**Comment by jbmfg** [comment]
Still not working for me in latest beta.  Not sure what the deal is
