### ISSUE TITLE
USB Audio quirks for Kernel 4.14.90

### ISSUE THREAD

**Issue by gkkpch** [volumio/Volumio2#1686]
I have a patch, assembled from from 4.18.y and 4.19.y, which brings DSD Direct capable device support to the level of the last stable kernel.. 
This patch has been tested with kernel 4.14.90 on cubox-i and works perfectly.
I added two kernel print messages for XMOS/Thesycon/Mytek devices, which will show if and which altsetting is DSD Direct capable.
These patches are **not** in the PI kernel, so if we want to use them, we have to compile our own.

Here is the link:
https://github.com/gkkpch/USB-Audio-Patches

**Comment by volumio** [comment]
What do you suggest? Shall we go and compile all kernels?

**Comment by gkkpch** [comment]
We do most of them already, except PI, Cubox and Asus (when we get back to normal after the Tinker clock issue has been fixed).
With Asus we can get patches integrated fairly easy, with Cubox I rely on Armbian (might actually use that for other main platforms. Armbian’s build method offers the opportunity to patch ourselves.
Leaves the PI. 
Not a lot of work after doing that for the first time, perhaps @macmpi is willing to maintain that (there is a weekly update for 4.14.y).

But this also reminds me of one thing I have not done consistently: document it properly.

**Comment by macmpi** [comment]
@gkkpch you may want to suggest the patch to @pelwell and crew at https://github.com/raspberrypi/linux/issues: they might cherry-pick into next 4.14.x, as this is potentially beneficial to many.

**Comment by volumio** [comment]
Great idea! 

And I also had another one for the pi kernel: for the USB quirks to be added, why don't we just rebuild the ko file and add it on top of the official pi kernel?

**Comment by pelwell** [comment]
Go for it. I don't think we'll be on 4.14 much longer, but anything which is essentially a back port is usually accepted very quickly.

**Comment by gkkpch** [comment]
@pelwell / @macmpi 
I followed your advice and created a PR with it.

**Comment by gkkpch** [comment]
I’ll close this one, it has just been merged into the PI kernel 4.14.y as #2790.
