### ISSUE TITLE
Update Base OS to Debian Stretch Stretch

### ISSUE THREAD

**Issue by smoonlee** [volumio/Volumio2#1719]
Update OS to Debian Stretch for support for newer version of Kodi and Packages

**Comment by volumio** [comment]
We're working to bring buster support as we speak

**Comment by MaxSchambach** [comment]
Any news on this?
Would be very nice to have the kernel updated to >= 4.6 in order for the newer Intel WiFi chips to work (e.g. for the recent NUCs).
