### ISSUE TITLE
Mixer Type undefined Issue

### ISSUE THREAD

**Issue by thegunslingers** [volumio/Volumio2#1747]
Setup: 
Volumio on a PiZero
USB DAC 
Hardware mixer type

Everything works as it should when first configured, but occasionally with the USB DAC turned off the mixer type will be changed to undefined and requires an edit to the playback options to fix. I have tested restarting Volumio (with the DAC off) and verified that is one case where the mixer type changes from hardware to undefined and Mixer Control Name changes to a null value.

When Mixer Type is changed to undefined, other settings like Output Device and general playback options are not changed. Audio Playback continues to work while mixer type is set to undefined (volume control doesn't work clearly though).

**Comment by xipmix** [comment]
So ... you have a hardware mixer, you configure volumio to use it and then you(?) turn it off. If not by you, how does it get turned off - a powersave feature?

If you turn the DAC on again and bring volumio up, what happens? 
It sounds like volumio does not notice, and does not fix the Mixer Type.

What do you think should happen here - should volumio automatically change to the software mixer? Or should Mixer Type change to some other defined value, e.g. 'not_detected' ?

**Comment by thegunslingers** [comment]
apologize for the delayed response.
If I get Mixer Type to undefined, then turn on the dac then turn on volumio, mixer state stays as undefined, like you were thinking.
Ideally in my opinion it would stay 'hardware mixer' with 'mixer control name' saved as it was set until manually changed to be something else, even if the mixer is not detected or not plugged in.  I think it would be a little more robust with this setup.  And bad boot up order, or turning things off would not force a settings adjustment.

Thank you!

**Comment by thegunslingers** [comment]
I have been working on a fix for this issue, and I have some working code, but I do have one JS question, before I try to submit the fix.
I want to check the config file to ensure mixer is not undefined or empty, I looked at other sections of the code and followed what I saw. The if statement appears to execute everytime though even when my alsa config.json has
`  "mixer": {
    "type": "string",
    "value": ""
  },`
`ControllerAlsa.prototype.setDefaultMixer  = function (device) {
	var self = this;
        var defaultmixer = self.config.get('mixer', '')
        if(defaultmixer.value != undefined && defaultmixer!=''){ 
                    ...js fix here...
        }`

**Comment by thegunslingers** [comment]
Submitted pull request with fix

**Comment by xipmix** [comment]
Hi, is this resolved for you - if so could you close it please?

**Comment by thegunslingers** [comment]
thanks the hot plug changes now fix this issue
