### ISSUE TITLE
REST api for browse doesn't work

### ISSUE THREAD

**Issue by rastersoft** [volumio/Volumio2#1781]
Hi:

I downloaded the last version of Volumio and I'm trying to use the REST API, but although some commands work, others don't. One case is the browse command: I tried:

`curl http://192.168.0.25:3000/api/v1/browse/?uri=radio`

but it just returns "Found. Redirecting to /". And calling that URI from Python just returns the main page of Volumio, instead of a JSON with the list of radios.

**Comment by volumio** [comment]
Works on latest version
