### ISSUE TITLE
Apple Music and Android

### ISSUE THREAD

**Issue by RickorDD** [volumio/Volumio2#1795]
Hi, today i installed Volumio2 on Raspberry Pi 1.

Webradio with iOS App and Apple Music from iPhone works perfectly!!!

But a other device is a Android Tablet, thats not work with Apple Music and the Chrome Browser for beta.music.apple.com 
With Apple Music Android 3.0.0 will Apple Support Chromecast.

What is a good solution for future in Android?

**Comment by volumio** [comment]
Not revelant to volumio
