### ISSUE TITLE
network boot order

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#180]
I noticed that if I power my volumio and later my router, volumio can't start properly (startup sound repeat) and never reach the network. I have to reboot volumio device to use it.

**Comment by volumio** [comment]
Interesting report thanks, I'll look into it!

**Comment by WzL** [comment]
Seems to me Volumio doesn't get an IP from the routers DHCP server because the routers dhcp service is not running yet. Only solution is power volumio when router is finished booting, or maybe add static IP adress to your Volumio. I am not sure if that is an option though.
