### ISSUE TITLE
interrupt and reset music scan from the NAS

### ISSUE THREAD

**Issue by giuseppedigiulio** [volumio/Volumio2#1806]
I have just purchased a Pro-ject Stream box S2 ultra with the customized software version 1.038. The device recognizes the NAS correctly mounts the music folder and starts scanning the tracks in the folder. When it comes close to 1000 songs it resets the counter and doesn't build the catalog. What's the problem?

**Comment by volumio** [comment]
Hi, do this.
Start the scan, then when it stops, send the logs (see: https://volumio.github.io/docs/User_Manual/Sending_logs_for_troubleshooting.html )
and paste the link to the log and send via mail to info@volumio.org I will help from there

**Comment by giuseppedigiulio** [comment]
Hi, I send you the link via email.

**Comment by volumio** [comment]
Following up via mail
