### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by gilphilbert** [volumio/Volumio2#1830]
I've noticed that whitespace is very inconsistent in some of the files which makes reading code a little tricky at times.

Obviously, correcting this will generate a lot of churn across the various files.

Is there a plan to correct some of the whitespace to bring consistency to indentation (tabs vs. spaces) and indentation levels (4/8 spaces, etc.) to the source? Happy to contribute!

**Comment by volumio** [comment]
Yes, there is a semistandard routine ready to be deployed... 
See: https://github.com/volumio/Volumio2/pull/1613

I am trying to get all pending PRs merged before re-enabling it...
