### ISSUE TITLE
Rest API volume control doesn't work

### ISSUE THREAD

**Issue by bdynamic** [volumio/Volumio2#1843]
Version: 2.657
calling: 
```
curl <host>/api/v1/commands/?cmd=volume&volume=58
or
curl <host>/api/v1/commands/?cmd=volume&volume=+5
```
both via localhost and ssh or remotly from another computer results in a volume of zero (or NaN)
Control via webinterface and other commands like pause do work.

API response is success.
See also: https://forum.volumio.org/rest-api-volume-command-issue-t12859.html#p68899

**Comment by xipmix** [comment]
I'm going to ask the obvious to just get it out of the way: are you quoting the url? ie
```
$ curl 'localhost:3000/api/v1/commands/?cmd=volume&volume=20'
# rather than
# curl localhost:3000/api/v1/commands/?cmd=volume&volume=20
```

**Comment by bdynamic** [comment]
I'm ashamed ... and blinded by the beauty of the obvious....

**Comment by volumio** [comment]
@bdynamic what a nice way of saying it ;)
