### ISSUE TITLE
Volumio constantly resolving mqtt.volumio.org

### ISSUE THREAD

**Issue by reshnm** [volumio/Volumio2#1862]
Hi,

my raspi volumio instance (2.657) is doing a DNS lookup for "mqtt.volumio.org" 3 times each second.
Is there some reason this is done? Seems to be a bit chatty ...

Rene

**Comment by volumio** [comment]
mqtt.volumio.org is our broker for mqtt communication, used for myvolumio presence system and in the future for push updates.
Don't know why it resolves 3 times a second, the mqtt protocol should keep the connection alive with minimum bandwith and request

**Comment by WarmChocolateCake** [comment]
Is there a way of disabling this? I'm happy to use my instance at home and have no plans for remote connectivity at the moment
(If I change my mind, then I'd enable it in the future :))

**Comment by volumio** [comment]
Sorry not at the moment

**Comment by WarmChocolateCake** [comment]
OK, I'll just have to block Volumio from the internet.

**Comment by volumio** [comment]
@WarmChocolateCake mind that some functions might not work properly (webradios, myvolumio, updater ).
Let me know what does not work after you disable it.
We now introduced privacy settings, this could be a good candidate to end up there

**Comment by WarmChocolateCake** [comment]
That said... just doing a packet capture now (version 2.703) and I'm not even seeing any MQTT requests, so in my case, I'm not seeing the OP's high traffic.

**Comment by WarmChocolateCake** [comment]
OK, comments passing each other. I'm going to do an update to the latest version and see what's happening

**Comment by volumio** [comment]
The only reason why there can be lots of MQTT packets is when our MQTT broker was down, it happened few times between december and january...
