### ISSUE TITLE
API Feature Request: Call web radio via play 

### ISSUE THREAD

**Issue by jwoodard80** [volumio/Volumio2#1881]
Please forgive me if this is the wrong place for this. Would it be possible to extend the play command to accept one of the web radio URLs? 

Currently the only workaround I know of is to create a playlist with only the web radio inside and call playplaylist. 

Were I more fluent in JS I wouldn't mind trying but I'm hoping it won't be a big change for someone. 

Thank you for the consideration and great project.

**Comment by shed** [comment]
I would love to see this as well.

**Comment by fr1sty** [comment]
You can using the url http://volumio.local/api/v1/replaceAndPlay
And then posting the data, in this case for wefunkradio :)
`
{
"service": "webradio",
"type": "webradio",
"title": "WEFUNK",
"uri": "http://s-09.wefunkradio.com:81/wefunk64.mp3"
}
`

**Comment by jwoodard80** [comment]
This works very well! Thank you so much!
