### ISSUE TITLE
Broken volumio after update 2.698

### ISSUE THREAD

**Issue by damien122** [volumio/Volumio2#1882]
After I install the latest Update 2.698 my volumio did a reboot and afterwards nothing works. The web interface is not reachable and it don't play any music. I can connect to ssh and can see some node processes working but don't know what can I do.

**Comment by xipmix** [comment]
You can run a log capture from ssh 
```
/usr/local/bin/volumio logdump
```
and upload it here, or pastebin.

**Comment by damien122** [comment]
Here is my logdump. Also I noticed that I can hear the startup sound very quiet in a loop playing. Like volumio is starting again and again. But the system don't do a reboot because I am still connected to ssh.

[logondemand.txt](https://github.com/volumio/Volumio2/files/4080344/logondemand.txt)

**Comment by kermitnc** [comment]
I had a similar issue. I restarted the rpi (3b+) twice by disconnecting the usb power line. Now it is working for me.

**Comment by damien122** [comment]
@kermitnc didn't work for me. 

How can I do a factory reset from ssh?

**Comment by volumio** [comment]
volumio updater factory

This error has been taken care, we are to release an update soon

**Comment by damien122** [comment]
@volumio nice, but how can I install the update when I can't access the web ui?

**Comment by volumio** [comment]
Can you let us know which plugins you have installed?

**Comment by damien122** [comment]
Backup & Restore, Autoplay (one of the two) and Spotify Connect

**Comment by damien122** [comment]
@volumio are there some news about this bug?

**Comment by volumio** [comment]
New release is out, which should fix the issue. 
Pleasee confirm it does and close the issue in this case.

**Comment by damien122** [comment]
And how should I install this fix when I can't access the frontend? I have just ssh access.

**Comment by volumio** [comment]
You can reset to factory with

volumio updater factory

Then you will be able to update

**Comment by damien122** [comment]
Sorry but I didn't understand how to call the "volumio updater factory"

**Comment by volumio** [comment]
From ssh command line

**Comment by damien122** [comment]
bug is fixed with release 2.699
