### ISSUE TITLE
Local Radios Wont Load

### ISSUE THREAD

**Issue by jammininmypjs** [volumio/Volumio2#1898]
It just hangs and never fully loads the local radio stations in the Web Radio

**Comment by xipmix** [comment]
We'll need more info to help with this.
Can you provide an example url, and perhaps a copy of the data file (/data/favourites/my-web-radio) and config (/data/configuration/music_service/webradio/config.json).
Also a log dump might be helpful; reboot, then try to access the webradio, then capture the log.
