### ISSUE TITLE
Support for redshift

### ISSUE THREAD

**Issue by suuuehgi** [volumio/Volumio2#1904]
Hi,

I would like to bring in the idea of redshift on the touch ui.
I would love it since at night my little hdmi touchscreen is really hard on my eyes.

Thanks a lot!

**Comment by volumio** [comment]
Can you elaborate more on what is redshift?

**Comment by suuuehgi** [comment]
> Can you elaborate more on what is redshift?

Yes, certainly. Sorry, in my filter bubble it's as mandatory as an adblocker.

[Redshift](https://en.wikipedia.org/wiki/Redshift_(software)) filters out blue light what messes with your circadian rhythm (e.g. bad sleep; by significantly suppressing [melatonin](https://en.wikipedia.org/wiki/Melatonin) secretion) and _massively_ reduces eye-strain at night.

[![image of f.lux in action](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/F.lux_stitched_screenshots.jpg/640px-F.lux_stitched_screenshots.jpg)](https://en.wikipedia.org/wiki/File:F.lux_stitched_screenshots.jpg)

It gradually dims according to your location, time and max values. In my experience people regularly don't notice it until they disable it during the night and their eyes burn away.

I head it would work with the experimental OpenGL driver from `raspi-config`.

**Comment by volumio** [comment]
Not really a volumio thing, since browsers or apps can achieve that

**Comment by suuuehgi** [comment]
I'm not aware that browsers can do that and I don't have apps in Volumio. Maybe you over-read that I'm talking about my hdmi touchscreen driven by the Volumio Touch Display Plugin.

**Comment by volumio** [comment]
Ah, now I understand. 
I don't think we'll be able to do it anyway...
