### ISSUE TITLE
Spotify Premium Indication

### ISSUE THREAD

**Issue by suuuehgi** [volumio/Volumio2#1908]
Good morning,

I just tried the Spotify plugin for a while without success before I found this warning in the logs:

```
[WARN] Login failed: User needs a premium account
```

Afaiks there is no information about it in the UI - maybe you could incorporate it there.

It currently states `Spotify Login failed: Please check username and password` what is clearly not the case.

And I also recommend to change the plugin description `Spotify plugin for Volumio2` to something indicating the sole support for premium accounts.

Thanks for the work!

**Comment by xipmix** [comment]
I think this issue really belongs in https://github.com/volumio/volumio-plugins, could you open it there or at least cross-ref to this issue?

**Comment by ashthespy** [comment]
FWIW it does mention it on the plugin details page when you go to install it.. 
![image](https://user-images.githubusercontent.com/16233271/76322110-413f7f00-62e3-11ea-8ec3-0a0cf68fbcef.png)
