### ISSUE TITLE
Browsing library

### ISSUE THREAD

**Issue by gkkpch** [volumio/Volumio2#192]
current commit: browsing is noticeably faster than before!
Small issue: when selecting an album from the library, the queue shows more than one copy of the contents

**Comment by balbuze** [comment]
for me I don't see that problem. In which case does it occurs ? With any album ? which file format (I use flac)

**Comment by gkkpch** [comment]
most of them, some of them contain .wav, .flac, .mp3. I select one and then the songs in the playlist tab show up multiple times

**Comment by balbuze** [comment]
I use the very last webUI (18e8a2252b0f8248301e6e3b219a81d018257dd6), and you ?

**Comment by piercer** [comment]
I also see this issue. If you ad an album, then add another album you will see multiple entries for both albums in the queue. Flac format files.

**Comment by gkkpch** [comment]
By coincidence used a .cue file today, this does not duplicate queue entries!
