### ISSUE TITLE
Update mpd

### ISSUE THREAD

**Issue by suuuehgi** [volumio/Volumio2#1923]
Hi,

I noticed that volumio uses a really old (v0.20.18; Feb 24, 2018) version of mpd. This causes e.g. webm files, as e.g. Youtube uses them, to be non-seekable.

Concrete scenarios:

  - I played until somewhen, try to seek and it falls back to the start of the file.
  - I have a long file and can't jump.

Afaics this has been [fixed on Feb. 4](https://github.com/MusicPlayerDaemon/MPD/issues/719), release v0.21.20 and above.

Is there any chance this is to be updated soon?

Thanks a lot! :-)

**Comment by speeedturtle** [comment]
> Hi,
> 
> I noticed that volumio uses a really old (v0.20.18; Feb 24, 2018) version of mpd. This causes e.g. webm files, as e.g. Youtube uses them, to be non-seekable.
> 
> Concrete scenarios:
> 
> * I played until somewhen, try to seek and it falls back to the start of the file.
> * I have a long file and can't jump.
> 
> Afaics this has been [fixed on Feb. 4](https://github.com/MusicPlayerDaemon/MPD/issues/719), release v0.21.20 and above.
> 
> Is there any chance this is to be updated soon?
> 
> Thanks a lot! :-)

is it possible to update MPD to latest version downloaded from MPD official site?

**Comment by volumio** [comment]
MPD will be updated when we finish the buster porting of Volumio, as of now it's not possible since we miss quite a lot of dependencies
