### ISSUE TITLE
Lost volumio.log with update to 2.773

### ISSUE THREAD

**Issue by kermitnc** [volumio/Volumio2#1956]
RPI 3B+ Hifiberry Digi+ Pro

Once again the playback died while skipping to a different song using tidal.

I tried therefore to search the volumio.log for some reasons but the file volumio.log is missing.
Afterwards I created the file volumio.log but no entries at all. After a reboot, the created file is gone.

**Comment by volumio** [comment]
volumio.log has been removed.

you can access full log by doing: sudo journalct -f

**Comment by ashthespy** [comment]
This was done in https://github.com/volumio/Volumio2/pull/1951 as it's redundant as it's not saved across reboots. 

tl;dr `cat volumio.log` == `journalctl -o cat -u volumio.service` 

PS: I normally add an alias:
```bash
echo -e "alias vollogs='journalctl -f -o cat'" | sudo tee -a /etc/bash.bashrc
```
