### ISSUE TITLE
System Update Modal

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2#201]
Just ran the system update, clicked the restart button, rpi reboots and the volumio UI comes back behind the update modal with no way of closing the modal just leaving the restart system option.

Modal either needs to close on system restart or needs to have the ability to close it. Escape works, but that's not very obvious or helpful on a touch-screen device.

![image](https://cloud.githubusercontent.com/assets/85802/12728953/2d1cd9a6-c91c-11e5-9187-aee411396dfd.png)

**Comment by balbuze** [comment]
I noticed that restart system does shutdown (or halt) instead of reboot. I have to unplug/plug the rpi to restart
