### ISSUE TITLE
Websocket api Play N from queue is broken?

### ISSUE THREAD

**Issue by Joni-Salminen** [volumio/Volumio2#2021]
Hey, I'm building android client for my needs and noticed that the websocket api does not work for some commands, or the documentation is misleading.

`socket.emit("play", X)` where x is the position of song in queue, is what i expect the command to be.

I tried to look at at the source, but i have zero javascript experience, so that did not really help me forward.

The usual media controls seems to work fine.(play, pause, skip...etc and volume control) 

If it matters i do have volumio on RPI4, latest official image from the website.

**Comment by xipmix** [comment]
can you post a log of what happens when you try this? https://volumio.github.io/docs/User_Manual/Sending_logs_for_troubleshooting.html

**Comment by Joni-Salminen** [comment]
Hi, sure i can, you find it here(?) -> http://logs.volumio.org/volumio/613CVzk.html
I dont know if the log contains anything since the Live log found on mydevice/dev page does not show anything when i try this command via websocket api, where as it does output information when doing the same with rest api.

as for now i decided to use workaround of using rest api interface for the play X from queue, since that seems to work as expected.

**Comment by Joni-Salminen** [comment]
This can be closed, the issue was the implementation details of websocket android library, which i did overlook.
