### ISSUE TITLE
volumio - nas power order

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#204]
If I power volumio and later my nas, this one is not mounted. The only way I found (without rebooting) is to edit mount (with no change) and save it, refresh the page and now it appears to be mounted and rescan.

**Comment by mpasteur** [comment]
I think we can't do anything to avoid it..  Maybe a button to retry if mounted is false?

**Comment by balbuze** [comment]
Or check the mount before playing, because you can list songs, select them to be played but of course it won't play.
