### ISSUE TITLE
Clean up stale issues

### ISSUE THREAD

**Issue by ashthespy** [volumio/Volumio2#2081]
There are a lot of open issues that are no longer relevant (Issue fixed, versions have changed) and makes things quite untraceable and a lot of duplicates. 
Would be a good idea to do some spring cleaning and close all irrelevant issues!

**Comment by volumio** [comment]
I agree.also we can take the chance to set up some nice GH automation for auto clean up and closing stale issues

**Comment by ashthespy** [comment]
Is moot - repo (but not old issues) has been moved over to https://github.com/volumio/volumio3-backend
