### ISSUE TITLE
Pi Zero unresponsive after update to 2.878 

### ISSUE THREAD

**Issue by messismore** [volumio/Volumio2#2113]
After the update to 2.878 my Pi Zeros are no longer connecting to the network. I tried a fresh install but the Volumio hotspot doesn't come up, either.

**Comment by timhaute** [comment]
Same thing for me, upgraded from 2.873 to 2.878 from GUI.
I tried a fresh install of 2.878, no luck.
I had to download volumio-2.873-2021-02-19-pi.img.zip and do a fresh install to have my rpi zero working again.

**Comment by chsims1** [comment]
Similar posts on the forums for RPi0, RPi1 & RPi4.

**Comment by messismore** [comment]
Fixed with 2.882.
