### ISSUE TITLE
add new driver and overlay for our I2S-cards in Volumio

### ISSUE THREAD

**Issue by chipdipru** [volumio/Volumio2#2128]
Hello, we have prepared a driver and overlay for our I2S-cards. 
https://github.com/chipdipru/ChipDip-DAC-driver-Volumio
How can we add it natively in Volumio?
Which way?
Regards

**Comment by gmerrall** [comment]
Not a core dev but I'd start by looking in app/plugins/audio_interface/alsa_controller/
