### ISSUE TITLE
reboot after update or bash cmd

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#218]
After a update the system never reboot.
After a sudo reboot the system never reboot
Tested with RPIB and RPI 2

**Comment by volumio** [comment]
thanks! I'll investigate why this happens..

**Comment by muzbox** [comment]
Same here, after update this morning the system never restarted

**Comment by muzbox** [comment]
I can log on via SSH but the website is not available

**Comment by volumio** [comment]
But after a forced reboot (aka PSU removal) does the system restart fine?

**Comment by muzbox** [comment]
No, I then went and downloaded the new beta. It loaded fine first time

The second I edit config.txt for my iqaudio-dacplus and reboot it stops working.
 Tried this a number of times.

**Comment by balbuze** [comment]
In my case no problem after unplug - replug psu

**Comment by volumio** [comment]
When you edit config.txt you must have messed it .
What did you put in it?

**Comment by muzbox** [comment]
It is quite possible

initramfs volumio.initrd gpu_mem=16 force_turbo=1 dtoverlay=iqaudio-dacplus

is the line from the file

Interestingly though,I wonder why it worked before I upgraded and then not after without me editing the file.

This is my recent edit. So it is possible I have done something wrong. I could not find any documentation on how to do this correctly so if you can point out my mistake I would be grateful

**Comment by muzbox** [comment]
hi

I have updated to the latest versions, the good news is it does not stop working when I add the overlay.

The bad news is the overlay does nothing. only ALSA showing in the playback, it is not picking up my DAC

**Comment by muzbox** [comment]
this is my current version 

System version: 0.834 Released: Sun Feb 21 17:18:36 CET 2016

this is my config.txt

initramfs volumio.initrd gpu_mem=16 force_turbo=1 dtoverlay=iqaudio-dacplus

**Comment by muzbox** [comment]
Fixed it, for anyone else who finds this issue

initramfs volumio.initrd gpu_mem=16 force_turbo=1 
dtoverlay=iqaudio-dacplus

the setting needs to be on its own line
