### ISSUE TITLE
Airplay 2 Support

### ISSUE THREAD

**Issue by the-driver-x** [volumio/Volumio2#2180]
AirPlay 2 is now supported in the dev branch of shairport-sync [https://github.com/mikebrady/shairport-sync/tree/development](url)
Do you think it would be possible to implement it in a test version of Volumio?

Thanks

**Comment by volumio** [comment]
Yeah interesting...
Can you open it in the volumio3-os ?

**Comment by schmurtzm** [comment]
Done: 
https://github.com/volumio/volumio3-os/issues/32
