### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by kaffeeringe** [volumio/Volumio2#219]
Hi! Thank you for your great work! It was really easy to set up Volumio and it sounds and looks great!

I love to listen to podcasts. How about support for podcasts in Volumio. 

I see there's a solution that adds podcasts to the mpd library: http://strobelstefan.org/?p=4513 But I don't want the podcasts among my music. 

How about you download the podcasts into a different folder and then stream them like they were radio stations?

**Comment by fanciulli** [comment]
Hello @kaffeeringe 

the podcast support would be a great plugin for Volumio. Unfortunately it would need some effort on the UI side since i'm not sure its UI is possible with the tools we currently have.

@volumio what do you think about? I think it would be a great testing platform for a lugin SDK....

**Comment by volumio** [comment]
Yep, let's go with the plugin SDK!

**Comment by volumio** [comment]
Done with a plugin

**Comment by biva** [comment]
Good news @volumio ! Thank you
Which plugin is it?

**Comment by DracoBlue** [comment]
https://github.com/ChrisPanda/volumio-podcast-plugin

**Comment by kaffeeringe** [comment]
How do I install it? The plugin doesn't show up in my plugin list

**Comment by biva** [comment]
Install an unofficial plugin
	1. SSH into machine
	2. Download zip using: wget <url>
	3. Uncompress in new folder
	4. Go into new folder
	5. Run: volumio plugin install

**Comment by kaffeeringe** [comment]
Okay. Thank you. ;-)
