### ISSUE TITLE
system integration check is failing - v3.512 (upgrade not possible)

### ISSUE THREAD

**Issue by camelcamro** [volumio/Volumio2#2191]
Hello
tried to upgrade to 3.5.12 (from 3.449)

there is nothing in logs visible ...
only telling on GUI: integration check failed)

is that really true ? it is not telling anything why it is failing in logs ? serious ?

funny, no changes were done, and neither either no hint which file is disturbing an upgrade.
it is going more and more worst.

and to present as a solution: set it back to factory settings - is not a solution - maxium a ptemp workaround.

additional, of course i alsoready have done changes (eg: fstab, cron, and some other things and also running a container "HOME ASSITANT" - which was now working in paralell - and now i should do everything again and maybe also loosing the HASS ? really ?

is it not possible to chow what is disturbing the UPDATE ? or debug posible to activate that it is showing the problem ?

don'T get me wrong, but volumio is going more and more instable (only my 2 cents)

**Comment by volumio** [comment]
Please use the volumio3 repo, this one is discontinued. 

This is a security feature: if you do manual mods, then Volumio cannot be updated safely because there is no way we can guarantee stable updates on heavily modified systems. This happens when you mod files under /volumio folders
