### ISSUE TITLE
volumio observed to crash after splash screen if custom settings used in pi imager

### ISSUE THREAD

**Issue by ASLOBEAR** [volumio/Volumio2#2193]
I tried to apply some custom settings in the raspberry pi imager (SSH enabled, unique hostname) and the software did not seem to work. On first boot, there was some text that I did not capture. Reflashing without custom boot settings seems to start up correctly. No further effort to diagnose issue made, software seems to run correctly now.

**Comment by ASLOBEAR** [comment]
Works

**Comment by ASLOBEAR** [comment]
just because I don't know where else to put it, the fact that it creates an adhoc network then uses that to connect to your personal network, I think, is SO COOL! nice software. Really, there is no need to want to use custom settings in pi imager.

**Comment by wisemoth** [comment]
Thanks @ASLOBEAR - this helped me just now!
