### ISSUE TITLE
dlna

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#227]
I've got a device running Volumio 1.55 and 2 running Volumio2. From my Ubuntu laptop I can stream using pulseaudio-dlna to volumio 1.55 but for Volumio2 I got a message "02-13 17:56:51 pulseaudio_dlna.plugins.upnp.renderer          INFO     The device "volumio2iq (DLNA)" does not specify a service transport url. Device skipped! " for both V2 devices.

**Comment by volumio** [comment]
You're right... It should be fixed with this:
https://github.com/volumio/Volumio2/commit/3bed1b346bb6ca901c8724fd2543cdf561f099ca

**Comment by balbuze** [comment]
ok now! Thank you
