### ISSUE TITLE
Side Menu Links aren't clickable

### ISSUE THREAD

**Issue by jbmfg** [volumio/Volumio2#241]
Since using the update function in the app, I am no longer able to click the sidemenu items other than "My Music."

**Comment by volumio** [comment]
Please try with this version 
http://updates.volumio.org/pi/volumio/0.832/volumio-0.832-2016-02-17-pi.img.zip

**Comment by jbmfg** [comment]
That fixed it.  Should the update function in the app not be used?

**Comment by volumio** [comment]
Yes is meant to be used ... But we had some problems with the intermediate version...
