### ISSUE TITLE
volume control

### ISSUE THREAD

**Issue by Nerz86** [volumio/Volumio2#261]
Hey.
I have following issue.
When you change the volume (for example over ssh with "mpc volume 75") and then you go to the web page the volume will be only 25.
It seams that the web page did not load the current volume.

**Comment by volumio** [comment]
No. Volumio changes (and retrieves) Volume directly on ALSA. MPD's volume is not used at all

**Comment by Nerz86** [comment]
All right, i understand. But how i have to change the volume over ssh. I tried it with "amixer cset numid=1 80%" but i have the same problem. When i go to the web page the volume will be changed to 25. Can you tell me how to change the volume directly on ALSA?
Thanks a lot.

**Comment by balbuze** [comment]
And with alsamixer ? but your dac must have hardware mixer, or you have to create a virtual device "softplug" to be able to change to volume
