### ISSUE TITLE
Volumio not start on ubuntu 14.04 lts

### ISSUE THREAD

**Issue by vtec83** [volumio/Volumio2#263]
root@test:/opt/volumio# node index.js
info: -------------------------------------------
info: -----            Volumio2              ----
info: -------------------------------------------
info: -----          System startup          ----
info: -------------------------------------------
info: Loading plugins from folder /opt/volumio/app/plugins/
info: Loading plugins from folder /data/plugins/
info: Loading plugin "system"...
info: Loading plugin "network"...
info: Loading plugin "networkfs"...
info: Loading plugin "services"...
info: Loading plugin "volumiodiscovery"...
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
info: Applying required configuration parameters for plugin volumiodiscovery
Discovery: StartAdv! undefined
Discovery: Started advertising... test - undefined
info: CoreCommandRouter::executeOnPlugin: system , registerCallback
info: Loading plugin "dirble"...
info: Applying required configuration parameters for plugin dirble
info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
info: [1456746010212] CoreMusicLibrary::Adding element WebRadio
info: CoreCommandRouter::BroadCastMessage pushBrowseSources
info: Loading plugin "alsa_controller"...
info: Loading plugin "upnp"...
info: [1456746010218] Starting Upmpd Daemon
info: CoreCommandRouter::executeOnPlugin: system , registerCallback
info: Loading plugin "alarm-clock"...
info: Loading plugin "albumart"...
info: Loading plugin "airplay_emulation"...
info: [1456746010259] Starting Shairport Sync
hw:0,0
info: Plugin example_plugin is not enabled
info: Loading plugin "mpd"...
info: Loading plugin "spop"...
info: [1456746010377] ControllerSpop::loadTracklistFromDB
info: Loading Spop tracklist from DB...
info: Loading plugin "updater_comm"...
info: Plugin mpdemulation is not enabled
info: Loading plugin "websocket"...
info: BOOT COMPLETED

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at EventEmitter.listen (/opt/volumio/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/opt/volumio/index.js:10:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
root@test:/opt/volumio# node index.js
info: -------------------------------------------
info: -----            Volumio2              ----
info: -------------------------------------------
info: -----          System startup          ----
info: -------------------------------------------
info: Loading plugins from folder /opt/volumio/app/plugins/
info: Loading plugins from folder /data/plugins/
info: Loading plugin "system"...
info: Loading plugin "network"...
info: Loading plugin "networkfs"...
info: Loading plugin "services"...
info: Loading plugin "volumiodiscovery"...
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
info: Applying required configuration parameters for plugin volumiodiscovery
Discovery: StartAdv! undefined
Discovery: Started advertising... test - undefined
info: CoreCommandRouter::executeOnPlugin: system , registerCallback
info: Loading plugin "dirble"...
info: Applying required configuration parameters for plugin dirble
info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
info: [1456746065166] CoreMusicLibrary::Adding element WebRadio
info: CoreCommandRouter::BroadCastMessage pushBrowseSources
info: Loading plugin "alsa_controller"...
info: Loading plugin "upnp"...
info: [1456746065172] Starting Upmpd Daemon
info: CoreCommandRouter::executeOnPlugin: system , registerCallback
info: Loading plugin "alarm-clock"...
info: Loading plugin "albumart"...
info: Loading plugin "airplay_emulation"...
info: [1456746065213] Starting Shairport Sync
hw:0,0
info: Plugin example_plugin is not enabled
info: Loading plugin "mpd"...
info: Loading plugin "spop"...
info: [1456746065330] ControllerSpop::loadTracklistFromDB
info: Loading Spop tracklist from DB...
info: Loading plugin "updater_comm"...
info: Plugin mpdemulation is not enabled
info: Loading plugin "websocket"...
info: BOOT COMPLETED

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at EventEmitter.listen (/opt/volumio/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/opt/volumio/index.js:10:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by volumio** [comment]
As stated on the docs this only works on volumio os
