### ISSUE TITLE
DSD 

### ISSUE THREAD

**Issue by hicaoc** [volumio/Volumio2#267]
DoP
Native DSD

**Comment by balbuze** [comment]
I've got DSD files and I can play them in Volumio2

**Comment by hicaoc** [comment]
@balbuze 
    Yes , the decoding to PCM can be played , but my DAC supports native DSD and DoP, currently no DoP and native DSD configuration on the UI 。I modified mpd.conf file to add options to achieve DoP play DSD 。

**Comment by budisaka** [comment]
@hicaoc 
how to edit mpd.conf..?
I've got error message : Error: no "edit" mailcap rules found for type "application/octet-stream"

**Comment by warrenjmcdonald** [comment]
sudo apt-get install vim
vim /etc/mpd.conf

In order to be able to stream dsd over pcm you should add the following to mpd.conf your device section:

dsd_usb         "yes"

example:
 
audio_output {
        type            "alsa"
        name            "Rockna - Audiobyte Silver Dragon"
        device          "hw:0,0"
        dsd_usb         "yes"
} 

Save 
restart volumio

**Comment by volumio** [comment]
Implemented
