### ISSUE TITLE
Volume2 after use rpi-update upgrade failed to start

### ISSUE THREAD

**Issue by hicaoc** [volumio/Volumio2#268]
Pi is the latest kernel version 4.1.18-v7 +, and Volumio2 of volumio.initrd files are not compatible, need to update volumio.initrd

**Comment by gkkpch** [comment]
Yes, currently we build volumio.initrd based on 4.0.6 for i2s compatibility reasons.
Just hold on a bit, this will be taken care of at a later stage.

**Comment by FishTest** [comment]
It doesn't support Rpi 1 or Rpi Zero too, and custom kernel cannot be support.i can't use my custom kernel modules with other device drivers.
