### ISSUE TITLE
Connect or create wifi

### ISSUE THREAD

**Issue by elalemanyo** [volumio/Volumio2#283]
Hi,
Will be a nice feature if you can set a default wifi setup, and if there is not possible to connect than volumio will create an own wifi.

Thanks!

**Comment by elalemanyo** [comment]
Maybe something like this: http://lcdev.dk/2012/11/18/raspberry-pi-tutorial-connect-to-wifi-or-create-an-encrypted-dhcp-enabled-ad-hoc-network-as-fallback/

**Comment by apinner** [comment]
I do like this idea, it would make volumio partially portable.

**Comment by martinchristophhess** [comment]
I also think this would make a big step to using volumio as a standalone player. Wow nice idea!!

**Comment by pujan14** [comment]
+1

**Comment by volumio** [comment]
This has already been implemented in latest versions

**Comment by elalemanyo** [comment]
👏

**Comment by volumio** [comment]
Done
