### ISSUE TITLE
[beta4] Add cifs network drive: Path must not start with /

### ISSUE THREAD

**Issue by dragotin** [volumio/Volumio2#284]
I was struggling to add a proper network drive to volumio 2 beta4. After long fiddling around I found out that the path must not contain a leading '/. Removing the slash made it work properly.

There should be some checks on the content of the entry fields with error indicators.

**Comment by apinner** [comment]
I was lucky and actually figured this out fairly quickly. However, I agree that this needs to be better explained or checked in the UI.

**Comment by volumio** [comment]
Yes absolutely... added on to do list...

**Comment by Atrejoe** [comment]
In my case even without adding the /, the share is not mounted:

![image](https://cloud.githubusercontent.com/assets/585091/13944839/ee25c80c-f008-11e5-9e9b-9c7501152cf3.png)

The share is on a Qnap NAS.

Can I see an error log anywhere?

**Comment by xipmix** [comment]
To view the error log, you will have to login over ssh
```
% ssh volumio@volumio
$ sudo journalctl
```
However I think I have addressed this in #877 .

**Comment by xipmix** [comment]
This should be fixed now, in the next release after 2.041. Please close this when it works for you.
