### ISSUE TITLE
Deleted network drives are still displayed

### ISSUE THREAD

**Issue by Atrejoe** [volumio/Volumio2#296]
```browse > music library > nas ``` also displays deleted network drives

**Comment by apinner** [comment]
I can't recreate this issue, can you provide some more information or even a screenshot?

**Comment by Atrejoe** [comment]
This was in the previous version. In the current-prerelease version I have a similar issue: right now with all shares deleted (and some time aited, and rebooted) it still shows some songs:
![image](https://cloud.githubusercontent.com/assets/585091/14251103/a77a415c-fa81-11e5-993a-e9fad888e9f5.png)

And so does my 'music library'

![image](https://cloud.githubusercontent.com/assets/585091/14251125/c5ce34d8-fa81-11e5-9e0e-54108d2a5a21.png)

When adding the share again (under another name)

![image](https://cloud.githubusercontent.com/assets/585091/14251159/03f4db40-fa82-11e5-9ea9-4309d4e93499.png)

They are both there:

![image](https://cloud.githubusercontent.com/assets/585091/14251177/17ca1dc4-fa82-11e5-8f1a-115853ade6af.png)

**Comment by apinner** [comment]
Thanks for the info.

**Comment by Atrejoe** [comment]
After leaving it a while (indexing the new location) the old location disappeared automagically.

(I now attempted to rename the alias for the share back to 'Hornbill' and no error was displayed, no confirmation either, and the alias was not persisted)

**Comment by apinner** [comment]
Are you saying it is resolved?

**Comment by Atrejoe** [comment]
Yes, but quite unclearly so. When a share is unmounted, you'd expect it to disappear immediately from your library.

**Comment by volumio** [comment]
No, it takes some time: mpd db needs to be updated
