### ISSUE TITLE
Timeout error message after adding a share

### ISSUE THREAD

**Issue by Atrejoe** [volumio/Volumio2#297]
Shortly after adding a mount, an orange toast was displayed, stating:

```Error scanning Database: Error: Command failed: /bin/sh -c /usr/bin/mpc update
error: Timeout```

This could be a bit more explanatory

**Comment by Atrejoe** [comment]
after this message a share seems to fail to mount

**Comment by apinner** [comment]
Was this using RC1?

**Comment by Atrejoe** [comment]
No, this was using the previous version. Currently I don't have this issue.
I can't add a folder withing a SMB share, but that seems to be known limitation

**Comment by apinner** [comment]
Ok, i will close for now
