### ISSUE TITLE
Volumio2 RC1 (volumio-0.861-2016-03-25-pi) IP address issue (fix IP configured in the image)

### ISSUE THREAD

**Issue by balages74** [volumio/Volumio2#303]
Dear All,
Noticed one small issue with Volumio2 RC1 (volumio-0.861-2016-03-25-pi).
Altho DHCP is set up for the lan0 interface, there is a fixed IP set up in /etc/dhcp/dhclient.conf (192.168.8.8).
Could you correct this please?
Thank you
Balázs

**Comment by apinner** [comment]
This is actually a build issue. https://github.com/volumio/Build
