### ISSUE TITLE
[rc1] /opt/vc

### ISSUE THREAD

**Issue by ajongsma** [volumio/Volumio2#307]
Apps like tvservice are located under /opt/vc/bin, this isn't included in the path.
I also noticed the LD_LIBRARY_PATH isn't set, this generates some errors with the shared object files.

"export LD_LIBRARY_PATH=/opt/vc/lib/:LD_LIBRARY_PATH" resolves the errors, might be an idea to take this environment variable into the default build?

**Comment by volumio** [comment]
Done here https://github.com/volumio/Build/commit/2f0241f45fdd22d40d744dcbace892a94c0a518d

Thanks for reporting!
