### ISSUE TITLE
[rc1] Pi isn't discoverable in OS X via Finder > Shared 

### ISSUE THREAD

**Issue by ajongsma** [volumio/Volumio2#308]
Resolved this minor, maybe not desirable feature, by installing netatalk. Perhaps left out intentionally?

**Comment by apinner** [comment]
Not sure I understand this issue, was 1.55 discoverable? 

Is this just to access the volumio shares on the Pi?

**Comment by ajongsma** [comment]
1.55 wasn't discoverable either as far as I remember. It's a personal preference of mine to have the netbios name viewable while, if I'm not able to airplay for some reason, it's a very quick way to see if the pi is actually reachable.

**Comment by apinner** [comment]
This just seems like it would add unnecessary elements to the build with little to no useful function. Considering you can just check the webUI or SSH.

**Comment by xipmix** [comment]
Bother. fatfingered the bug id. can someone please close this again?
