### ISSUE TITLE
[RC1] Sleep Timer should stop music, not shut down device

### ISSUE THREAD

**Issue by cshotton** [volumio/Volumio2#310]
The current Sleep Timer functionality is virtually useless. It actually shuts down the hardware device when the timer expires. This makes the alarm functionality impossible to use. That is, if you fall asleep to music and have the sleep timer turn it off, the device is powered down and the alarm functionality can never start the music again.

The desired behavior is for the sleep timer to expire and simply stop music playback. That way the mpd server can still be accessed without requiring a reboot of the host computer.

**Comment by apinner** [comment]
+1

**Comment by macmpi** [comment]
actually both usecases make sense: in some case you may want to actually power it down.
Maybe a toggle allowing either idle (stop music) or shutdown would make sense
Thanks!

**Comment by volumio** [comment]
https://github.com/volumio/Volumio2/commit/12a91f117e0736dc30b27f676631cc0197f893fa
