### ISSUE TITLE
[rc1] mpd is not listening an ipv4-Port 6600

### ISSUE THREAD

**Issue by dasarne** [volumio/Volumio2#312]
One can't connect with an external mpc to the volumio-mpd. 
netstat on the Rpi shows
`root@volumio:~# netstat -tulpn`
`Active Internet connections (only servers)`
`Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name`
`...`
`tcp6       0      0 :::6600                 :::*                    LISTEN      1/init`
`...`  
There is no connection on tcp. 

Discovered on a fresh installed Rpi with 
System version: 0.861 Released: Fri Mar 25 18:23:26 CET 2016

**Comment by xipmix** [comment]
Hm. I just tried this with 2.041 on Rpi
```
$ telnet 192.168.1.2 6600
Trying 192.168.1.2...
Connected to 192.168.1.2.
Escape character is '^]'.
OK MPD 0.19.0
^]
telnet> quit
```
Yet I get this from netstat
```
volumio$ sudo netstat -tulpn|grep 6600
tcp6       0      0 :::6600                 :::*                    LISTEN      1/init
```
Would you mind checking if this is still an issue, and close this if it you find mpd clients work?
