### ISSUE TITLE
[RC1] Can't add webradio to playlist

### ISSUE THREAD

**Issue by arnodeclercq** [volumio/Volumio2#320]
There isn't a way (or I didn't find it) to add webradio to a playlist.
Which in turn doesn't allow webradio to be used for the alarm feature.

Please add the possibility to add webradio to a playlist.
Or allow a webradio to be used for the alarm feature.

**Comment by apinner** [comment]
+1

**Comment by THEJAJO** [comment]
+1

**Comment by xipmix** [comment]
This has probably been fixed, can you test 2.001?

**Comment by THEJAJO** [comment]
It is fixed. Thanks.
