### ISSUE TITLE
[RC1] Navigating music library does not work in Safari 9.1

### ISSUE THREAD

**Issue by Turbofoehn** [volumio/Volumio2#322]
Hi everyone,

In the 'Browse' tab, clicking on a list item such as 'Music library' has no effect. Search does not work either. Both work in Chrome.

I am using 10.9.5.

<img width="886" alt="bildschirmfoto 2016-04-01 um 19 18 59" src="https://cloud.githubusercontent.com/assets/5689189/14214681/ad881ee2-f83e-11e5-95b5-71cf10f7cd59.png">
<img width="884" alt="bildschirmfoto 2016-04-01 um 19 20 58" src="https://cloud.githubusercontent.com/assets/5689189/14214723/e4703cc8-f83e-11e5-8c85-3ff92c6aed6e.png">

**Comment by apinner** [comment]
I don't quite understand the issue, what storage are you using?

**Comment by apinner** [comment]
Anyone else with a Mac that can confirm this?

It's really a UI issue.

**Comment by arnodeclercq** [comment]
I have some issues with iPad. 
Can't click on these links. They get highlighted but tapping, double tapping, holding, ... does not do anything. So it's probably Safari that's acting weird.
![image](https://cloud.githubusercontent.com/assets/1454216/14246904/7c2b3b30-fa6a-11e5-92e3-ca038445f086.jpg)

**Comment by apinner** [comment]
@kurtommy you are a Mac user aren't you. Have you had any issues with Safari?

**Comment by sbkivitz** [comment]
I can confirm this behavior on an iPhone with Safari.  I had started to debug it with the developer console and found that it was an issue with one of the supporting libraries (jsearch?), but for the life of me - I can't remember which one.  I will try to post more this evening when I'm home with my Pi3 / RC1.

**Comment by volumio** [comment]
Yes, please. The more we know, easier we'll solve this

**Comment by hicaoc** [comment]
I use safari  9.1 (11601.5.17.1) on osx 10.11.4  is ok . 

![image](https://cloud.githubusercontent.com/assets/8174631/14268642/ee712d12-fb0f-11e5-8f48-6d42554aa9ad.png)

**Comment by skikirkwood** [comment]
I am also using Safari 9.1 on OS X 10.11.4 for RC1 and everything is working fine.

On both my iPhone 6s and iPad 2, running the latest version of iOS, clicking through the UI is fine until there is a list of songs (or webradios) to choose.  Clicking on the row does nothing, you have to click on the icon of the 3 bars and bring up a pop-up menu to perform an operation on the row (which does work).

**Comment by apinner** [comment]
Yeah just single clicking/pressing on the row that is normal behaviour, you have to double click in order to play or open the hamburger menu.

**Comment by skikirkwood** [comment]
Ah, my bad.  Well, I can confirm that double-clicking in Safari on iOS with both an iPhone and iPad does nothing in RC1 for lists of songs or webradios.  But I just brought up Chrome on my iPhone and double clicking a list of songs or webradios also does nothing.  So it seems the problem is not Safari, it's iOS.

Double clicking in the Safari browser on my Mac works fine in the RC1 UI.

**Comment by skikirkwood** [comment]
BTW, double clicking on songs and webradios does not work in Volumio 1.55 on either Safari or Chrome on an iPhone.  That's why I didn't realize I needed to double-click on the item in RC1, double-clicking has never worked for me on iOS.

**Comment by apinner** [comment]
Double tap in chrome on android works, its starts the song playing.

**Comment by skikirkwood** [comment]
I just got out my Amazon Kindle HDx 7, which runs a heavily customized fork of Android.  In a side-loaded Chrome browser, double-clicking doesn't work, but double-clicking in the default Silk browser on the device does work!

So it really looks to be primarily an iOS issue.  The UI for both 1.55 and 2 is certainly a lot smoother being able to double-click a track versus bringing up the hamburger menu.

**Comment by apinner** [comment]
Weird.. I use the same tablet running cyanogenmod and chrome and double tapping works as expected. Also works on my Moto G running pretty much stock android.

**Comment by skikirkwood** [comment]
I do have an old version of Chrome on my Kindle, let me see if I can find a recent APK to see if that helps.

**Comment by skikirkwood** [comment]
Just installed the latest Chrome browser on my Kindle and double-clicking in RC1 does work.  Ok, looks like it's purely an iOS issue!  Good to have narrowed it down.

**Comment by skikirkwood** [comment]
Apparently double-clicking in iOS in Safari is reserved for zooming in on the screen, so that's why it's not triggering any events.  Here's an old article that describes a workaround with JQuery:

http://appcropolis.com/blog/howto/implementing-doubletap-on-iphones-and-ipads/

**Comment by apinner** [comment]
Was you aware of the above @kurtommy, no double tap on ios? :/

**Comment by sbkivitz** [comment]
Hi, sorry about the delay--

Here is a screenshot of a Safari debugger connected to my iPhone 6 / iOS 8.3
![image](https://cloud.githubusercontent.com/assets/5068282/14308181/4f878190-fb89-11e5-9c62-b6e68594a487.png)

This is the same error no matter which menu entry I try to click on (Favourites, Playlists, Music Library, Webradio).

How else can I help?  Seems @skikirkwood is onto something - but why would it work in some iPads / iPhones and not others?

**Comment by sbkivitz** [comment]
Drilling down a bit further in the debugger tab...
![image](https://cloud.githubusercontent.com/assets/5068282/14308299/20794478-fb8a-11e5-9137-784ea6b5252e.png)

This is jQuery JavaScript Library v2.1.4 - as indicated by the text header on this script

**Comment by kurtommy** [comment]
@sbkivitz you spot the problem, is the lack of performance API. I'll fix that easily :)

**Comment by skikirkwood** [comment]
That's strange.  I'm running iOS 9.3.1 on both my iPhone 6s and iPad 2, just hooked up the Safari debugger on my iMac to both, and got no errors at all on the Volumio 2 RC1 pages on either device.

That said, I think this is totally orthogonal to the issue that my understanding now is that Safari in iOS captures double-click events for screen zooming, so it will always be a NOOP for Volumio.  

I am also wondering why not just choose a single click event for selecting a song or webradio to play.  That's the default UI for most music applications on mobile devices (e.g. Spotify), so it's what people are used to.
