### ISSUE TITLE
[RC1] Menu should close/hide when clicking outside of it

### ISSUE THREAD

**Issue by arnodeclercq** [volumio/Volumio2#333]
Maybe this is mainly a personal preference but I think it would be better if the menu (that pops up when clicking the cogwheel) closes/hides when clicking outside of it.
Now you can navigate to another page while it stays open. Which, in my opinion, is not the best UX.

**Comment by apinner** [comment]
As you say, that's a matter of preference. I don't mind it staying open.

I suppose the question is, whats the problem with it staying open or whats the benefit of it closing?

**Comment by arnodeclercq** [comment]
It would be consistent.
If you click on an item in the menu it navigates to that page and closes the menu.
If you click outside of it and, for example, click on the browse link it navigates to that page but leaves the page open. Plus, it saves a click.
Also, on mobile it would be easier if the button to close the menu is located where the cogwheel is that opens it. Like how it's done on desktop.

**Comment by apinner** [comment]
@kurtommy any thoughts?

**Comment by kurtommy** [comment]
We'll do those changes in the next sprint :)

**Comment by apinner** [comment]
Has been resolved and will be in the next release.
