### ISSUE TITLE
Suggestion: Create checksum to verify downloaded image

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#335]
Wouldn't it be good to have SHA256 checksum files for the unzipped .img file to verify it (for security and integrity)?

**Comment by apinner** [comment]
I agree, nice idea

**Comment by gkkpch** [comment]
I suggest to use md5, it is twice as fast and for file integrity test md5 is sufficient. 
The build scripts can easily produce that, it is just a single line of code extra.
File base name would be identical to that of the zip file, and .md5 as the file extension.
The volumio builder would then have to copy that to the update repo as well.

**Comment by xipmix** [comment]
This has been done (a different way than my PR); issue can be closed
