### ISSUE TITLE
WiFi Issue

### ISSUE THREAD

**Issue by jncraig** [volumio/Volumio2#339]
I can now (RC2) select WiFi and it seems to be much better than previous betas.  But, if I unplug the ethernet cable, I can't connect using WiFi alone.

**Comment by apinner** [comment]
How are you trying to connect? volumio.local or the WiFi IP address?

**Comment by jncraig** [comment]
If I connect to WiFi, reboot and disconnect the ethernet cable before rebooting starts, then it comes up with the working WiFi connection.

**Comment by apinner** [comment]
Are you saying its resolved?

**Comment by jncraig** [comment]
I thought that it was.  It isn't.  I turned off the Pi and restarted it.  When it came up, it had lost the WiFi connection and did not reconnect.

**Comment by apinner** [comment]
Still not sure what your actual problem is, but it may have been resolved here; https://github.com/volumio/Volumio2/issues/337#issuecomment-207998248

**Comment by jncraig** [comment]
Thanks, I'll await the next RC!
