### ISSUE TITLE
Wifi?

### ISSUE THREAD

**Issue by jbmfg** [volumio/Volumio2#348]
Does wifi work for everyone?  I have not been able to get it working.  While plugged into ethernet it seems to connect but as soon as I pull the wired connection the wifi drops.  The wifi dongle works on raspbian, rune, volumio1, etc so I know its not the problem.

**Comment by apinner** [comment]
Possibly resolved here; https://github.com/volumio/Volumio2/issues/337#issuecomment-207998248
