### ISSUE TITLE
Needs a License

### ISSUE THREAD

**Issue by jomo** [volumio/Volumio2#35]
This repo has no LICENSE file. You should [choose a license](http://choosealicense.com/licenses/).

**Comment by ning-yu** [comment]
Yes, we definitely do need a license

**Comment by nickcannariato** [comment]
@jomo @ning-yu Opened a discussion on pull request #67. Suggestions are welcome as @volumio is unsure what license they would like attached to the project.

**Comment by philkunz** [comment]
Any updates here?

**Comment by nickcannariato** [comment]
@philkunz if you take a look at #67 you'll see the brief conversation on the topic. Seems like there's going to be a brief holding period for objection and then an official adoption of GPLV3. We probably need @volumio to verify this officially though.
