### ISSUE TITLE
[RC1] NAS shares "advanced options"

### ISSUE THREAD

**Issue by acidicX** [volumio/Volumio2#351]
The "advanced options" headline is a link, but does not look like a button.
As a user, I would expect a button, instead the functionality is hidden under what looks like an intermediate headline. 

It took me three attempts to find where I could enter the username/password ;-)

**Comment by apinner** [comment]
Agreed, its not very clear at all! It may be better in a collapsible element with a button to toggle.

@kurtommy another one for your ever growing list. ;)

**Comment by apinner** [comment]
Fixed here; https://github.com/volumio/Volumio2-UI/commit/95b39152a3f0763b4410a8ddf97f90eae6d8e4de

@volumio can you merge?

**Comment by acidicX** [comment]
cool! :+1:
