### ISSUE TITLE
dirble webradio list only first page 

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#353]
I come back to an old problem : when listing radio by country, only the first page from dirble is displayed. In a previous issues ( I don't refind it) we were talking about an infinite scrolling so that having the whole list returned by dirble

**Comment by apinner** [comment]
This issue? https://github.com/volumio/Volumio2/issues/136

**Comment by balbuze** [comment]
Yep it was the base

**Comment by gkkpch** [comment]
yes, we did check this a bit, when you manually enter an url and supply the page number, it seems to  work sort off, but even then I think there was an error with page 0 and page 1.
Still, good to know it is now listed as an issue.

**Comment by apinner** [comment]
Dirble replaced with shoutcast, no longer an issue

**Comment by balbuze** [comment]
But dirble still use when sorting radio by country it seems.

**Comment by apinner** [comment]
Which doesn't seem right, @volumio is that just a hangover that needs to be corrected?
