### ISSUE TITLE
Suggest to adopt MPD fork with both SACD ISO and Native DSD(Non DOP) support

### ISSUE THREAD

**Issue by xxxbugxxxx** [volumio/Volumio2#354]
@volumio 

As suggested in the forum and another issue. 

hicaoc's repo has incorporated SACD ISO(from Maxim's repo) and native DSD(fromMPD 0.2) support. 

It would be the perfect MPD version for Volumio 2:!

https://github.com/hicaoc/MPD.git

**Comment by apinner** [comment]
Why open another issue when https://github.com/volumio/Volumio2/issues/349 is the same?

**Comment by xxxbugxxxx** [comment]
Don't want it get lost;). Anyway it is in good hands. Thank you
