### ISSUE TITLE
Streaming outside the network...

### ISSUE THREAD

**Issue by TeenTin** [volumio/Volumio2#368]
Can RC1 stream music (from NAS) outside the network to the internet, so that a smartphone can play the music ?

If not, is it possible to add this ?

Thanks for your attention.

**Comment by apinner** [comment]
That's not really what volumio is about. It is a music player not a server. You can control volumio with your phone, but volumio will not stream music to your phone.

There are tons of options available that can stream music outside of your home network to phones and tablets. I use plex for this purpose but there are plenty of others.
