### ISSUE TITLE
Cannot connect to open wireless network on RC1

### ISSUE THREAD

**Issue by menew** [volumio/Volumio2#369]
Device: Raspberry Pi 3
Version: System version: 0.86, Released: Fri Mar 25 18:23:26 CET 2016

With network configuration view on web interface, I can connect to protected wifi network without any trouble. But when I try to use open wifi network (without password), `wpa_supplicant` daemon died immediately with error and wireless functionalities stopped until next reboot.

As far as I examined, `key_mgmt = NONE` line in `/etc/wpa_supplicant/wpa_supplicant.conf` seems to be causing the syntax error.  So I edited that line to `key_mgmt=NONE` (no spaces around equal) by hand and rebooted, then the device could connect to the open network correctly.

I think this is a bug caused by line 224 in `/volumio/app/plugins/system_controllers/network/index.js`, but I'm not confident. Is there a better way to fix my trouble?

**Comment by apinner** [comment]
I think you might be right.. Thanks!
