### ISSUE TITLE
WebUI Fails to Receive State Push

### ISSUE THREAD

**Issue by ning-yu** [volumio/Volumio2#37]
I think I see what happened - my fault :flushed: 

I had changed the names of the websocket events during an effort to simplify the websocket interface plugin. When it was decided to revert to the old version, I reverted the names of the events which are listened for, but forgot to revert the names of the events which are emitted. Thus `volumioPushState` is currently `pushState`.

Now that we have a chance to re-examine these event names, I think we can strip the "volumio" prepended to each event. This was used back in the day when direct commands were also sent to spop and MPD. Now that the clients only talk to Volumio, the extra tag is no longer needed. Thus, `volumioPlay` becomes just `play`, and so on.  I'll also change `getLibraryIndex` to `getLibraryFilters` per request.

I will update the websocket API in the wiki to reflect the new configuration.

**Comment by volumio** [comment]
Yes, that was needed and it makes the WS API more clear, which is not bad at all. Now we just need to update the static UI..
