### ISSUE TITLE
Rename "multiroom" output

### ISSUE THREAD

**Issue by escoand** [volumio/Volumio2#370]
Multiroom is misleading in my opinion. Maybe something like "UPNP renderer" is more hepful.

**Comment by escoand** [comment]
or "UPNP receiver"

**Comment by volumio** [comment]
It's actually multiroom... A bit of patience and you'll see what it really does...

**Comment by escoand** [comment]
OK, are you interested in a really multiroom icecast audio interface? I tested it quick and dirty with my installation and try do create an audio interface of it.

**Comment by rlucian** [comment]
Hey, what this suggests is great news, having more devices in sync when on the same network and same feed would be G.R.E.A.T.

using it on the RPi3 btw... great job!

**Comment by apinner** [comment]
As this isn't an issue, i'm going to close.

Multiroom is being worked on still.
