### ISSUE TITLE
Volumio2 is very promiscuous

### ISSUE THREAD

**Issue by aqw** [volumio/Volumio2#374]
By default there's a lot of services available on the network. Samba, rpcbind, mdns, upnp, etc. I understand the logic of doing this by default, for a seamless out-of-box experience for users. However, I would like to be able to configure Volumio so that it is adaptable to non-home networks. Currently, I can't find a list enumerating these services and no UI to disable them.

Also, as a note, when I remove the avahi-daemon service, the Volumio service fails to start. This is suboptimal IMO. ;-)

---Alex

**Comment by volumio** [comment]
Yes, we'll offer the chance to disable this services...

**Comment by Alexqw** [comment]
Awesome. Great to hear. :-)
