### ISSUE TITLE
Failure to detect Mamboberry HiFi DAC+

### ISSUE THREAD

**Issue by brendan-pike** [volumio/Volumio2#391]
I tested RC1 with my Mamboberry which works fine with Volumio 1. Unfortunately it was unable to detect it at all.  To clarify I did enable I2S.

**Comment by apinner** [comment]
The Mamboberry was only added in this commit https://github.com/volumio/Volumio2/commit/6f705ab2e605508942321b4c4c3197f9cea1d7b9 on April 2nd so its not currently included in the RC1 build.
