### ISSUE TITLE
Selecting the DAC on an OdroidC2 needs a reboot

### ISSUE THREAD

**Issue by gkkpch** [volumio/Volumio2#392]
The RC1 version needs a reboot after selecting the DAC as the output device. Failing to do that results in a plop and noise when starting a track. After reboot /etc/modules holds both snd_soc_pcm5102 and snd_soc_odroid_dac, Volumio starts OK. 
Perhaps not both modprobes are done when selecting the DAC? Could also be it works as designed?
Anyway, easy to reproduce for someone with a C2 ( @volumio :) ) and low prio.

**Comment by codewarriorFX** [comment]
Hi, was the DAC connected via I2S or a USB controller?

**Comment by gkkpch** [comment]
ooops, should have closed this one ages ago as this has been resolved.
But to answer your question, yes, it was connected to i2s.
Connecting an usb audio DAC usually works on the fly as far as I know.

**Comment by codewarriorFX** [comment]
LoL, I posted very recently on the Issues about connecting an PCM5102 via I2S. But the dac is asynchronous. Maybe you can help me?

**Comment by gkkpch** [comment]
Saw it, not looked at it yet. Will do...

On 21 Dec 2016, at 19:00, Peter <notifications@github.com> wrote:

LoL, I posted very recently on the Issues about connecting an PCM5102 via I2S. But the dac is asynchronous. Maybe you can help me?
