### ISSUE TITLE
[RC1][WebUI] Static DHCP doesn't work

### ISSUE THREAD

**Issue by THEJAJO** [volumio/Volumio2#396]
I'm not able to set static IP.

When I try to set up, it shows it was successful, but when I go back to the Network setting it has still DHCP enabled. The static IP address which was set before doesn't work.

Raspberry Pi 2

**Comment by apinner** [comment]
I think this may be a duplicate of https://github.com/volumio/Volumio2/issues/337 which has been resolved but not in a release yet.

**Comment by apinner** [comment]
If this is a different issue to 337 then please reopen.

**Comment by THEJAJO** [comment]
In this case I'm writing about LAN, not WLAN, and changing the setting using WebUI (web browser), not console connection.

If I have permissions, I will re-open the issue.

**Comment by apinner** [comment]
Can confirm that this doesn't work.

Error while setting network: TypeError: fs.creatOutputStream is not a function.

**Comment by apinner** [comment]
This is now resolved in RC2
