### ISSUE TITLE
Solve DNS uncaught error event

### ISSUE THREAD

**Issue by volumio** [volumio/Volumio2#40]
This is the error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: dns service error: unknown
    at Error (native)
    at MDNSService.on_resolver_done (/volumio/node_modules/mdns/lib/resolver_sequence_tasks.js:19:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/volumio/node_modules/mdns/lib/mdns_service.js:18:40)

It's quite random

**Comment by jomo** [comment]
Might be helpful
- https://github.com/agnat/node_mdns/issues/97
- https://github.com/agnat/node_mdns/issues/104

**Comment by volumio** [comment]
Thanks. We're gonna add an error handler to it.

Also, I noticed that we still have unhandled errors in some places in the system. Should start to place error handling while we code, as a good practice

**Comment by fanciulli** [comment]
Error catching has been introduced. This will restart the advertising or the browse functionality

**Comment by fanciulli** [comment]
Closing this issue since error never show up again after update
