### ISSUE TITLE
Need ability to turn off/on wireless.

### ISSUE THREAD

**Issue by XiozTzu** [volumio/Volumio2#411]
I keep my RPi wired so would like to disable wireless to save power and eliminate wireless interface for other devices.  I have to blacklist the drivers to accomplish this but would like to have something in the interface.  If it were not for this issue I could fully configure Volumio2 from the web interface.

**Comment by volumio** [comment]
Interesting... I'll add an option

**Comment by apinner** [comment]
Presumably this only applies to the RPi3?

**Comment by XiozTzu** [comment]
Yes, as far as I know.

**Comment by apinner** [comment]
@volumio any plans to add this?

**Comment by xipmix** [comment]
Related: #780

**Comment by xipmix** [comment]
Pretty sure this feature is in now. @XiozTzu can you confirm with 2.031 or later?
