### ISSUE TITLE
Need the driver Hifiberry DAC for Audiophonics I-Sabre DAC range

### ISSUE THREAD

**Issue by Trillien** [volumio/Volumio2#417]
Hello,
I use a Raspberry Pi2 B and try Volumio 2 last version RC1.
I find no suitable DAC Model for my Audiophonics I-Sabre. On Volumio v1, the DAC perfectly works with DAC Model Hifiberry DAC. As of info Hifiberry DAC Plus doesn't work.
Is there any chance the Hifiberry DAC driver will be implemented on the next releases?
Regards,
Trillien

**Comment by apinner** [comment]
I believe it already has been and will be in the next release.
