### ISSUE TITLE
CD Playback: plugin to come?

### ISSUE THREAD

**Issue by macmpi** [volumio/Volumio2#423]
Hi,

There had been discussions to add support for CD playback (via USB) in previous Volumio 1.55.
Any chance this will comes to 2.0?
Ideally this would get CD & Track info from online database...

Thanks!

**Comment by macmpi** [comment]
Any plugin wish-list available?

**Comment by volumio** [comment]
It will most likely be a plugin...
As for the wish list, done here:
https://volumio.org/forum/plugin-wish-list-t4361.html
