### ISSUE TITLE
Adjust Volume during radio stream

### ISSUE THREAD

**Issue by eggerph** [volumio/Volumio2#435]
hey
first of all: thank you!!! Volumio2 is awesome. Some minor bugs still exist but I have it already in day-to-day use. One bug I want to point out, is that Volume for radio streams can not be adjusted live. instead after changing volume I need to pause the stream and restart it. I use Volumio 2 RC1 on a RP3 with Hifiberry Dac+.

buth great work.
cheers
Philipp

**Comment by klokslagB** [comment]
To help pinpoint this problem I can confirm that I don't have this problem with Subtronics X400 using the IqaudIO DAC plus as DAC model under playback options. Currently on the master using RP2.

To be clear I can change the volume using my browser on my added webradio's in mp3 streaming format.
