### ISSUE TITLE
No wifi option in GUI on raspberry pi 3

### ISSUE THREAD

**Issue by Modhappy** [volumio/Volumio2#437]
When I installed the "volumio-0.861" image I have no option under Network on the wifi tab for the RPi 3s built in wifi. How do I connect using the built in wifi?

**Comment by apinner** [comment]
Full support for the RPi3 has been addressed and will be in the next Release Candidate. In the mean time you can take a look at this issue for a fix; https://github.com/volumio/Volumio2/issues/266

**Comment by JeroenfNL** [comment]
Can someone tell me when the new release is to be expected?

**Comment by apinner** [comment]
The final bits are being worked on at the moment, its quite a step forward from RC1 hence the additional wait time. It's not far off though.
