### ISSUE TITLE
Missing Spotify account configuratiom

### ISSUE THREAD

**Issue by fanciulli** [volumio/Volumio2#44]
Spotify configuration cannot be entered in the current configuration Ui. A section should contain services configurations.

**Comment by glucaci** [comment]
I've just made something in this direction. Where can I create a PR, on dev or master?

**Comment by volumio** [comment]
On Dev, but please wait since we're using a new method to do this...

**Comment by glucaci** [comment]
Maybe I can help, if you can describe your ideea and if nobody is working on it already.

**Comment by volumio** [comment]
I would love an helping hand on this... But we're in the design process still of the whole plugin management system, so there's nothing definitive yet...
I know it's not the best answer... Hopefully for middle of next week we'll have something working , and then you could jump in and give us your feedback and contribute.. I'll keep you  posted..
What do you think?

**Comment by glucaci** [comment]
Ok, I understand the situation. Till then, I will just try to take a look on Issues that are not so infrastructure linked.

**Comment by apinner** [comment]
Fixed with the spotify plugin
