### ISSUE TITLE
Album Art whichever song playing it's always the same

### ISSUE THREAD

**Issue by klokslagB** [volumio/Volumio2#445]
I have an issue with AlbumArt. I have a collection of songs in one folder on a mounted usb stick. When I play any song using the webbrowser (Music library usb ) the same jpeg always come up. 

My log:
```
May 29 20:24:58 volumio volumio[476]: info: /mnt/USB/*/muziek/*.mp3
May 29 20:24:58 volumio volumio[476]: info: /data/albumart/folder//mnt/USB/*/muziek/extralarge.jpeg
May 29 20:24:58 volumio volumio[476]: info: Sending file /data/albumart/folder//mnt/USB/*/muziek/extralarge.jpeg
May 29 20:24:58 volumio volumio[476]: info: Serving request took 11 milliseconds
```
I removed the one song with that albumart but still no luck. Willing to provide all necessary information.

I don't know if this has anything to do with the above issue but on music libary scanning I have this issue.

`ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: max_analyze_duration 5000000 reached`

I ran the stat bash command on the extralarge.jpeg and have the following info:

```
File: 'extralarge.jpeg'
  Size: 39673           Blocks: 80         IO Block: 4096   regular file
Device: b303h/45827d    Inode: 521329      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/ volumio)   Gid: ( 1000/ volumio)
Access: 2016-05-09 17:59:36.000000000 +0000
Modify: 2016-05-09 17:59:36.000000000 +0000
Change: 2016-05-09 17:59:36.000000000 +0000
 Birth: - 
```

**Comment by volumio** [comment]
It's by design. If a picture is found in a folder, is used as a default.
Since it's cached, you now see the cached one. Just remove /data/albumart
