### ISSUE TITLE
AK4490EQ DAC I2S or USB XMOS support

### ISSUE THREAD

**Issue by codewarriorFX** [volumio/Volumio2#456]
Does Volumio 2 has support for AK4490EQ DAC? through I2S or XMOS USB?

Please label this as an enhancement.

**Comment by apinner** [comment]
I don't think it does at the moment. I can't find that much information about it..

**Comment by kisset** [comment]
YES pi3 + volumio 2 + xmos USB + ak4490eq works very well.

**Comment by codewarriorFX** [comment]
Nice, how was the cpu consuming at high resolution files? Where you able to get it up to 32/384?

**Comment by apinner** [comment]
Closing as its not an issue. Feel free to keep discussing though.

**Comment by kisset** [comment]
I use files 24bits 96khz, It's excellent, I have not tried 32bits 384khz but with192khz the sound is read with some jerks. With volumio 1.55 no probleme for 24 bits 192khz but I would prefer 96khz.
How to know the cpu consuming?
