### ISSUE TITLE
Support SFTP

### ISSUE THREAD

**Issue by clsidxxl** [volumio/Volumio2#462]
I like manage the Volumio files with MobaXterm SFTP session,please support SFTP in Volumio 2

**Comment by apinner** [comment]
Which files do you want to manage?

**Comment by clsidxxl** [comment]
It's more easy and friendly to modify  for example the systeme file of DLNA (files.db,art cache),and other files ex.boot.ini or dtb, easily add credential file,modify Fstab,minidlna.conf,mpd.conf......

**Comment by apinner** [comment]
You can do all of this using SSH

**Comment by clsidxxl** [comment]
MobaXterm connect in SSH  to Odroid and  it's more easy manage file with SFTP

**Comment by clsidxxl** [comment]
you know MobaXterm SFTP?

**Comment by apinner** [comment]
Nope, never heard of it

**Comment by clsidxxl** [comment]
[http://www.zimagez.com/zimage/sanstitre92f51760d2aadaa4dcd9bfdb942d9eba.php](url)

**Comment by volumio** [comment]
Volumio has sssh/sito enabled by default.  Doesn't work with mobaxtem?

**Comment by clsidxxl** [comment]
no,don't work; tomorrow I will again install Volumio 2 and try again,I give you the error message when I want to copy a file in SFTP  session.

**Comment by xipmix** [comment]
HI, is this still a problem? If not please could you close this again.
