### ISSUE TITLE
Volumio RC2: No Webradio and can't adjust volume

### ISSUE THREAD

**Issue by SonosKiller** [volumio/Volumio2#484]
Running a Rpi3 a clean install of the RC2 on a new Sd card using no Dac just the audio jack.

Mp3 music works fine!
But no webradio channels works. 
The only sound I hear is the startup sound after a few seconds 

I can't change the volume in the playback dialog
note: the "Mixer control" in "Playback options" is empty and not changeable

Tried the sd card in an Rpi2B and done a re-flash, same problem

**Comment by apinner** [comment]
I can confirm that i am also having an issue with shoutcast radio stations.

Nothing happens, i just get a shoutcast URL show in the playback information.

**Comment by apinner** [comment]
![screenshot 2016-06-27 13 14 15](https://cloud.githubusercontent.com/assets/85802/16379345/0804d02c-3c69-11e6-992d-e4059cc39b0d.png)

**Comment by SonosKiller** [comment]
Old issue ! fixed in current version 2.031
