### ISSUE TITLE
RC2 Playback Options

### ISSUE THREAD

**Issue by apinner** [volumio/Volumio2#485]
I can confirm there is an issue with the playback options screen.

Despite having IQaudiO DAC selected my output device remains Audio Jack, changing it to the DAC will not stick.

Mixer controls is also empty.

**Comment by codewarriorFX** [comment]
I see also Mixer controls empty. Im using a USB dac.

**Comment by clemensmartin** [comment]
Is the behavior of not being able to control volume (on a HifiBerry DAC without HW volume control) also a result of this or is this a separate issue?

**Comment by apinner** [comment]
@clemensmartin we are aware of that issue and working on it.
