### ISSUE TITLE
Volumio2 RC2 for Odroid C2  --- Volume control U/S

### ISSUE THREAD

**Issue by superpat999** [volumio/Volumio2#487]
No Volume control on Odroid C2 Volumio RC2 using Xmos X20 USB DAC.
Dac outputs OK,  plays all Flac files submitted, but  on Volumio webpage "volume options",  the  Mixer box is greyed out,    On the "playback" page web volume controls do NOT have any effect.

regards P J K

**Comment by gkkpch** [comment]
Yes, there is an open issue for this, it has not been implemented yet.
