### ISSUE TITLE
WebUI or dev console

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#49]
Hi!
Sorry to ask, but even with a fresh install, I can't connect to webUI (still known problem?)
dev console was ok until I reboot...and now no more access.

**Comment by volumio** [comment]
Try from scratch 

systemctl disable volumio.service
rm -rf /volumio
git clone https://github.com/volumio/Volumio2.git /volumio
cd /volumio
npm install --unsafe-perm

Now to start everything you need to lauch manually with
cd /volumio
node index.js

**Comment by balbuze** [comment]
Thank you !
dev console is working...
What about webUI ? (blank page)

**Comment by mpasteur** [comment]
by default the submodule (in http/www) is not retrieved when you clone the repo. You have to get it by 'git clone --recursive https://github.com/volumio/Volumio2.git volumio'

**Comment by balbuze** [comment]
@mpasteur thank you, but it was an old problem...

**Comment by mpasteur** [comment]
you're right but i've just encountered this problem... So it can be usefull for the Internet :-)

**Comment by balbuze** [comment]
ok ;-)
