### ISSUE TITLE
RC2: Spotify Plugin without premium?

### ISSUE THREAD

**Issue by 8bitgentleman** [volumio/Volumio2#491]
Is it possible to use the spotify plugin without having a premium account?  A premium subscription allows for high quality sound, is that the only reason it's needed?

**Comment by balbuze** [comment]
I think it's rather due to the fact that only official app support non premium connection. It's not a volumio problem

**Comment by apinner** [comment]
Yes as balbuze said, unfortunately you need a premium account. That's a restriction by Spotify nothing that Volumio can do about that.
