### ISSUE TITLE
RC2: UI Behavior on errors when mounting file systems. 

### ISSUE THREAD

**Issue by clemensmartin** [volumio/Volumio2#493]
It would be a good idea to keep the data fields in the "Add new drives" dialog filled with the entered data  after an error occurs. 
In the current (RC2) version, all fields are set to blank if the mount does not succeed. 

Further, with an unsuccessful mount I end up with a bunch of mount points in the file system, but these don´t show in the user interface. 

A bit of feedback on the success or failure of a mount would be helpful.

**Comment by volumio** [comment]
Yes, on tofix list
