### ISSUE TITLE
Volumio2 RC2 for Odroid C2 - no acces from browser

### ISSUE THREAD

**Issue by johnyn6** [volumio/Volumio2#496]
I can´t connect from my browser. I use DHCP, router give IP, but only ssh, scp is working (putty, winscp). Ipconfig / flushdsn doesn´t help.
With RC1 I have no problem.
My config is C2 + 8GB emmc and ethernet cable, no wifi.

**Comment by volumio** [comment]
Could you add :3000 to your IP and see if that works?

**Comment by johnyn6** [comment]
Port 3000 doesn´t work.

**Comment by volumio** [comment]
If  you can ssh..
sudo journalctl -p 7 > /home/volumio/faillog.log

And paste the content of faillog.log here, if that fits (or try to get the error part)

**Comment by johnyn6** [comment]
[faillog.zip](https://github.com/volumio/Volumio2/files/339971/faillog.zip)

**Comment by volumio** [comment]
The mdns stack is failing, I don't know why.. 
Do you have multiple volumios? 
Which router do you have? Does it have a firewall?

**Comment by mardev7** [comment]
(Volumio2 RC2, Odroid C2 Hifi Shield)
It works connecting from my browser using http://volumio.local when I am connecting with a cable to my router. However, if I connect to my router using wifi (using my phone) it fails. Then I must use the ip number to be able to connect.

**Comment by apinner** [comment]
Are you using an Android phone by any chance?

**Comment by johnyn6** [comment]
I can test RC2 on C1+. RC1 is working on both odroids. I have router with openwrt and yes, it have firewall.

**Comment by mardev7** [comment]
@johnyn6 Yes, Android on my phone (and dd-wrt on my router).

**Comment by apinner** [comment]
I think that may be your problem. http://volumio.local won't work on android, you have to use the IP address. Its because android doesn't support mDNS, nothing that we can do to fix that.

However, if your volumio always has the same IP through either static or a dhcp reservation then you can use the add to homescreen feature in your mobile browser and the Volumio UI will open fullscreen like a native app.

**Comment by mardev7** [comment]
@apinner  Ok, great, thanks for the info! 
I just got my odroid and I am really impressed with Volumio, once the volume control is implemented it will be perfect!

**Comment by johnyn6** [comment]
On C1+ RC2 is working... So there is some problem in C2 build.

**Comment by johnyn6** [comment]
With newest RC2Fix-2016-07-31 still no web access. I want to try my C2 with another router, or only with fixed IP directly to my PC.
