### ISSUE TITLE
Airplay - Shairport interface feedback

### ISSUE THREAD

**Issue by muzbox** [volumio/Volumio2#497]
Whilst I await the tidal plug-in :)  my primary use of Volumio is to utilize Airplay from an apple device.

Currently there is no feedback at all in the interface showing that airplay is being played.

Can you please add metadata from the airplay stream to show what is playing on the screen

**Comment by codewarriorFX** [comment]
I am also looking  forward to this enhancement. I've been googling for a while how to get the metadata from shairport and I found this. Im going to try this after work and see if it works on my odroid and beaglebone. Airplay metadata output would be a nice implementation to Volumio 2.

https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=93928
