### ISSUE TITLE
Back button in Spotify Plugin

### ISSUE THREAD

**Issue by muzbox** [volumio/Volumio2#498]
The back button next to the home symbol does not work when you are in the spotify plugin

![image](https://cloud.githubusercontent.com/assets/11152840/16483698/2693256c-3ee8-11e6-9f4e-b36ab7375768.png)

**Comment by muzbox** [comment]
It does work once there are playlists.

Maybe you should not show it until you have entered a playlist

**Comment by skikirkwood** [comment]
The Back button for Spotify playlists never works for me, whether I have playlists displayed or not.

**Comment by volumio** [comment]
Fixed
