### ISSUE TITLE
[question] Check Airplay status...

### ISSUE THREAD

**Issue by codewarriorFX** [volumio/Volumio2#499]
Hi - I would like to know if there is a similar way for Airplay to check via telnet if is playing, pause or stopped, just like MPD and spop?

I have plans in mind to create a script that if I have a device connected to my Odroid via Airplay, show the Airplay logo on the oled screen.

**Comment by codewarriorFX** [comment]
This is on Odroid C2 with RC2.

**Comment by paviro** [comment]
Would also be nice if the webUI would show the status! Especially since [shairport-sync](https://github.com/mikebrady/shairport-sync) seems to be able to transfer metadata!

**Comment by volumio** [comment]
Yes, I started doing that (look at the Airplay_WIP branch), but it's not as simple as it seems...

**Comment by paviro** [comment]
Mhh really does not look that simple :D So chances are it is going to be there one day?

**Comment by volumio** [comment]
I hope so...

**Comment by codewarriorFX** [comment]
I tried to add the flag "-M <directoryname>" on the shairport command, but it doesn't seem to show the now_Playing file on the directory assigned.

Nope, is not that simple as it seems...
