### ISSUE TITLE
[RC2] Minor bug? Wrong file type is displayed during playback

### ISSUE THREAD

**Issue by figshot** [volumio/Volumio2#502]
This is a very minor bug, but I found it and I decided it's probably best to let you know anyway.

Volumio RC2 on RPi3, accessed using Safari. I have an external HDD hooked up to the home router. I have a bunch of Apple Lossless files in .m4a format in there. I open one, and the playback page shows an icon displaying the file type as .m4a. However, when I click on "Go to Artist," put the same file on the playlist and play it, it displays that the file type is .mp3, not .m4a. As far as I can tell, the actual playback is not affected.

**Comment by apinner** [comment]
That is indeed an odd one! Thanks for reporting
