### ISSUE TITLE
[RC2] Glitch when adding network drive without nickname

### ISSUE THREAD

**Issue by figshot** [volumio/Volumio2#503]
Thanks for the positive response to #502, @apinner. May I report an additional, but very slight glitch?

This might be specific to my system, but when I was adding a network drive, I didn't know that a nickname was required. When I added the network drive without the nickname, all settings pages became glitchy (playback settings through system all load empty pages, reboot/shutdown option displays but would not work, etc). Reloading the entire page resolves this issue.

**Comment by xipmix** [comment]
This has probably been fixed - if you try to add a network drive without an alias, it should warn you that the alias is missing and not add the drive. Try [2.001](http://updates.volumio.org/pi/volumio/2.001/volumio-2.001-2016-10-15-pi.img.zip) (go to /dev, turn on test mode, upgrade to 2.006 or whatever we're at)
