### ISSUE TITLE
[RC2] No sound with Hifiberry Dac+

### ISSUE THREAD

**Issue by terrybooth** [volumio/Volumio2#506]
[Same Problem with RC1]
Two problems: no sound output with HifiBerry Dac Plus configured as HifiBerry Dac - no errors on UI on replay just no sound.

Mixer control gives no list (I disable software volume control)

1.55 works perfectly on same hardware.

**Comment by apinner** [comment]
Yep we are aware of this issue and we are working on it.

**Comment by terrybooth** [comment]
I've found the threads on volumio.org now. Apologies.
