### ISSUE TITLE
Spotify playlists not always displayed

### ISSUE THREAD

**Issue by skikirkwood** [volumio/Volumio2#507]
I downloaded and activated the Spotify plugin for RC2 hotfix (June 30 release) and after plugging in my Spotify credentials tried to browse my Spotify playlists.  I had a screen with a folder icon, "Playlists" to the right, and the hamburger icon over on the far right.

Clicking on Playlists didn't result in anything.  I then plugged in my Spotify credentials a couple more times, got the same behavior, and then after a 5th or 6th try it worked.  I was able to play Spotify tracks, see them in the queue, etc.  I then went back to browse more Spotify playlists and same behavior as before.  After clicking around the UI, the playlists appeared again, then they disappeared again!

The Volumio log file shows this when I cannot browse Spotify:

2016-07-01T23:01:20.433Z - info: CoreCommandRouter::executeOnPlugin: spop , handleBrowseUri
2016-07-01T23:01:21.536Z - info: CoreCommandRouter::executeOnPlugin: spop , handleBrowseUri
2016-07-01T23:01:21.536Z - info: [1467414081536] ControllerSpop::sendSpopCommand
2016-07-01T23:01:21.538Z - info: ADDING DEFER FOR COMMAND ls
2016-07-01T23:01:21.547Z - info: FIRST BRANCH
2016-07-01T23:01:21.548Z - info: BEFORE: SPOP HAS 1 PROMISE IN STACK
2016-07-01T23:01:21.548Z - info: AFTER: SPOP HAS 0 PROMISE IN STACK
2016-07-01T23:01:21.551Z - info: FIRST BRANCH
2016-07-01T23:01:21.552Z - info: BEFORE: SPOP HAS 0 PROMISE IN STACK
2016-07-01T23:01:21.552Z - info: AFTER: SPOP HAS 0 PROMISE IN STACK

When the browse command does work I see a list of the Spotify playlists in the log file.  Using the latest versions of Chrome and Safari on a Mac running the latest release of El Capitan.  Overall I'd say 90% of the time I do not get a list of playlists, seems to be random when they do show up.

**Comment by apinner** [comment]
Do you have a Spotify premium account?

**Comment by skikirkwood** [comment]
Yes, I have a Spotify Premium account and it works fine on Volumio 1.    I could PM my credentials to someone for debugging if that would help.   
  

  
I was able to play Spotify tracks from my playlist, but 90% of the time clicking on the Playlist link resulted in nothing.   
  
  
  

  
  
>

**Comment by skikirkwood** [comment]
Here's some additional info.  I created a new Spotify Premium account, added a few playlists, and put the credentials of the new account (user: volumio2) into Volumio.   Browsing, playing Spotify playlists worked perfectly.  I then put the credentials of my original (user: altamontstudios) account back into the Spotify plugin in Volumio.  Back to the same issue of browsing Playlists stopped working.  Both are Spotify Premium, one works perfectly, one mostly does not work, but occasionally does.  Strange!

One guess here is I have a very large number of playlists with my altamontstudios account.  Perhaps some kind of timeout issue or something else regarding how large the data there is?

Again, be happy to PM credentials of both accounts if someone can help debug this, although if you are outside the U.S. you would need to VPN into a U.S. server since they are U.S. based Spotify accounts.

**Comment by skikirkwood** [comment]
After rebooting my Pi, I no longer see Spotify as an option in Browse.  The plugin is active, with the credentials of my original Spotify account.  I then put the credentials of my new Spotify account in to the plugin and Spotify showed up again under Browse.  Seems like this plugin does not like my Spotify account!  Here's the log after bootup when Spotify would not start:

1970-01-01T00:00:26.018Z - info: [26018] Shairport-Sync Started
1970-01-01T00:00:27.205Z - info: 
[27204] ---------------------------- Client requests Volume 22
1970-01-01T00:00:27.207Z - info: [27206] VolumeController::SetAlsaVolume22
1970-01-01T00:00:27.219Z - info: [27218] ------------------------------ 14ms
1970-01-01T00:00:27.230Z - info: [27229] VolumeController::Volume 22
1970-01-01T00:00:27.231Z - info: [27230] CoreStateMachine::pushState
1970-01-01T00:00:27.231Z - info: [27231] CoreStateMachine::getState
1970-01-01T00:00:27.232Z - info: [27231] CorePlayQueue::getTrack 0
1970-01-01T00:00:27.232Z - info: CoreCommandRouter::volumioPushState
1970-01-01T00:00:27.233Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
1970-01-01T00:00:27.234Z - info: [27234] InterfaceWebUI::pushState
1970-01-01T00:00:27.242Z - info: Pushing Favourites {"service":"webradio","uri":"http://yp.shoutcast.com/sbin/tunein-station.m3u?id=899590","favourite":false}
1970-01-01T00:00:30.345Z - info: Connecting to daemon
1970-01-01T00:00:30.366Z - info: SPOP command error:
1970-01-01T00:00:30.370Z - info:  Error: connect ECONNREFUSED 127.0.0.1:6602
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
1970-01-01T00:00:30.373Z - info: SPOP status error:
1970-01-01T00:00:30.374Z - info:  Error: connect ECONNREFUSED 127.0.0.1:6602
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
2016-07-02T17:08:32.636Z - info: Volumio called home
2016-07-02T17:08:39.386Z - info: mDNS: A device disapperared from network
2016-07-02T17:08:39.489Z - info: mDNS: Found device Volumio2
2016-07-02T17:08:50.768Z - info: mDNS: Found device Volumio2

**Comment by skikirkwood** [comment]
Ok, here's one more data point.  I telnet'd to the spop daemon and gave a "ls" command, just as the Volumio 2 Spotify plugin does.  I got back an array of my playlists, but the first entry was an empty object, so perhaps that is the cause of the problem with this one account:

ls
{
  "playlists" : [
    {
    },
    {
      "type" : "playlist",
      "name" : "Smooth Morning",
      "tracks" : 69,
      "offline" : false,
      "index" : 1
    },
    {
      "type" : "playlist",
      "name" : "Alexander Volosnikov – All These Melodies",
      "tracks" : 13,
      "offline" : false,
      "index" : 2
    },
    {
      "type" : "playlist",
      "name" : "Sunny Terrace – The Orbit",
      "tracks" : 10,
      "offline" : false,
      "index" : 3
    },
    {
      "type" : "playlist",
      "name" : "Phoria – Volition",
      "tracks" : 11,
      "offline" : false,
      "index" : 4
    },
    {
      "type" : "playlist",
      "name" : "David Arkenstone – Chillout Lounge",
      "tracks" : 10,
      "offline" : false,
      "index" : 5
    },
    {
      "name" : "Coastsider",
      "type" : "folder",
      "playlists" : [
        {
          "type" : "playlist",
          "name" : "Coastsider Roots",
          "tracks" : 941,
          "offline" : false,
          "index" : 7
        },
        {
          "type" : "playlist",
          "name" : "Coastsider Mark Knopfler",
          "tracks" : 261,
          "offline" : false,
          "index" : 8
        },
        {
          "type" : "playlist",
          "name" : "Wine Tasting",
          "tracks" : 28,
          "offline" : false,
          "index" : 9
        }
      ]
    },
    {
      "type" : "playlist",
      "name" : "Native Chill",
      "tracks" : 19,
      "offline" : false,
      "index" : 11
    },
    {
      "type" : "playlist",
      "name" : "Chillout Lounge",
      "tracks" : 10,
      "offline" : false,
      "index" : 12
    },
    {
      "type" : "playlist",
      "name" : "Audiophile Tracks",
      "tracks" : 51,
      "offline" : false,
      "index" : 13
    },
    {
      "type" : "playlist",
      "name" : "Peaceful Piano",
      "tracks" : 90,
      "offline" : false,
      "index" : 14
    },
    {
      "name" : "DW",
      "type" : "folder",
      "playlists" : [
        {
          "type" : "playlist",
          "name" : "DW May 2016",
          "tracks" : 30,
          "offline" : false,
          "index" : 16
        },
        {
          "type" : "playlist",
          "name" : "DW 2 Feb 16",
          "tracks" : 30,
          "offline" : false,
          "index" : 17
        },
        {
          "type" : "playlist",
          "name" : "DW Feb 16",
          "tracks" : 30,
          "offline" : false,
          "index" : 18
        },
        {
          "type" : "playlist",
          "name" : "DW Nov. 2",
          "tracks" : 29,
          "offline" : false,
          "index" : 19
        },
        {
          "type" : "playlist",
          "name" : "DW Archive",
          "tracks" : 89,
          "offline" : false,
          "index" : 20
        },
        {
          "type" : "playlist",
          "name" : "DW Nov. 9",
          "tracks" : 31,
          "offline" : false,
          "index" : 21
        }
      ]
    },
    {
      "type" : "playlist",
      "name" : "Indie Chillout.",
      "tracks" : 99,
      "offline" : false,
      "index" : 23
    },
    {
      "type" : "playlist",
      "name" : "Acoustic EDM",
      "tracks" : 59,
      "offline" : false,
      "index" : 24
    },
    {
      "type" : "playlist",
      "name" : "Productive Morning",
      "tracks" : 39,
      "offline" : false,
      "index" : 25
    },
    {
      "type" : "playlist",
      "name" : "Sine Music",
      "tracks" : 275,
      "offline" : false,
      "index" : 26
    },
    {
      "type" : "playlist",
      "name" : "Thomas Lemmer",
      "tracks" : 57,
      "offline" : false,
      "index" : 27
    },
    {
      "type" : "playlist",
      "name" : "Chillbar, Vol. 1 - 4",
      "tracks" : 66,
      "offline" : false,
      "index" : 28
    },
    {
      "type" : "playlist",
      "name" : "Chill Miami",
      "tracks" : 60,
      "offline" : false,
      "index" : 29
    },
    {
      "type" : "playlist",
      "name" : "Chill Vibes",
      "tracks" : 147,
      "offline" : false,
      "index" : 30
    },
    {
      "type" : "playlist",
      "name" : "Lawrinson Tunes",
      "tracks" : 78,
      "offline" : false,
      "index" : 31
    },
    {
      "type" : "playlist",
      "name" : "Chill Tracks",
      "tracks" : 344,
      "offline" : false,
      "index" : 32
    },
    {
      "type" : "playlist",
      "name" : "Chilled R&B",
      "tracks" : 52,
      "offline" : false,
      "index" : 33
    },
    {
      "type" : "playlist",
      "name" : "Tame Impala",
      "tracks" : 54,
      "offline" : false,
      "index" : 34
    },
    {
      "type" : "playlist",
      "name" : "Altamont live",
      "tracks" : 13,
      "offline" : false,
      "index" : 35
    },
    {
      "type" : "playlist",
      "name" : "Fleetwood Mac",
      "tracks" : 8,
      "offline" : false,
      "index" : 36
    },
    {
      "type" : "playlist",
      "name" : "Altamont 80's",
      "tracks" : 56,
      "offline" : false,
      "index" : 37
    },
    {
      "type" : "playlist",
      "name" : "Deep Dark Indie",
      "tracks" : 138,
      "offline" : false,
      "index" : 38
    },
    {
      "type" : "playlist",
      "name" : "Peaceful Indie Ambient",
      "tracks" : 95,
      "offline" : false,
      "index" : 39
    },
    {
      "type" : "playlist",
      "name" : "Summer Acoustic",
      "tracks" : 73,
      "offline" : false,
      "index" : 40
    },
    {
      "type" : "playlist",
      "name" : "Indie Acoustic »» Chill",
      "tracks" : 135,
      "offline" : false,
      "index" : 41
    },
    {
      "type" : "playlist",
      "name" : "Liked from Radio",
      "tracks" : 40,
      "offline" : false,
      "index" : 42
    },
    {
      "type" : "playlist",
      "name" : "Altamont Lounge II",
      "tracks" : 145,
      "offline" : false,
      "index" : 43
    },
    {
      "type" : "playlist",
      "name" : "AMBIENT LOUNGE",
      "tracks" : 61,
      "offline" : false,
      "index" : 44
    },
    {
      "type" : "playlist",
      "name" : "Lush + Atmospheric",
      "tracks" : 81,
      "offline" : false,
      "index" : 45
    },
    {
      "type" : "playlist",
      "name" : "New Albums",
      "tracks" : 23,
      "offline" : false,
      "index" : 46
    },
    {
      "type" : "playlist",
      "name" : "Discover Weekly",
      "tracks" : 30,
      "offline" : false,
      "index" : 47
    },
    {
      "type" : "playlist",
      "name" : "Vocal Chillout",
      "tracks" : 243,
      "offline" : false,
      "index" : 48
    },
    {
      "type" : "playlist",
      "name" : "David Gilmour – Rattle That Lock (Deluxe)",
      "tracks" : 14,
      "offline" : false,
      "index" : 49
    },
    {
      "type" : "playlist",
      "name" : "Girls in Their Summer Clothes – Bruce Springsteen",
      "tracks" : 4,
      "offline" : false,
      "index" : 50
    },
    {
      "type" : "playlist",
      "name" : "Altamont Vocal Trance",
      "tracks" : 32,
      "offline" : false,
      "index" : 51
    },
    {
      "type" : "playlist",
      "name" : "Altamont Smooth Jazz",
      "tracks" : 157,
      "offline" : false,
      "index" : 52
    },
    {
      "type" : "playlist",
      "name" : "Altamont Chill",
      "tracks" : 23,
      "offline" : false,
      "index" : 53
    },
    {
      "type" : "playlist",
      "name" : "Altamont Lounge",
      "tracks" : 395,
      "offline" : false,
      "index" : 54
    },
    {
      "type" : "playlist",
      "name" : "Ibiza/Mallorca Lounge",
      "tracks" : 66,
      "offline" : false,
      "index" : 55
    },
    {
      "type" : "playlist",
      "name" : "tyDi Classic Tracks and Remixes",
      "tracks" : 14,
      "offline" : false,
      "index" : 56
    },
    {
      "type" : "playlist",
      "name" : "tyDi",
      "tracks" : 147,
      "offline" : false,
      "index" : 57
    },
    {
      "name" : "Burke",
      "type" : "folder",
      "playlists" : [
        {
          "type" : "playlist",
          "name" : "Burke 74 EDM",
          "tracks" : 30,
          "offline" : false,
          "index" : 59
        },
        {
          "type" : "playlist",
          "name" : "Burke 74 Dance",
          "tracks" : 17,
          "offline" : false,
          "index" : 60
        },
        {
          "type" : "playlist",
          "name" : "Burke 74 50s",
          "tracks" : 61,
          "offline" : false,
          "index" : 61
        },
        {
          "type" : "playlist",
          "name" : "Burke 74 Alt",
          "tracks" : 37,
          "offline" : false,
          "index" : 62
        },
        {
          "type" : "playlist",
          "name" : "Burke 74",
          "tracks" : 173,
          "offline" : false,
          "index" : 63
        }
      ]
    },
    {
      "name" : "iTunes",
      "type" : "folder",
      "playlists" : [
        {
          "name" : "A3 CDs",
          "type" : "folder",
          "playlists" : [
            {
              "type" : "playlist",
              "name" : "A3 - 1 - Moby Live",
              "tracks" : 37,
              "offline" : false,
              "index" : 67
            },
            {
              "type" : "playlist",
              "name" : "A3 - 2 - Kings of Leon",
              "tracks" : 38,
              "offline" : false,
              "index" : 68
            },
            {
              "type" : "playlist",
              "name" : "A3 - 3 - Todd Rundgren",
              "tracks" : 16,
              "offline" : false,
              "index" : 69
            },
            {
              "type" : "playlist",
              "name" : "A3 - 4 - Howie Day Live - 2015",
              "tracks" : 54,
              "offline" : false,
              "index" : 70
            },
            {
              "type" : "playlist",
              "name" : "A3 - 5 - Earth, Wind And Fire: Greatest Hits",
              "tracks" : 17,
              "offline" : false,
              "index" : 71
            }
          ]
        },
        {
          "name" : "Altamont Playlists",
          "type" : "folder",
          "playlists" : [
            {
              "type" : "playlist",
              "name" : "Altamont 80's",
              "tracks" : 180,
              "offline" : false,
              "index" : 74
            },
            {
              "type" : "playlist",
              "name" : "Altamont Chick Singers",
              "tracks" : 175,
              "offline" : false,
              "index" : 75
            },
            {
              "type" : "playlist",
              "name" : "Altamont Classic Rock 1",
              "tracks" : 120,
              "offline" : false,
              "index" : 76
            },
            {
              "type" : "playlist",
              "name" : "Altamont Classical",
              "tracks" : 140,
              "offline" : false,
              "index" : 77
            },
            {
              "type" : "playlist",
              "name" : "Altamont Dead",
              "tracks" : 25,
              "offline" : false,
              "index" : 78
            },
            {
              "type" : "playlist",
              "name" : "Altamont Electronic",
              "tracks" : 126,
              "offline" : false,
              "index" : 79
            },
            {
              "type" : "playlist",
              "name" : "Altamont Lounge",
              "tracks" : 58,
              "offline" : false,
              "index" : 80
            },
            {
              "type" : "playlist",
              "name" : "Altamont New Age",
              "tracks" : 879,
              "offline" : false,
              "index" : 81
            },
            {
              "type" : "playlist",
              "name" : "Altamont Pool Tunes 1",
              "tracks" : 64,
              "offline" : false,
              "index" : 82
            },
            {
              "type" : "playlist",
              "name" : "Altamont Refresh",
              "tracks" : 58,
              "offline" : false,
              "index" : 83
            },
            {
              "type" : "playlist",
              "name" : "Altamont Rock",
              "tracks" : 352,
              "offline" : false,
              "index" : 84
            },
            {
              "type" : "playlist",
              "name" : "Altamont Techno",
              "tracks" : 51,
              "offline" : false,
              "index" : 85
            },
            {
              "type" : "playlist",
              "name" : "Altamont Trance",
              "tracks" : 486,
              "offline" : false,
              "index" : 86
            },
            {
              "type" : "playlist",
              "name" : "Altamont Workout",
              "tracks" : 71,
              "offline" : false,
              "index" : 87
            }
          ]
        },
        {
          "name" : "iTunes Pass",
          "type" : "folder",
          "playlists" : [
            {
              "type" : "playlist",
              "name" : "The Fray Live - iTunes Pass",
              "tracks" : 7,
              "offline" : false,
              "index" : 90
            }
          ]
        },
        {
          "name" : "Playlist Archive",
          "type" : "folder",
          "playlists" : [
            {
              "type" : "playlist",
              "name" : "Xmas 2005",
              "tracks" : 9,
              "offline" : false,
              "index" : 93
            },
            {
              "type" : "playlist",
              "name" : "Xmas 2007",
              "tracks" : 8,
              "offline" : false,
              "index" : 94
            },
            {
              "type" : "playlist",
              "name" : "Xmas 2008",
              "tracks" : 10,
              "offline" : false,
              "index" : 95
            },
            {
              "type" : "playlist",
              "name" : "Xmas 2009",
              "tracks" : 8,
              "offline" : false,
              "index" : 96
            },
            {
              "type" : "playlist",
              "name" : "Xmas 2010",
              "tracks" : 19,
              "offline" : false,
              "index" : 97
            },
            {
              "type" : "playlist",
              "name" : "Xmas 2012",
              "tracks" : 16,
              "offline" : false,
              "index" : 98
            },
            {
              "type" : "playlist",
              "name" : "Xmas 2013",
              "tracks" : 55,
              "offline" : false,
              "index" : 99
            },
            {
              "type" : "playlist",
              "name" : "Xmas 2014",
              "tracks" : 16,
              "offline" : false,
              "index" : 100
            }
          ]
        },
        {
          "type" : "playlist",
          "name" : "Xmas Favorites",
          "tracks" : 26,
          "offline" : false,
          "index" : 102
        },
        {
          "type" : "playlist",
          "name" : "Xmas Songs",
          "tracks" : 145,
          "offline" : false,
          "index" : 103
        },
        {
          "type" : "playlist",
          "name" : "Xmas Tunes",
          "tracks" : 233,
          "offline" : false,
          "index" : 104
        }
      ]
    },
    {
      "type" : "playlist",
      "name" : "2002-04-15 - Corey Union Function Room",
      "tracks" : 21,
      "offline" : false,
      "index" : 106
    },
    {
      "type" : "playlist",
      "name" : "Above & Beyond - We Are All We Need",
      "tracks" : 16,
      "offline" : false,
      "index" : 107
    },
    {
      "type" : "playlist",
      "name" : "Brian Wilson - Live At The Roxy Theatre",
      "tracks" : 14,
      "offline" : false,
      "index" : 108
    },
    {
      "type" : "playlist",
      "name" : "Brit Rock",
      "tracks" : 654,
      "offline" : false,
      "index" : 109
    },
    {
      "type" : "playlist",
      "name" : "Dinner Tunes",
      "tracks" : 29,
      "offline" : false,
      "index" : 110
    },
    {
      "type" : "playlist",
      "name" : "Fall/Winter Chill Out",
      "tracks" : 120,
      "offline" : false,
      "index" : 111
    },
    {
      "type" : "playlist",
      "name" : "Genius: Altamont Chill",
      "tracks" : 65,
      "offline" : false,
      "index" : 112
    },
    {
      "type" : "playlist",
      "name" : "Headphones Tunes",
      "tracks" : 93,
      "offline" : false,
      "index" : 113
    },
    {
      "type" : "playlist",
      "name" : "HeadStreamer Tunes",
      "tracks" : 87,
      "offline" : false,
      "index" : 114
    },
    {
      "type" : "playlist",
      "name" : "Howie",
      "tracks" : 12,
      "offline" : false,
      "index" : 115
    },
    {
      "type" : "playlist",
      "name" : "Howie Day",
      "tracks" : 90,
      "offline" : false,
      "index" : 116
    },
    {
      "type" : "playlist",
      "name" : "Howie Day - 2015-05-15 - Dosey Doe Music Cafe, Conroe TX",
      "tracks" : 17,
      "offline" : false,
      "index" : 117
    },
    {
      "type" : "playlist",
      "name" : "Howie Day - Live At SPACE",
      "tracks" : 16,
      "offline" : false,
      "index" : 118
    },
    {
      "type" : "playlist",
      "name" : "Howie Day - Live At The Berklee Performance Center - 2002-04-28",
      "tracks" : 18,
      "offline" : false,
      "index" : 119
    },
    {
      "type" : "playlist",
      "name" : "Howie Day - Live at Yoshi's 2014-12-17",
      "tracks" : 16,
      "offline" : false,
      "index" : 120
    },
    {
      "type" : "playlist",
      "name" : "Hozier - Hozier",
      "tracks" : 13,
      "offline" : false,
      "index" : 121
    },
    {
      "type" : "playlist",
      "name" : "JoJo Tunes",
      "tracks" : 123,
      "offline" : false,
      "index" : 122
    },
    {
      "type" : "playlist",
      "name" : "Late Night Chill",
      "tracks" : 94,
      "offline" : false,
      "index" : 123
    },
    {
      "type" : "playlist",
      "name" : "Luther Mix",
      "tracks" : 100,
      "offline" : false,
      "index" : 124
    },
    {
      "type" : "playlist",
      "name" : "Noel Gallagher's High Flying Birds",
      "tracks" : 26,
      "offline" : false,
      "index" : 125
    },
    {
      "type" : "playlist",
      "name" : "Piano Tunes",
      "tracks" : 83,
      "offline" : false,
      "index" : 126
    },
    {
      "type" : "playlist",
      "name" : "Private Music",
      "tracks" : 43,
      "offline" : false,
      "index" : 127
    },
    {
      "type" : "playlist",
      "name" : "Rush - Top 10",
      "tracks" : 9,
      "offline" : false,
      "index" : 128
    },
    {
      "type" : "playlist",
      "name" : "Sade Genius",
      "tracks" : 100,
      "offline" : false,
      "index" : 129
    },
    {
      "type" : "playlist",
      "name" : "Springsteen Bootlegs",
      "tracks" : 62,
      "offline" : false,
      "index" : 130
    },
    {
      "type" : "playlist",
      "name" : "The Beatles",
      "tracks" : 67,
      "offline" : false,
      "index" : 131
    },
    {
      "type" : "playlist",
      "name" : "Tycho",
      "tracks" : 32,
      "offline" : false,
      "index" : 132
    },
    {
      "type" : "playlist",
      "name" : "Vocal Trance/Techno",
      "tracks" : 80,
      "offline" : false,
      "index" : 133
    }
  ]
}

**Comment by skikirkwood** [comment]
I fixed this myself over the weekend.  Just got pulled into master with b2a214a commit.

**Comment by apinner** [comment]
Can it be closed then?
