### ISSUE TITLE
[RC2 HotFix] 5 buttons in Queue list not working in Android Phone 

### ISSUE THREAD

**Issue by TeenTin** [volumio/Volumio2#512]
System : Pi3 and HiFiberry DAC Plus Pro

Issue : Android -> Chrome -> Queue list -> 'Random, Repeat, ..., Delete' buttons not working.

However, no problem when open in PC.

**Comment by apinner** [comment]
Confirmed, tested this morning.

**Comment by rhealey-uk** [comment]
Not sure if this needs to have its own Issue but I can confirm I have the same problem occurring on the iPhone 6. The 5 buttons do not function on the Queue List.

System:
[RC2] / Pi A+ / IQAudio PiDAC+

**Comment by volumio** [comment]
This is a UI related issue. Moved to https://github.com/volumio/Volumio2-UI/issues/149
