### ISSUE TITLE
Spotify Plugin doesn't recognize playlist folders

### ISSUE THREAD

**Issue by skikirkwood** [volumio/Volumio2#514]
The Spotify plugin will list folders as playlists when browsing, and clicking on a folder will give a blank screen instead of listing the playlists in the folder.

**Comment by skikirkwood** [comment]
I fixed this, pulled into master with commit b2a214a.  Playlist folders will not get expanded inline, with their playlists showing instead of the folder name in the playlist view.

**Comment by apinner** [comment]
Close?

**Comment by skikirkwood** [comment]
Sorry, didn't see the Close button.  Closing this, yes.
