### ISSUE TITLE
RC2 [HOTFIX] Playlist issues

### ISSUE THREAD

**Issue by SonosKiller** [volumio/Volumio2#526]
Running a Rpi3 a clean install of the RC2 [Hotfix] on a new Sd card using no Dac just the audio jack
and a windows share as Nas

Playlist created from Music Library, Nas, ... don't Play from Playlists , Add to queue don't work either.
Playlist created/saved from  Queue, both Play and Add to queue works fine from Playlists

Random play of the queue don't work when "Consume playlist" is active 

Thanks for the work and dedication you all put in to this software
May God bless you all

**Comment by apinner** [comment]
Sorry I don't quite follow the first part? Playlists don't play in playlists? What can't you add to queue?

Can you clarify what you mean a bit better?

**Comment by xipmix** [comment]
Sounds like #509 to me...

**Comment by SonosKiller** [comment]
Sorry ! "Playlists dialoge"

If I create a playlist from Music Library, Nas, .. dialogue (and also in  search dialoge)
That playlist don't start when I pick them up in the Playlists dialogue using Play and  the playlist don't end up in queue if I use Add to queue

Playlists created/saved in Queue dialouge works fine when I pick them up in Playlists dialoge

Ok ?

Will test to  modify , add to and change them two types of playlists tonight and see what's happen

**Comment by volumio** [comment]
IMHO they miss the /mnt/ in the URI

**Comment by SonosKiller** [comment]
I assume that this also is a easy fix !
"Random play of the queue don't work when "Consume playlist" is active"

"Consume" is this the right word to use ? modify or change seems more correct ! :)

**Comment by xipmix** [comment]
> 
> "Consume" is this the right word to use ? modify or change seems more correct ! :)
> 

I noticed this too and wrestled with the wording.
What the button does is turn on the mode that does
'Remove items in the queue after they have been played'.
but that's a little long for a tool tip.

'Consume queue' is more consistent (its The Playqueue, not a playlist)
but...ugly.

My suggestion: 'Remove played items' or 'Autoremove'.

> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/volumio/Volumio2/issues/526#issuecomment-231082389

--

**Comment by SonosKiller** [comment]
Okey ! Didn't notice that songs disappeared, thought that function was for activate "moving songs in the queue" , then Consume is more than correct

**Comment by apinner** [comment]
Yeah Consume mode means it will consume the queue, so as a song is played it will be consumed and removed from the current track queue.

**Comment by SonosKiller** [comment]
Just a note on the "Consume playlist" function (now when I understand it  :) ) , it removes the top song not the played song !
 Random and Consume together could be a nice feature

**Comment by volumio** [comment]
Fixed
