### ISSUE TITLE
[RC2] Feature Request:  Finer queue control

### ISSUE THREAD

**Issue by nightflightdan** [volumio/Volumio2#529]
1. Would be handy to be able to select multiple entries from the queue and delete them, rather than need to do it one by one or clear the whole lot.
2. When a folder is added to the queue, group all the tracks in that folder and be able to delete that folder from the queue with a single click, with the option to multi select several folders together (as above)
3. Drag and drop reordering of queue order

**Comment by volumio** [comment]
Drag and drop reordering is already there...
For the other 2 it would be too complicated to make, and handle in touch environment...
