### ISSUE TITLE
Party mode

### ISSUE THREAD

**Issue by Gizmoh1683** [volumio/Volumio2#533]
As mentioned in https://volumio.org/forum/party-mode-t4320.html

I would suggest adding a Party Mode to Volumio. If the Party mode is activated all public users are allowed to do certain things:
 - Search the database
 - Add a song to the current Playlist (after current tilte or at the end (configurable))
 - Play/Pause/Next (configurable which actions are available, maybe "next" enabled after a configurable time like 1 minute)
 
There's one admin user who is able to use all functions from volumio.

If a song is added by a public users there could be some verfifications, e.g. a minimum of songs between repeating tiltes in the playlist or that songs can only be added one time to a playlist.

**Comment by volumio** [comment]
That's a really nice idea... But quite hard to implement... We'll review the idea in the future...
