### ISSUE TITLE
RC2-Hotfix not working

### ISSUE THREAD

**Issue by amalic** [volumio/Volumio2#544]
I tried it on a Raspberry2B with Durio I2C-DAC. 

I was able to access it via SSH for a short period of time. When trying to load Volumio2 in my Browser I only got a grey site. The Website title started with "{ {".

I flashed the image with Win32 Disk Imager as I did for Volumio 1.55.

**Comment by apinner** [comment]
Presumably you have tried a reboot?

**Comment by amalic** [comment]
Yes, i believe so.

Today i got a secont SD-card. Will try again.

**Comment by amalic** [comment]
Bought a Raspberry3B today --> RC2 seems to work. Trying to figure out how to play music from my USB flashdrive on Volumio2.
