### ISSUE TITLE
webui - does not remove playlist from display when playlist is deleted

### ISSUE THREAD

**Issue by xipmix** [volumio/Volumio2#545]
Minor usability nit.

I had only one playlist, but it happens the same if there are more items in the list.

To reproduce:
* Go to Browse->Playlists.
* Select 'delete' from the options menu for a playlist.

The UI says playlist deleted, but it is still shown in the UI until I navigate back to Browse->Playlists, it does not appear at that point. 

What I was expecting is when I selected the delete option, the playlist page would refresh and the selected playlist would no longer be displayed.

The log shows the list is actually getting deleted.

    info: CoreCommandRouter::executeOnPlugin: mpd , handleBrowseUri
    info: [1468318466758] Listing playlists
    info: [1468318475995] Deleting playlist test

Version info:

    $ git remote -v; git branch -v; git log -1;
    origin  https://github.com/volumio/Volumio2.git (fetch)
    origin  https://github.com/volumio/Volumio2.git (push)
    * dev c3908e5 Fixed credentials for NFS
    commit c3908e504f7c3d333d1a671db206d031283406fb
    Author: Volumio <info@volumio.org>
    Date:   Thu Jul 7 12:04:10 2016 +0200

        Fixed credentials for NFS

**Comment by volumio** [comment]
This has been solved
