### ISSUE TITLE
Missing volume up/down buttons on mobile interface

### ISSUE THREAD

**Issue by Coolechriz** [volumio/Volumio2#553]
Hello, 
On the mobile interface I miss the volume up and down buttons enormous, the use of the slider will sometime bug making it sound suddenly goes much too hard. Is there a possibility to add these buttons to the interface?
Thanks!

ps, sorry for bad English, i'm Dutch

**Comment by TeenTin** [comment]
Agree.  The volume slider is hard to use.

**Comment by amalic** [comment]
please don't forget to not show any volume controls if volume change is disabled in the settings -> https://github.com/volumio/Volumio2/issues/547

**Comment by heis2201** [comment]
When using the WebUI in Safari on my iphone, the volume slider doesn't even work: Not able to change volume with the slider.

**Comment by Coolechriz** [comment]
@heis2201 on my iPhone whit Google Chrome it is working but hard to use

**Comment by apinner** [comment]
Added here https://github.com/volumio/Volumio2-UI/commit/0c471fd164b413d6346831cfc48d357668f7f18e
