### ISSUE TITLE
Please add replace and play to conextmenu when selecting folder/title

### ISSUE THREAD

**Issue by amalic** [volumio/Volumio2#560]
I'm missing a comfort feature from Volumio2. "Replace and Play" which replaces the current playlist by the selected folder/title and plays the selected title.

Problem description:
I've been playing before "The Top 100 Masterpieces of Classical Music". Now I'm playing "Kruder & Dorfmeister - The K&D Sessions". I have to do a lot of scrolling to select a specific title in the playlist.

**Comment by apinner** [comment]
IIRC just clicking Play from the menu does exactly that.

**Comment by amalic** [comment]
not really. it adds the new song/album to the current playlist.

**Comment by heis2201** [comment]
.... and create a function **"Replace & Play"**. Thanks!

**Comment by apinner** [comment]
Done here https://github.com/volumio/Volumio2/issues/584#issuecomment-235334921
