### ISSUE TITLE
Alarm: new created playlist not showing

### ISSUE THREAD

**Issue by klokslagB** [volumio/Volumio2#563]
Reproduce:
add a song to a **new** playlist using browse music library.
go to settings ==> alarms

New created playlist not showing.
on RC2 hotfix + dev

**Comment by jo-me** [comment]
Same thing happens if you create a new playlist from the "playback" tab and then immediately try to add it again. The newly created playlist does not shop up in the list of existing playlists.
After a page reload it shows up.

**Comment by volumio** [comment]
Yes, it's a bug, we'll fix it

**Comment by jo-me** [comment]
Seems to be fixed in v.2.001

**Comment by klokslagB** [comment]
still can reproduce the orginal bug

**Comment by klokslagB** [comment]
Couldn't reproduce the orginal bug. Guess it is fixed. If someone can confirm this the issue can be closed.
