### ISSUE TITLE
Support for Pandora Radio

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#574]
Hi, 

anyone capable of writing a plugin to integrate Pandora streaming to Volumio?
Thanks

**Comment by skikirkwood** [comment]
This would be challenging, as Pandora only makes their API available to qualified partners:

https://www.quora.com/Do-Spotify-or-Pandora-provide-APIs-to-fetch-user-data-e-g-who-listened-to-what-in-a-given-period-of-time-for-non-commercial-use

There is an unofficial API but apparently Pandora changes their API frequently to break 3rd parties who are not official partners.  They should, like Spotify, open up the API to anyone.

**Comment by heis2201** [comment]
Oh, if that's the case, let's drop the idea until Pandora decides to let more people use their service...
