### ISSUE TITLE
B+ and Hifiberry DAC+

### ISSUE THREAD

**Issue by Xtgskc** [volumio/Volumio2#577]
Raspi 1 B+, Hifiberry DAC+, Volumio RC2 Hotfix 0.928 2016-06-30

'Hifiberry DAC Plus' does not display in 'DAC Model' list on a Pi 1 B+.

![bplusunconfiguredhifiberryplus missing](https://cloud.githubusercontent.com/assets/20600626/17079001/76335d7e-50fb-11e6-8bfb-769a791f4f3b.jpg)

Hifiberry DAC+ can be configuered on a Pi2 with no additional hardware then uSD card swaped to a B+. B+ will now output through Hifiberry. Volumio displays 'Output Device' as 'Hifiberry DAC', 'DAC Model' as 'Hifiberry DAC Plus'. 

![bplushifiberryplus](https://cloud.githubusercontent.com/assets/20600626/17079002/8ad41db8-50fb-11e6-918e-f3bc9dfdbbca.jpg)

If the DAC Model dropdown is selected 'Hifiberry DAC Plus' does not display.

![bplushifiberryplusmissing dropdown](https://cloud.githubusercontent.com/assets/20600626/17079003/925141ec-50fb-11e6-9587-1b718446813c.jpg)

Appologies if this is a duplicate issue.

**Comment by eggerph** [comment]
Hey
I was having the same issue. Seems like Volumio thinks it's a first generation Raspberry Pi and therefore only shows compatible DAC's for this version. I think this should be an easy fix.

For the moment I have an easy workaround. Just choose the Hifiberry dac, shutdown. Edit the config.txt file by inserting the SD to your computer or via ssh. Just ad plus where it says something like overlay=hifiberry-dac. so it would be overlay=hifiberry-dacplus. Worked perfectly in my case, even displays it correctly in the settings now.
