### ISSUE TITLE
Wifi doesn't work on Rpi using RC2 

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#580]
/etc/network/interfaces shows a line

```
allow-hotplug wlan0
iface wlan0 inet manual
```

while in volumio's UI it is set for auto-address. Also, in UI, can't connect to wifi. `ifconfig` doesn't show that network address is received...

**Comment by heis2201** [comment]
Had to change *interfaces* manually to 

```
allow-hotplug wlan0
iface wlan0 inet dhcp

```
in order to establish a wifi connection.

**Comment by kaffeeringe** [comment]
I had the same problem. And the solution also works for me.

**Comment by kaffeeringe** [comment]
The UI still shows a wired connection with 10Mb/s and IP 192.168.8.8 - altought the cable is disconnected and I already rebooted the system.

**Comment by heis2201** [comment]
Same here but I don't bother too much... as long as wifi connection is reliable and stable.

**Comment by volumio** [comment]
As per wi-fi issue, did you had this trouble while trying to connect from UI?

**Comment by heis2201** [comment]
@volumio : Sorry, never answered your above question. Yes, when connected via ethernet, I could access my Volumio but I was not able to establish a wifi connection. Tried it several times. Then I took a look at `interfaces` and `wlan0` would always remain in `manual`. Once I changes that value to `dhcp`, my wifi connection is working just fine.
