### ISSUE TITLE
Appearance settings are not clear/intuitive

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#582]
Appearance settings are not clear/intuitive, at least on my UI (Firefox 47). 
See screenshot [here](http://imgur.com/a/KjDOw).
Additionally, I think, they deserve a "reset" button that loads factory defaults for design.

**Comment by volumio** [comment]
When you saw the page probably, the thumbnails were not generated yet.
Which pi models do you have? 
Could you try to reload the page and see what happens?

**Comment by apinner** [comment]
Your page clearly hasn't loaded properly.

There are only two settings that you can change, I think a reset button is a bit excessive. Especially when the default background is called default.

**Comment by heis2201** [comment]
@volumio : I am on RPI B+. Already tried to reload the page. Nothing changed. 

And yes, I agree with @apinner : When this page is completely loaded, there will be no need for a reset button.

**Comment by heis2201** [comment]
So, what's the solution to fully load the page?

**Comment by volumio** [comment]
It should load automatically everytime, I'm investigating the issue which seems related to RPI B+ maybe being too slow to achieve this in a timely manner
