### ISSUE TITLE
Missing Library view

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#583]
Missing Library view:

I have two USB and one network connection feeding my volumio player with music. Now, when I would like to play a specific album, I need to know where it's stored, (which can be hard to remember).

Is there a way to enable a Library view (like we had it in Volumio 1.55) that just lists all audio files? Best would be to set filters or sort it by some characteristics contained in meta information (Artist, Album, Genre, etc.).

**Comment by volumio** [comment]
We're still working on it. But you can use the search function

**Comment by heis2201** [comment]
Thank you very much for all the effort put into Volumio2!!!
