### ISSUE TITLE
Seeking to input volume by typing in a number

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#585]
In Volumio 1.55, I could enter the desired output volume by clicking on the current value and enter the new value by typing a number with my keyboard.

Unfortunately, that is not possible anymore. Would like to see that functionality again.

**Comment by apinner** [comment]
You have the ability to change the volume with a click on the dial, with the mouse scroll wheel, or using the up and down buttons for which you can set your own custom increments. On mobile we also have a slider.

I don't think we really need another way to change the volume.
