### ISSUE TITLE
Support for USB Wifi Adapter MT7601U (Ralink Technology, Corp.)

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#588]
Hi,
I bought a USB Wifi adapter with external antenna (Ralink Technology, Corp. **MT7601U** Wireless Adapter) to make volumio's wifi connectiion more stable.

Surprisingly, this chipset is not supported out-of-the-box. Has anyone any idea how to add the corresponding kernel module (works perfectly fine on Fedora with kernel 4.5 and 4.6).

(While troubleshooting, why is `lsusb` and `lspci` not available on Volumio's debian/raspbian?)

**Comment by volumio** [comment]
try with sudo , probably we miss firmwares. Do you know if they are available on raspbian?

**Comment by balbuze** [comment]
Yes I think we really miss those commands. Someone on the forum have a similar problem and without lspci or lsusb it'not easy to help

**Comment by volumio** [comment]
Right, fixed with this:
https://github.com/volumio/Build/commit/b59d0c24847952fc2c60c5e716429d365a15aeb5

**Comment by heis2201** [comment]
Don't know if firmware available on raspbian but I can research it later today.

**Comment by volumio** [comment]
thanks

**Comment by pgpGithub** [comment]
My MT7601U works out of box with raspian but not with volumio 2.246

**Comment by macmpi** [comment]
There's a pending PR fixing it: https://github.com/volumio/Build/pull/221

**Comment by macmpi** [comment]
I guess this one can be closed now

**Comment by heis2201** [comment]
Yes, it could be closed, PR has been merged: https://github.com/volumio/Build/pull/221

[Duplicated issue](https://github.com/volumio/Volumio2/issues/1080) has already been closed. Thank you very much for fixing this issue!
