### ISSUE TITLE
catalan translation

### ISSUE THREAD

**Issue by nosferatujr** [volumio/Volumio2#589]
Hi Guys, i produced this translation. Please consider to add. Thanks
https://gist.github.com/nosferatujr/00e5565f9451e417f6afc9d42f831f62

**Comment by apinner** [comment]
Thank you @nosferatujr 

I have added those translations for you. Just as a note, if you edit in future we use two spaces as a tab. If you use one of the common text editors then there is a editorconfig here https://github.com/volumio/Volumio2-UI/blob/master/.editorconfig that should configure that for you. For the most part it was fine, just a few random tabs.

**Comment by volumio** [comment]
Molt bè!!! Moltes gràcies 

fins aviat 

mi

**Comment by nosferatujr** [comment]
Un plaer, 
apinner  , Sorry for the mistake, I will take in consideration the tabs on the future
