### ISSUE TITLE
Radio stream failed to decode

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#594]
I was trying to listen to my favorite [KCRW-Eclectic 24 ](http://www.kcrw.com/music/shows/eclectic24/#)radio but volumio said it would not be able to decode the stream.
What's the problem here?

Volumio suggests that it is playing... time is counting, but there is really no output...

Screenshots are [here](http://imgur.com/a/ULkeQ), and [here](http://imgur.com/a/Bsis9)

![img_3532](https://cloud.githubusercontent.com/assets/17801574/17180205/a9bf5d82-53e9-11e6-9639-5c7b5ab8ab93.PNG)

**Comment by shoredrive** [comment]
I am also having trouble using a .m3u address to stream webradio. I get the audio tone on boot, and airplay works great, however I can not stream Radio St. Barth http://www.vtuner.com/vtunerweb/mms/m3u18177.m3u  It says playing and even shows the different song data, however no audio except for some light static that disappear when i press pause.

**Comment by buzink** [comment]
Did you try using the url in the m3u-file? As a workaround, you can create a playlist file with that url in the folder "/data/playlist" following the following format:

[ { "service": "webradio", "uri": "http://2stream.dyndns.org:8000/rsb", "title": "Name of station", "albumart": "/albumart?path=%2Fplaylist%2Fradio1.jpg" } ]

You can add playlists through SSH each time or through your file explorer after adding "/data/playlist" once as a network share in "/etc/samba/smb.conf"
