### ISSUE TITLE
Would love to remove the mosaic in Playback View

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#595]
Hi,

I know this is probably a sensitive issue and opinions differ a lot...

What's a good way to remove the *disc cover mosaic* in the background of the *Playback View*?
In my personal opinion it is distracting - I love simplistic, clear layouts. The many little pictures draw a lot of attention, shifting focus. 

![img_3533](https://cloud.githubusercontent.com/assets/17801574/17180814/b157d70c-53eb-11e6-886e-a7b164209481.PNG)

Maybe this could be an option in Appearance Settings? 
Thanks!

**Comment by balbuze** [comment]
you can rename default cover /volumio/app/plugins/miscellanea/albumart/default.png (default.png.backup) or remplace it by the image you want...

**Comment by heis2201** [comment]
Thanks!
