### ISSUE TITLE
Player control overlaps title of currently playing song

### ISSUE THREAD

**Issue by paviro** [volumio/Volumio2#601]
![control overlap](https://cloud.githubusercontent.com/assets/992826/17246600/840c12d8-558d-11e6-8f1a-272f4a90ecb1.png)

Latest Volumio 2 Version.

**Comment by apinner** [comment]
On what resolution? It should have switched to the mobile UI by that point.

**Comment by paviro** [comment]
962px wide

**Comment by paviro** [comment]
Using a radio stream. Titles sometimes get a bit longer switching happens long after that at about 770 pixels wide.

**Comment by apinner** [comment]
What device is that?

**Comment by paviro** [comment]
MacBook Pro 15"

**Comment by apinner** [comment]
Haha, why are you running it at that resolution?

We can tweak it so it hides at lower resolutions, but it wont be a priority issue.

**Comment by paviro** [comment]
Why should I not? Dont want a fullscreen chrome and I think it should definitely work at that resolution! 
![sdfkdfsljglsdfihjgdf](https://cloud.githubusercontent.com/assets/992826/17246824/db36a6bc-558e-11e6-8582-22d9893cf167.png)

**Comment by apinner** [comment]
I didn't say you shouldn't, It's just an unusual resolution. 

Obviously this could be an issue at any resolution if the title is long enough. As i said, will think about a solution but its not going to be very high priority at the moment as it doesn't effect functionality.

**Comment by paviro** [comment]
Alright perfect! :)
