### ISSUE TITLE
Volumio 2 and WiFi...needs some careful attention

### ISSUE THREAD

**Issue by chsims1** [volumio/Volumio2#604]
Volumio needs to urgently address how it deals with wireless connections.  The changes upstream with Raspbian mean that it doesn't behave in the standard Debian way (since about March 2015). Static IP addresses do not work as implemented by Volumio #517, and there is a recent post on the forums about the aggressive control of scripts detecting disconnections and implementing the hostapd AP [https://volumio.org/forum/disable-hostapd-automatic-hotspot-creation-t4400.html](url). 

As far as static IP addresses go, then the problem can be rectified by  replacing the isc-dhcp-client package with the dhcpcd5 package (see #517).

**Comment by apinner** [comment]
Are you just repeating what is in your other issue?

We are aware of the WiFi issue, I don't think we really another issue do we as the other one is still open?

Feel free to reopen if necessary.
