### ISSUE TITLE
Playing Queue issues (Random and Consume functions) Version 0.976

### ISSUE THREAD

**Issue by SonosKiller** [volumio/Volumio2#605]
Active Random is not flawless:
    plays the same song twice from time to time

Active Consume: 
    Removes the first song in the list not the played song

Active Random and Active Consume: 
    Random don't works when consume is active , plays the list in straight order 
    Consume removes the first song in the list not the played

**Comment by apinner** [comment]
Thanks for reporting.

**Comment by SonosKiller** [comment]
Old issue ! fixed in current version 2.031
