### ISSUE TITLE
LIBRARY IMPORT ERROR ON 0.976

### ISSUE THREAD

**Issue by ruudvddries** [volumio/Volumio2#613]
Hi all,

This morning I upgraded volumio From v1.55 to v0.976 (the latest version anyways). I Mount all NAS drives I was using before and updated the library whill listining to a radio stream. After some time, playback stopped, and my library was empty. During the library scan the number of tracks was increasing steadily. 

I have tried setting "ro,noatime,sec=ntlmv2". The musicfile are located on a synology DS414 running the latest DSM 6.0 release. A log file can be found here; https://www.dropbox.com/s/c072dny78yo66qh/volumio.log?dl=0

And onder v1.55 the library was always full. What should/can I do to resolve this?

Regards,

Ruud

**Comment by gkkpch** [comment]
are you running wireless or on an eth0 connection?

Gé

**Comment by ruudvddries** [comment]
Wired! I Like stable network connections....

Ruud

**Comment by yanyingjie007** [comment]
same here, it show my NAS was 16M, and no list of songs artists after reboot, i connected to WIFI and cable at the same time(different LANs).
