### ISSUE TITLE
MPD Error with .aif Files

### ISSUE THREAD

**Issue by CaptainMetal** [volumio/Volumio2#614]
There is an error in your compiled/used MPD Version with .aif Files. 
This error was already fixed in the newest Version on musicpd.org . 
I corrected this error with them (i already send you an email about this error on 12.04.2015).

Is it possible you are using a newer, correct Version in the Volumio2 Image ?
That would be great !

Thank you !

**Comment by apinner** [comment]
We did update mpd to the latest version, but the compile was a bit buggy during testing.

mpd will be updated to the latest version in the future.

**Comment by CaptainMetal** [comment]
This are good news. It was fixed in MPD 0.19.13
I was not able to compile it in the Volumio 0.976 environment, may be my configure parameters are wrong or something is wrong with the apt-get install libs i installed.

I attached a free testfile for your use to reproduce this error.


[11 Hahn.zip](https://github.com/volumio/Volumio2/files/394249/11.Hahn.zip)

kind regards,

**Comment by CaptainMetal** [comment]
here is a more explanation of the error: in the mpd.log you will see “id3:failed to read riff chunk” error for some (not all) .aif Files from generated by iTunes, and the result is, that these soundfiles does not show up in the library and are not playable.

resolution:
before compiling mpd, modify the file ./src/tag/Aiff.cxx
there is a bug with the line “++size” where the chunk length is rounded up to the next value by 1 when odd. 
This causes the read command to fail, and triggering that error (for example: trying to read 1000 bytes, when there are only 999 left isn’t a good idea, isn’t it ?).
This if-construction has to be removed completely.
