### ISSUE TITLE
Selecting Hifiberry only works after manually setting Output Device

### ISSUE THREAD

**Issue by dragotin** [volumio/Volumio2#615]
When configuring my Raspberry based volumio device to use Hifiberry AMP with volumio version 0.976 it did not work after selecting _DAC Model_ to _Hifiberry Amp_ and switching on _I2S DAC_ on. 

After rebooting, it did not play. To make it work the _Output Device_ had to be set to _Hifiberry DAC_ manually.

I think the _Output Device_ should be set automatically if the user selects to use the Hifiberry Amp.

**Comment by fmslottje** [comment]
I have the same problem on 0.976. I have to set the output at every reboot

**Comment by Coolechriz** [comment]
For me the same problem

**Comment by iso400** [comment]
I found a work around. I think this only occurs when de Hifiberry is detected automatically. Re-select both _output device_ and _DAC Model_ manually and _Save_. After this the settings persist after a reboot.

**Comment by kaffeeringe** [comment]
Same problem with Hifiberry DAC Plus - after reboot "Audio Jack" is selected. I have to change that to have Sound.

**Comment by volumio** [comment]
Which PI model do youhave ?

**Comment by Coolechriz** [comment]
For me is it à raspberry pi3
With the dame problem

**Comment by messismore** [comment]
Also happens on a Zero with with a Hifiberry Amp.

**Comment by dragotin** [comment]
I experienced that on a Raspi 2, not sure which Model atm

**Comment by volumio** [comment]
How did you guys reboot? By removing power or hitting reboot on the UI?

**Comment by Coolechriz** [comment]
Reboot or shutdown from the interface. Direct removing power is not so good for hard- and software.

**Comment by nicosea** [comment]
I have same the problem with PI3 and Pi-dac+ IQaudIO.

**Comment by nicosea** [comment]
I tried to do what iso400 suggested, I re-select both output device and DAC Model manually and Save. After this the settings persist after a reboot, but no sound, I need to reselect IQaudIO DAC anyhow to be able to listen to music.

Is there a way to disable atutomatic Sound Card detection? So I can set PI-DAC+ manually once and avoid this problem on next reboots.

**Comment by volumio** [comment]
It's on top of my priority list to fix.

**Comment by michaelecker** [comment]
Thanks Michelangelo for taking care of this! 

 I have the same issue with a Pi1 B and Hifiberry DIGI

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/Build/commit/06a21f308ffdfb4feb2a53e70eb94acd007ab39d

Basically the new kernel was loading the i2s module before the integrated pi audio. If you don't want for a new release to come out, just add 

snd_bcm2835

to /etc/modules


Also, please someone add this information to relevant forum threads, so other people in need will benefit from the solution...

**Comment by nicosea** [comment]
It's working for me! Thanks!

**Comment by robvangeloven** [comment]
I don't know if it's been fixed in a new build. But for me in 0.979 I still have this issue. Using a hifiberry digi+ and raspberry pi 2.

On reboot it seems ok (from software). Cold boot is a 50/50 which gets selected, jack or digi
