### ISSUE TITLE
/usr/local/bin/shairport-sync: No such file or directory

### ISSUE THREAD

**Issue by spaceSub** [volumio/Volumio2#616]
I just downloaded the latest and greatest volumio version for x86.
Some time ago you had a checkbox to enable airplay, I could not find that in this version. Since I can't find the volumio airplay device I logged in via ssh and the systemd unit file was deactivated, stopped and the referenced /usr/local/bin/shairport-sync does not exist.

**Comment by gkkpch** [comment]
Correct, x86 is wip, not everything is finished yet. A couple of days ago shairpoint-sync was accepted in Debian jessie backports, I will check it today.

**Comment by gkkpch** [comment]
yes, there was a .deb package we can use, testing it...

**Comment by volumio** [comment]
Fixed
