### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by jakubro** [volumio/Volumio2#62]
While starting volumio via `node index.js`, it dies on missing dependency.

In f39237c there was added this line in [http/restapi.js](/volumio/Volumio2/http/restapi.js)
```
var ifconfig = require('wireless-tools/ifconfig');
```
however `wireless-tools` is missing in `package.json`.

**Comment by volumio** [comment]
Fixed in https://github.com/volumio/Volumio2/commit/ca2246e580665bb1c91be13873ebb2a7747f2854
