### ISSUE TITLE
[0.976] Umlaute are not displayed correctly

### ISSUE THREAD

**Issue by Tihmann** [volumio/Volumio2#621]
When displaying titles with german umlaute like äöü (ae,oe,ue) they are not displayed correctly in the webbrowser

**Comment by gkkpch** [comment]
where are your files located and how do you access them? Via cifs, nfs or on a usb disk/card/stick?
We saw this issue ages ago but I thought that was solved.

**Comment by Tihmann** [comment]
When playing webradio..in the titles and descriptions

**Comment by apinner** [comment]
Are you referring to this issue @gkkpch https://github.com/volumio/Volumio2/issues/285

Its an encoding issue IIRC, the problem is with the radio station i think.

**Comment by gkkpch** [comment]
Yes, that was the one...
