### ISSUE TITLE
[0.976] Fourth webradio in list 

### ISSUE THREAD

**Issue by Tihmann** [volumio/Volumio2#622]
When adding four webradios, you are not able to see the complete menu the upper bit is truncated
![bildschirmfoto vom 2016-08-01 22-04-47](https://cloud.githubusercontent.com/assets/8845214/17307179/0c709812-5834-11e6-85fb-1560bf50ac59.png)

Tested on Firefox on Linux desktop, Linux Chromium, Linux Chrome and Firefox Android version, all recent versions

**Comment by apinner** [comment]
Confirmed, looks like an overflow issue. 

Will look at a fix.

**Comment by SonosKiller** [comment]
Almost the same effect on the fourth item in a Playlist,in a Spotify Playlist, Favorites, and  Album list (missing or a half play button)

**Comment by bst27** [comment]
To add some additional info about this issue: 

I can confirm a similiar behaviour in Google Chrome and Safari on an iPhone 5S with Volumio 2.001. The first items menu is created correctly (image 1) but the menu of the second item is truncated (image 2).

![2016-10-31 09 22 22](https://cloud.githubusercontent.com/assets/6805736/19848180/11237cda-9f4c-11e6-8a84-7d72979e984b.png)
![2016-10-31 08 43 40](https://cloud.githubusercontent.com/assets/6805736/19848179/11237668-9f4c-11e6-9bb0-c38e64bb3c1d.png)
