### ISSUE TITLE
[0.976] UI strings missing after update

### ISSUE THREAD

**Issue by SuperBonny** [volumio/Volumio2#625]
After the last update, most webUI strings are missing. Here's an example image to explain the problem ![example](https://cloud.githubusercontent.com/assets/12095774/17332532/5ff8ad6c-58cf-11e6-83a3-7dc2256e736d.png)

**Comment by apinner** [comment]
Remove the file "/data/configuration/miscellanea/apparence/config.json" and restart

**Comment by SuperBonny** [comment]
That solved the issue! Many thanks!
