### ISSUE TITLE
Album and Artist in Search Results v0.976

### ISSUE THREAD

**Issue by howarthcd** [volumio/Volumio2#628]
I've found that when searching the music library then a maximum of only one Album result and one Artist is returned in the search results regardless of how many matches there actually are in the music library.

For example, searching for 'David' returns **only** 'David Bowie' under artists, ignoring any other artists that have the word 'David' in their name.

Similar behaviour is seen for Albums that are returned.

**Comment by ericct** [comment]
I have the same problem with v0.979.

For instance, a search for "beethoven" in my collection (a large number of hits!), is leading to 1 result in artist (btw, I'm sorting out the classical music tagging difficulty by having "composer // perfomer" as ARTIST tag) and 1 album - not from the same artist, as you can see on the screenshot below:

![capture du 2016-10-03 23-02-30](https://cloud.githubusercontent.com/assets/22603003/19053973/9ad6a28a-89bd-11e6-9f91-dda6265519d1.png)
