### ISSUE TITLE
VOLUMIO v.0.976 x86 don't work on AMD platform ?

### ISSUE THREAD

**Issue by Solaar74** [volumio/Volumio2#629]
VOLUMIO don't boot on Zotac Fusion E-350 motherboard. The blinking cursor. No access network.
[https://volumio.org/forum/volumio-976-x86-don-work-amd-platform-t4448.html](url)

**Comment by balbuze** [comment]
I tested it on a hp pavillon dm1 with a amd e350 and it works, but hotspot not working yet. Wifi works after configuration.

**Comment by Solaar74** [comment]
Where is the problem?

**Comment by balbuze** [comment]
The hostapd problem seems to come from a missing line in config file for the build. It's beeing corrected and will be tested. Gkkpch is working on it

**Comment by Solaar74** [comment]
Where is the problem?

**Comment by Solaar74** [comment]
OK. Will wait. I wonder how the system works on the PC.)

**Comment by gkkpch** [comment]
i'm already working on this. similar to @balbuze medion problem. @Solaar74 can download a special version as per PM. I think I know where it stops, but have no clue why. 
hostapd is a step further, visible and connectable. Will be in the next release...

**Comment by gkkpch** [comment]
@Solaar74 you have a PM

**Comment by gkkpch** [comment]
i did find an issue and resolved it with the help of solaar74. Unfortunately, it left us with the next one. After successfully starting volumio 2 on a device that did not work before, there is an issue with reboot. Trying to find out what actually happens, I don't see any relation to the initial issue yet.
