### ISSUE TITLE
Spotify thumbnails missing

### ISSUE THREAD

**Issue by 5AMsan** [volumio/Volumio2#633]
All Spotify thumbnails request lead to this 404 on my fresh Volumio install: 
http://192.168.1.12https//i.scdn.co/image/03f087866bd1c715f616cde11c7071632bd5007e

[volumio.txt](https://github.com/volumio/Volumio2/files/409756/volumio.txt)

**Comment by skikirkwood** [comment]
That's odd, I looked at the log file and the URL's are valid.  You are missing a ":" after the above https in the above.  Where did the URL come from in your message?

Can you include a screenshot of what you are seeing?
