### ISSUE TITLE
Display issue with BBC stations

### ISSUE THREAD

**Issue by skikirkwood** [volumio/Volumio2#635]
The only URL I could get to work for BBC Radio stations was the "Worldwide stream URL (HTTP progressive, 128 Kbps MP3)" listings from BBC Radio Wikipedia entries.  When I plug these URLs into Volumio the play fine but the (very long) URL is displayed in the UI as the song title and blows the display out as seen below.
![bbc4](https://cloud.githubusercontent.com/assets/1205597/17600160/1b42a3be-5fb7-11e6-850b-1fd7f03b84a3.png)

**Comment by apinner** [comment]
Yep i have seen the same.

I'm hoping that when mpd is updated which will also enable HLS stream playback it will fix this issue.
