### ISSUE TITLE
npm install error on cookie-parser

### ISSUE THREAD

**Issue by EMCP** [volumio/Volumio2#64]
I ran `npm install` as non-sudo user.  Seems `cookie-parser` failed to install

I know you don't run the NPM, I'm filing a bug there.. but just giving a heads up.

**Comment by EMCP** [comment]
after trying to run it anyway.. looks like express didn't install.

**Comment by volumio** [comment]
did you give proper permission to volumio folder? In which system are you installing?

**Comment by EMCP** [comment]
this is a Raspberry Pi running Debian aka "Raspbian" ,

I will look again at the instructions again, I just created folders under my user's home dir

**Comment by volumio** [comment]
UI works on Volumio distro, since it requires lot of dependencies

**Comment by EMCP** [comment]
I've re-read and followed the instructions.. same problem is occurring however.

**Comment by volumio** [comment]
Are you using raspbian or Volumio2 distro?

**Comment by EMCP** [comment]
`Raspbian` , I have a need to do that due to some customizations on the wifi routing

**Comment by volumio** [comment]
So, can't help. The whole system is made on purpose.
Also, this is a raspbian problem (probably node's version) or lack of compilers

**Comment by EMCP** [comment]
may I ask, what OS is this distro based on? Debian?

**Comment by volumio** [comment]
Yes, debian. Built with multistrap
