### ISSUE TITLE
RFE: Add "Reset" function to UI

### ISSUE THREAD

**Issue by skikirkwood** [volumio/Volumio2#640]
It's possible to get Volumio in strange states that only rebooting will fix.  A nice alternative would be to have a "Reset" button on the System Settings page that would delete the queue, kill the node process, kill the mpd process and then when these automatically restart many locked up situations would be fixed without a reboot.  They start up real fast too.

**Comment by WalterBorgstein** [comment]
I agree. Being a novice user I sometime feel restarting is the only option. But maybe I'm just not familiar enough yet with Volumio. Love to participate though.

**Comment by heis2201** [comment]
as far as I remember, there is a "reset to factory defaults" button under settings. That should do it.

**Comment by skikirkwood** [comment]
I believe that would be too much.  I want my MPD database intact, WiFi settings, MyWebRadio favorites, installed plugins, etc.  So I only want to get a fresh start without changing persistent data.

**Comment by volumio** [comment]
Just reload the page
