### ISSUE TITLE
Disk Image Size - 2.8Gb really needed?

### ISSUE THREAD

**Issue by rolanddb** [volumio/Volumio2#650]
Hi,
I was just in the process of upgrading to Volumio 2.0, but got stuck because the latest image does not fit on my 2GB SD card. The image, unpacked, is 2.8GB.

Before I go out and buy a new SD card, may I ask whether this is really necessary? Can the image somehow be shrunk? I cannot imagine that the app itself is really that big..

**Comment by volumio** [comment]
No the app is barely 300 megs. We need all those space for the updates. We need at least 1,5 GB of space avaiable for a safe update procedure...
