### ISSUE TITLE
Albumart UI bug with Multiroom

### ISSUE THREAD

**Issue by skikirkwood** [volumio/Volumio2#651]
The Multiroom Devices UI section is putting my Pi's IP address in front of the URL for Spotify albumart on the Playback screen:

    <img ng-    src="http://10.0.1.86https://i.scdn.co/image/761046e21077fa23a6c911d7b4a6c83b73bcec44"     src="http://10.0.1.86https://i.scdn.co/image/761046e21077fa23a6c911d7b4a6c83b73bcec44">

![volumio multiroom](https://cloud.githubusercontent.com/assets/1205597/17716426/8331fe02-63bd-11e6-9756-43676ab90c41.png)

**Comment by balbuze** [comment]
yes I've got the same. And other thing, from a device I can't access an other one, I click on the screen is refreshed, but it stay on the same device. On the third device it's ok...
![multiroom](https://cloud.githubusercontent.com/assets/12850139/17838616/d6492012-67d1-11e6-958b-4185bcdd1a68.png)

**Comment by volumio** [comment]
This is a UI bug, could you please move it there?
