### ISSUE TITLE
Issues with Alarm Clock and with 'Add to playlist'

### ISSUE THREAD

**Issue by kiwiASRALL** [volumio/Volumio2#654]
Hi all,

I reported an issue with function 'Alarm' and with 'Playlist'.

**Alarm:**
Add alarm, for example '08:00' and playlist 'test'.  All hours, music is playing (at [...] 07:00, 08:00, 09:00 [...]).  Only solution is delete alarm and not to use it.

**Playlist:**
Move to your local library, for me:
_Music Libray -> NAS -> Music_ 
On the menu button (who you can choose, Play/Add to queue/...) of an directory, choose "Add to playlist' and select a playlist, for me 'test'. 
Go to the playlist, it is empty. The solution is to select 'Add to queue' and in the queue 'Save queue as a playlist'. 

I use the latest release (0.928) on a RPI3. 

Thank you

**Comment by nosferatujr** [comment]
Just to say that still on the new version released today. 0.979

**Comment by fanciulli** [comment]
Working on it

**Comment by fanciulli** [comment]
Patch missed fixing Add to queue
