### ISSUE TITLE
User interface labels are shown in stead of button text

### ISSUE THREAD

**Issue by WalterBorgstein** [volumio/Volumio2#656]
<img width="1242" alt="screen shot 2016-08-20 at 12 35 11" src="https://cloud.githubusercontent.com/assets/15366175/17830671/b569e868-66d2-11e6-9378-f62588a3ea64.png">

Running on RPi3.
version: 0.978

possible root cause:
adding the NFS share to synology.
On a second try (fresh image, changed output to DAC, added NFS share) it did not happen :( So maybe unrelated.

**Comment by volumio** [comment]
Please try to reload the page. Also, did you change the default language?

**Comment by WalterBorgstein** [comment]
I did try reload, also did factory reset. No Luck.
Did not touch the language setting. I have had this happen also on the previous version. I assumed it was related to adding a NFS share (which is no working for me :( ), but I didn't manage to recreate the bug. Will post updates when it happens again.

I seem unable to find substantial logging on the image. the /var/log dir is rather empty. So I am unable to provide more details. Happy to help or provide evidence in any way.

**Comment by volumio** [comment]
Which browser do you use? If you use chrome, please go to the inspector and then select console, see if you have some error there. 
The logs are stored in the journal. To see what goes on do:

sudo journalctl -f

**Comment by balbuze** [comment]
It seems that this issue is due to a problem in /data/configuration/miscellanea/appearance/config.json
If you remove this file, it rework. But I agree it doesn’t tell why it occurs.

**Comment by WalterBorgstein** [comment]
@volumio currently I'm using safari. Will give Chrome a run if the error re occurs.

**Comment by WalterBorgstein** [comment]
@volumio The error game back after I removed a background using the GUI.
The following error is shown in the console.

<img width="577" alt="screen shot 2016-08-20 at 16 29 00" src="https://cloud.githubusercontent.com/assets/15366175/17831783/38d2a35a-66f3-11e6-8700-0a21b1b355df.png">

**Comment by WalterBorgstein** [comment]
I found some error in the journal files.

```

> Aug 20 14:17:41 volumio volumio[595]: info: CoreCommandRouter::executeOnPlugin: appearance , getBackgrounds
Aug 20 14:17:41 volumio volumio[595]: info: CoreCommandRouter::executeOnPlugin: appearance , getUiSettings
Aug 20 14:17:47 volumio volumio[595]: info: CoreCommandRouter::executeOnPlugin: appearance , deleteBackgrounds
Aug 20 14:17:47 volumio volumio[595]: /volumio/app/plugins/miscellanea/appearance/index.js:359
Aug 20 14:17:47 volumio volumio[595]: self.commandRouter.pushToastMessage('success', self.getI18NString('appearance_title'),
Aug 20 14:17:47 volumio volumio[595]: ^
Aug 20 14:17:47 volumio volumio[595]: TypeError: self.getI18NString is not a function
Aug 20 14:17:47 volumio volumio[595]: at /volumio/app/plugins/miscellanea/appearance/index.js:359:77
Aug 20 14:17:47 volumio volumio[595]: at FSReqWrap.oncomplete (fs.js:123:15)
```
```

**Comment by WalterBorgstein** [comment]
The tip from @balbuze is working. After getting the label error, renaming the  /data/configuration/miscellanea/appearance/config.json file seems to work.

I made a differences overview so someone can determine what is misinterpreted. 

<img width="1280" alt="screen shot 2016-08-20 at 16 53 29" src="https://cloud.githubusercontent.com/assets/15366175/17831898/a8256186-66f6-11e6-9f30-8f287936d769.png">

**Comment by volumio** [comment]
Thanks, that was a bug, fixed here:
https://github.com/volumio/Volumio2/commit/913bfc0d191a11b9aef76c6ae8138df3bf6c4a87

I don't know if that related to the other one..

**Comment by volumio** [comment]
what was the one working? the first or second?

**Comment by WalterBorgstein** [comment]
_old was the failing one.

**Comment by volumio** [comment]
Maybe I found it, changing to color breaks the thing

**Comment by WalterBorgstein** [comment]
When selecting the dark background color it seems to break the config file.

**Comment by WalterBorgstein** [comment]
Great minds think alike

**Comment by volumio** [comment]
we're in the right direction. great!

**Comment by volumio** [comment]
wahooo you've spotted and solved two bugs in a row... great work!

**Comment by WalterBorgstein** [comment]
Thanks. Not sure if i fixed anything, but I like contributing by testing!

**Comment by volumio** [comment]
Well it was a three men works... You spot it, balbuze suggests it, I do the dirty work
https://github.com/volumio/Volumio2-UI/commit/205fedce92852b1556aca6c310d9a3273cda2dee

**Comment by volumio** [comment]
Can you try now to see if everything works as supposed?

**Comment by WalterBorgstein** [comment]
How? ;)

**Comment by volumio** [comment]
rm -rf /volumio/http/www/
git clone --depth 1 -b dist --single-branch https://github.com/volumio/Volumio2-UI.git build/$BUILD/root/volumio/http/www

**Comment by WalterBorgstein** [comment]
Ok will give it a try ;). Need to reboot. I'm in a error state cycle it seems. I think these commands will fix that as well.

**Comment by WalterBorgstein** [comment]
is it possible to overwrite the entire Volumio install this way? I crippled it.

**Comment by volumio** [comment]
Nothing works at all? If it does, you can do a factory reset... If not it will take longer to fix it than to reflash it..

**Comment by WalterBorgstein** [comment]
I think something broke in the Spotify plugin. I kept seeing Volumio restarting in the Journal. I could ssh in to the RP3, but the web interface would not come back. I'm lacking the in depth skills of Volumio to fix or reset things. So I did a refresh ;). Will plug it in next and kick off your commands.

**Comment by volumio** [comment]
great , you probably changed language. Which is the next bug I'm going to tackle...

**Comment by WalterBorgstein** [comment]
Not that I know ;)

**Comment by WalterBorgstein** [comment]
1) Changing background colours (all) is working.
2) changing background image (all) is working

**Comment by volumio** [comment]
Point n3 was fixed in the BE, which you don't have. 
Thanks, you helped me fix something I didn't have a clue about.  I'll prepare a new image now, and if that's ok release  it tomorrow

**Comment by WalterBorgstein** [comment]
Great! I will continue to harass the interface until it brakes and than provide an issue. For now this day was lot's of fun! But I'm getting hungry. Talk to you later! Thanks for all your effort in creating and updating Volumio! Really like it.

**Comment by volumio** [comment]
I released it as an update...
