### ISSUE TITLE
NAS path difference between CIFS and NFS

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#659]
I made some tests and mount my NAS using CIFS and NFS
It appears that for CIFS mount the PATH musn't start with / but for NFS it must start with /
It's a bit confusing.
![nasmount](https://cloud.githubusercontent.com/assets/12850139/17831703/9982a16c-66f0-11e6-8cfc-12b69ca687a3.png)

**Comment by WalterBorgstein** [comment]
I'm using NFS and the path doesn't need the /.
What happens without the /?



<img width="794" alt="screen shot 2016-08-20 at 16 24 34" src="https://cloud.githubusercontent.com/assets/15366175/17831770/9dd65f68-66f2-11e6-95fa-6e7069ccc871.png">

**Comment by balbuze** [comment]
Humm... maybe it is to the way my NAS shares folder... If I omit the / it does nothing, and appears as not mounted.

I see you still have button bugs...

**Comment by WalterBorgstein** [comment]
Yeah they came back. Added a screenshot of Chrome Console for dev skilled people. ;)

**Comment by WalterBorgstein** [comment]
What NAS do you have? Maybe you can add some to the documentation draft I made concerning Synology Shares [https://github.com/volumio/Volumio2/issues/641#issuecomment-241202422](url)

**Comment by balbuze** [comment]
have you noticed a particular action for that ? Have you change something in appareance ? or nothing noticable ?

**Comment by balbuze** [comment]
my nas is a dlink share center dns 320
