### ISSUE TITLE
ALARM SOUND EACH HOUR

### ISSUE THREAD

**Issue by nosferatujr** [volumio/Volumio2#660]
I test with a Raspberry Pi 2 and the volumio-0.976

Y setup the alarm at 09:15 , and the selected list is started each hour (at the right minute) ex, start at 16:15...   etc

**Comment by nosferatujr** [comment]
sorry , is duplicated issue. https://github.com/volumio/Volumio2/issues/654

**Comment by fanciulli** [comment]
Closing because duplicate
