### ISSUE TITLE
Add PI WIFI DONGLE

### ISSUE THREAD

**Issue by volumio** [volumio/Volumio2#663]
https://volumio.org/forum/resolved-using-official-raspberry-wifi-dongle-t4529.html#p20597

**Comment by WalterBorgstein** [comment]
Why would you build this? RPB3 has this default for only 40 EUR.
Just curious. Upgrading to new RB would not be that hard right?

**Comment by Frky** [comment]
Indeed, but I had the problem because I installed Volumio on a RPB2. 

I already had it, so from that point buying a wifi dongle (10-15$) is less expansive than upgrading the RP.
