### ISSUE TITLE
Wifi connecting and then disconnecting immediately after 

### ISSUE THREAD

**Issue by hfatgit** [volumio/Volumio2#668]
Wifi does connect when booting the system. It stays connected for a short period of time, retrieves the DHCP address, then disconnects from AP.  

Volumio 2 not usable at all using Wifi

using RC2 HOTFIX (2016-07-01) with Pi B+

**Comment by WalterBorgstein** [comment]
Thats a harsh statement. I have it working now on wifi. No issues. Kept it running all night long to test stability. Could you get some logs from the Volumio journal? Maybe some devs can spot weird activity. 

I gave the volumio a fixed IP in the dhcp. Maybe that helps?

**Comment by hfatgit** [comment]
Just stating the facts, nothing harsh here.  Wlan0 keeps the DHCP IP but cannot access the network. 
Static IP shows the same behaviour. 

Works like a charm when connected with eth0.
 
Version 1.5 did the Wifi job without problems.

**Comment by WalterBorgstein** [comment]
Why close the issue?

**Comment by hfatgit** [comment]
oops. Wurstfinger on mobile device

**Comment by WalterBorgstein** [comment]
;)

**Comment by volumio** [comment]
There is a setting in wireless.js that triggers hotspot mode if signal quality is not sufficient to get good performances.  At this point it seems that its too aggressive

**Comment by hfatgit** [comment]
Qualtiy 96/100 Signal 94/100. Too low?

**Comment by volumio** [comment]
Could you post the output of sudo journalctl - f?

**Comment by hfatgit** [comment]
My current settings for the wifi are accoring to issue 164 like
 /etc/wpa_supplicant/wpa_supplicant_mywlan.conf:
network={
    ssid="MYSSID"
    psk="passphrase"
}

/etc/network/interfaces:
auto wlan0
iface wlan0 inet dhcp
    wpa-conf /etc/wpa_supplicant/wpa_supplicant_mywlan.conf

I tripplechecked the psk: phrase is correct 

[journal.txt](https://github.com/volumio/Volumio2/files/428873/journal.txt)
Not much contents and the last few lines repeating over and over

**Comment by hfatgit** [comment]
Rebooted the Pi and logging the journalctl -f output for a while. Will attach the outcome soon.

**Comment by hfatgit** [comment]
Started journalctl-f > journal.txt immediately after login was possible

[journal.txt](https://github.com/volumio/Volumio2/files/428888/journal.txt)

**Comment by Callenberg** [comment]
I can confirm problems with the Wi-Fi connection, it is even worse with 0.979 than with 0.976.
I got it working by (after the connecting procedure):
1. turn off and turn on the Raspberry Pi
2. turn off
3. disconnect Ethernet cable
4. turn on

You can not just remove the Ethernet cable any more (as you could do using Volumio 1.55).
There were less turn ons and turn offs in the 0.976 version. 
You also have to refresh the pages manually, otherwise nothing seems to happen. The hotspot box disappears at an early stage in the procedure as well.

**Comment by christemporale** [comment]
I am running the latest version of Volumio: 2.246. I configured ethernet and wlan, both with static IP.
As long as an Ethernet cable is attached, I can access the GUI from both IPs and all works fine. Without ethernet cable, the system looses the wlan connection. After the boot, the wifi connection is lost almost immediately. I don't have this issue with runeadio
