### ISSUE TITLE
Volumio 2 - 0.976 or 0.979 couldn't play a cue+flac or ape

### ISSUE THREAD

**Issue by pyropingvin** [volumio/Volumio2#669]
I can list the songs but I can not put them in Queue.
I can play only whole files, but I can't choose individual songs.

**Comment by lowrideris** [comment]
I have the same problem on x86 build. 
I can see cue file song list, but if i run on of them, volumio crashes and restarts (fast)to main page.
 Pls fix cue file support:)

**Comment by volumio** [comment]
Fixed, it will be on next release
