### ISSUE TITLE
ODROID: add Wifi dongle drivers

### ISSUE THREAD

**Issue by youpilai** [volumio/Volumio2#674]
version RC2Fix on Odroid C2

As for the Odroid version, it lacks some drivers for wifi dongles (Example Edimax EW-7811UN Nano or TP-Link Archer T1U)

Could you please add these in future release ?

**Comment by volumio** [comment]
Yes, if you could find the firmwares and place the link here, I'll do it with much pleasure

**Comment by youpilai** [comment]
Don't know if you're talking about this : 
[http://static.tp-link.com/res/down/soft/Archer_T1U_V1_150909.zip](url)

indicated for 	
Linux (Kernel version 2.6~3.16)
