### ISSUE TITLE
Mixer control dropdown is empty (Raspberry Pi + Hifiberry DAC)

### ISSUE THREAD

**Issue by Atrejoe** [volumio/Volumio2#680]
I wanted to see if I could control the volume of playback by changing the mixer control. (I remember a hardware vs software choice in Volumio 1).

The dropdown where I'd expect this choice is empty, see:
![image](https://cloud.githubusercontent.com/assets/585091/18032206/9286203c-6cfe-11e6-98ab-a73d9f9b35e2.png)

(Volumio version 0.979 on Raspberry PI 1 B, Hifiberry DAC, old model B)

**Comment by balbuze** [comment]
Volumio2 does not yet support software mixer. It's because it's empty in your screenshot. It 's going to be added.

**Comment by Atrejoe** [comment]
Sounding like a user here, suggestions:
- Shouldn't the dropdown be disabled when there is no choice (single option)
- Shouldn't the dropdown be replaced by a label stating there is no mixer control available in my case

I don't see software volume control on the roadmap (https://github.com/volumio/Volumio2), any ETA?

**Comment by Sjit** [comment]
I have the same problem. 
Volumio version 0.979 on Raspberry PI 1 B, Hifiberry DAC, old model B
For my current use, mediaplayer for the kids, this is a significant problem since i dont have a hardware remote volume control.

**Comment by volumio** [comment]
Fixed

**Comment by Atrejoe** [comment]
Great to hear, thanks!
