### ISSUE TITLE
Album art not stable enough

### ISSUE THREAD

**Issue by volumio** [volumio/Volumio2#70]
Albumart server crashes, the behaviour seems to happen when we sequentially add lot of items to queue.
I suspect this is due to lack of / in the web art path

**Comment by fanciulli** [comment]
A fix has been introduced in the error-catch branch. It is more stable right now. The server anyway still lacks a load testing. Are we going to make it?

**Comment by volumio** [comment]
Album Art doesn't work when Volumio is launched from systemd service...
