### ISSUE TITLE
Hifiberry DAC+ and mpdroid: control volume 

### ISSUE THREAD

**Issue by pboesch** [volumio/Volumio2#701]
Hi all,

I just bought the Hifiberry DAC+. It works very well with volumio !

On my phone, I use mpdroid to control volumio at home. Before the DAC, I can control volume with this application without any problem. 

Now the control volume has no effect. I should specify the control on the **WebUI works correctly**. The issue appears only with a mpd client.

My configuration is here:
![](https://lut.im/g94eLSl9xZ/VlBu69g5cxKF3eiG)
![](https://lut.im/eaNTMktWFZ/IhWdHXM3te9i328W)

```

volumio@volumio:~$ cat /boot/config.txt 
initramfs volumio.initrd
gpu_mem=16
force_turbo=1
disable_splash=1
dtparam=audio=on
dtparam=i2c_arm=on
dtoverlay=hifiberry-dacplus
```

Maybe, my configuration is wrong ?

Regards,

**Comment by volumio** [comment]
No, it's just that Volumio controls the volume directly, and not via MPD. Its a known issue, and to solve it we must complete the mpd emulation plugin...

**Comment by kiwiASRALL** [comment]
Ok thank you :)

**Comment by HolyMacarony** [comment]
I would appreciate that too.  Same problem here
