### ISSUE TITLE
Problem with change Player name and push song with android phone (DLNA)

### ISSUE THREAD

**Issue by Ethanwain** [volumio/Volumio2#710]
1.  if I change system name with Chinese character，can't save;
2. if I play songs with Andriod phone, when I change volume then system volume return 0;
3. what is the volumio2 system username and password?

**Comment by volumio** [comment]
Could you please paste the chinese name here?
What is your setup ( pi? dac? network?)
volumio:volumio

**Comment by Ethanwain** [comment]
system version:0.979 volumio2
device:pi3 model B
dac:IQaudIO DAC Plus
network:wifi
Detail:
even if I change eng name also can't save(still old name);
use android phone play songs can't change volume,if change system volume turn to zero.

**Comment by volumio** [comment]
Fixed
