### ISSUE TITLE
albumart not loaded because of special characters

### ISSUE THREAD

**Issue by CaptainMetal** [volumio/Volumio2#726]
i find something out about the albumart covers loaded from internet automatically:
the covers are not correctly loaded when there are special characters in the album title or artists name  (or may be the directory path of the musicfiles ?) like:

 &
slash
minus
 !
 [
 ]

this is v.0991 and happens in the browsetab viewing albums or artists and also in the playbacktab.
when the picturefile exists as file in the musicfile directory, then in the playbacktab the albumart is displayed correctly, but not on the browsetab.
and sometimes there is just an X. 

regards,
CaptainMetal 

![image](https://cloud.githubusercontent.com/assets/20752794/18817119/0fb728c4-8359-11e6-810b-95a605ecc246.png)
![image](https://cloud.githubusercontent.com/assets/20752794/18817125/34bdffda-8359-11e6-98a1-45cbc5d07093.png)
![image](https://cloud.githubusercontent.com/assets/20752794/18817130/48038970-8359-11e6-9b8c-e7e8391d02d7.png)

**Comment by xipmix** [comment]
It looks like this can be closed - @CaptainMetal can you try with 2.031 which should have the fix referenced above and post your results here?

**Comment by CaptainMetal** [comment]
thank you. it seems to me, that this problem is fixed now. 
still some problems with albumart on some albums, but it looks like that the download doesn't find the albumart online. may be this will be solved in the future, when instead the folder.jpg file from the music directory itself is used. 

this would be kind and also faster than downloading the covers from internet, which are also sometimes different to the "real" one. 

kind regards,
captainmetal
