### ISSUE TITLE
cann't resume same web radio channel after stopping 

### ISSUE THREAD

**Issue by aidanreilly** [volumio/Volumio2#727]
volumio2 version 0.979

Can't resume a radio channel after stopping the radio stream. Workaround is to start another radio channel, and then click the desired radio station.

**Comment by jo-me** [comment]
Reproducible like this:
- Goto the webradio list in the Browse-View
- Double-click one to play
- Stop the playback with the stop button
- Double-click again on the same web radio station
==> nothing happens

In adition to that, double-clicking on the currently playing web radio will stop the playback for some reason...
