### ISSUE TITLE
volumio 0.993 - i2s activation

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#730]
If i2s dac is activated, you can't select a other output (jack, hdmi, usb)

**Comment by heis2201** [comment]
Hi, Could someone please provide me with a download link to 0.993? I have had problem with 0.928 and 0.978 on my RpiB+, and I feel ready to give 0.993 a try.

**Comment by balbuze** [comment]
just go in IP/dev from webUI click dev go back to volumioUI and go to system check for update
