### ISSUE TITLE
Set default Startup volume

### ISSUE THREAD

**Issue by exetico** [volumio/Volumio2#734]
Hi' 

I can see that it was been up before - but not with the best answer.

How do add a default volume at startup? 100% is just a bit to high, for my solution. I using a USB DAC, and the volume-buttons works fine in the Volumio GUI.

Are you guys thinking adding this feature - and would you pointing out a solution for my setup.

This doesn't work:

```
volumio@volumio:/usr/share/alsa/init$ mpc volume 10
Morten Resen - Episode 1
[playing] #1/1  25:46/40:34 (63%)
volume: 10%   repeat: off   random: off   single: off   consume: off
volumio@volumio:/usr/share/alsa/init$ mpc volume 80
Morten Resen - Episode 1
[playing] #1/1  25:50/40:34 (63%)
volume: 80%   repeat: off   random: off   single: off   consume: off
volumio@volumio:/usr/share/alsa/init$
```

(The volume isn't change at all, then running the commands)

Best Regards,

![image](https://cloud.githubusercontent.com/assets/3549445/19015931/3ec6dc90-880e-11e6-838a-8ada8e578bc5.png)
![image](https://cloud.githubusercontent.com/assets/3549445/19015933/4479e9ac-880e-11e6-9ecb-965229f36858.png)
![image](https://cloud.githubusercontent.com/assets/3549445/19015938/54b37702-880e-11e6-9eac-a556a4ca192d.png)

**Comment by 01findus** [comment]
I can confirm this!  In Version 0.979 the Volume is on 100% after Startup or reboot of Volumio with an USB DAC (Nubert A200 Speakers) connected.
The Setting of the Default Startup Volume does not seem to affect the startup behaviour.

Best Regards
Alexander

**Comment by volumio** [comment]
Fixed in the latest dev version
http://updates.volumio.org/pi/volumio/1.005/volumio-1.005-2016-10-07-pi.img.zip
