### ISSUE TITLE
0.991: Can't use airplay

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#736]
Hi,
I am glad 0.991 release is stable and I don't have any OOM or (W)LAN issues. Great works. Thanks to all devs - looks like we're getting close!

The issue I am experiencing (actually two but I will open separate issues here), is that I am not able to stream anything from my iphone to Volumio 2. From my Iphone I do see Volumio2 as potential Receiver of the audio stream but it doesn't output anything.

**Comment by volumio** [comment]
What is your output device? I2S DAC? If yes, which model?
USB? Analog out? 

Let me know

**Comment by heis2201** [comment]
Rpi 1 B+
Analog out via I2S Dac: Durio Sound using the HifiBerry driver.

Playing local audio files from USB or webradio stream works fine.

**Comment by volumio** [comment]
Please try to reboot. Let me know

**Comment by heis2201** [comment]
I will, later today.

**Comment by heis2201** [comment]
Rebooted - but that didn't help.

**Comment by heis2201** [comment]
I re-flashed with current Volumio2 1.001 and airplay works just fine. 

You can close this issue, NOTABUG. Thanks

**Comment by heis2201** [comment]
Maybe it is an issue:
Running 1.005, airplay from my iphone is not working.

**Comment by volumio** [comment]
What device are you using? I2S DAC? Which one? USB DAC? Which one?

**Comment by heis2201** [comment]
Volumio 1.007 on RPI1B+ with furios Sound I2S Dac, using hifiberry driver. Playback of local files works fine.
