### ISSUE TITLE
can't figure out how to point Volumio2 to my music

### ISSUE THREAD

**Issue by EMCP** [volumio/Volumio2#74]
so I have an SSD drive connected via USB to a raspberry pi 2.

I have volumio 2 alpha distro running, and want to simply tell it.. "Hey Volumio2, all the music you need to find is in this direction `.....` " 

I clicked around and started to get into a bad state it would appear.  Using the latest Chrome on OSX btw...
![screen shot 2015-10-26 at 6 55 21 pm](https://cloud.githubusercontent.com/assets/3691722/10747507/2aed6c6e-7c13-11e5-94a8-418917cfb17c.png)

**Comment by volumio** [comment]
This image is quite old. Please wait until we release next beta.

**Comment by EMCP** [comment]
okay, thanks.  If there's a way to get a notification I'd love to sign up
