### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by philkunz** [volumio/Volumio2#75]
What license is this distributed under?
MIT?

Please add a license file so it is clear how contributions and forks are positioned in a legal context.

**Comment by volumio** [comment]
still deciding, see https://github.com/volumio/Volumio2/issues/35

It will be most likely GPL or MIT

**Comment by philkunz** [comment]
OK, I see. I'm really eager to contribute to this project, but without proper license specifications this is not possible. When adding the license file later on, theoretically you have to get permission for the license change from every single contributer, since they didn't contribute under a certain license originally.

**Comment by volumio** [comment]
Ok, will update the original issue, please continue there
