### ISSUE TITLE
UI Update procedure: Confirmation step missing

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#750]
Under *System Updates* it says *Check Updates* (Description: *Check if newer versions of the system are available*) but it looks like this button does more. It's a *Check for Update and if available install it*-button.

The issue I am seeing: Either the description should be adapted to what the button does, or there should be a confirming question/user dialog like *Do you want to install the available update*?

Anyway, the description should rather be: *Check if newer version of Volumio is available*

**Comment by pilifsch** [comment]
There is a dialog that show what version is available and provide changelog. Then user is able to cancel or 'update now'. Anyway I agree with your suggestion of description ('Check if newer version of Volumio is available').
