### ISSUE TITLE
No Audio Pimoroni Phat Dac

### ISSUE THREAD

**Issue by Kev7274** [volumio/Volumio2#755]
Set up the audio with this setup,but no sound.
https://learn.pimoroni.com/tutorial/phat/raspberry-pi-phat-dac-install

**Comment by macmpi** [comment]
works with Hifiberry DAC setting

**Comment by volumio** [comment]
Yes the tutorial is related to raspbian, not volumio

**Comment by macmpi** [comment]
Still would be nice if that DAC had an entry in the Volumio UI pick-list (event if it's a duplicate of HifiBerry DAC): would avoid questions in the future.
Thanks!
