### ISSUE TITLE
Move from JS to TypeScript

### ISSUE THREAD

**Issue by philkunz** [volumio/Volumio2#76]
As volumio is a bigger project I would propose moving to TypeScript with a gulp compile pipeline.

**Comment by fanciulli** [comment]
Seems interesting but i am wondering what the impact would be for Volumio.

**Comment by philkunz** [comment]
What should the impact be? It would allow better structuring of the code, would give access to things like easy classes without breaking support for ES5.
Errors that are not caught with TypeScript can be traced to their origin with source maps.

**Comment by fanciulli** [comment]
Can we start using it leaving the old code in place? I think it is probably possible..

**Comment by philkunz** [comment]
Since TypeScript is a superset of JavaScript that should work.

**Comment by philkunz** [comment]
I've created a tool that helps with writing TypeScript for (npm) modules:
https://www.npmjs.com/package/npmts
I'll add automatic source map integration later this week.

If there are special requirements for volumio that you'd like to see integrated, let me know.

**Comment by apinner** [comment]
Anything happening on this @philkunz 

Reopen if something is still happening.

**Comment by philkunz** [comment]
@apinner Well, I'm not putting any more work into this project, until the license is clarified. Then I'll be happy to fork, do the switch and hand in a PR. Until then forking is to be considered a grey area in law.
