### ISSUE TITLE
[SOLVED] Volume control not working: RPi 0 (zero), PlainDAC, Volumio 2.000

### ISSUE THREAD

**Issue by chsims1** [volumio/Volumio2#767]
Unable to alter volume via UI. Nothing showing in 'Mixer Type' or 'Mixer Control Name' boxes. 

'Output Device' and 'DAC Model' show 'Hifiberry DAC'. It worked ( I think, but can't categorically confirm) in earlier versions

Edit: sorry, on reflection I should perhaps have added this issue to #764

Edit 2: While fiddling around with the settings, I reselected hifiberry DAC and 'software mixer' magically appeared as 'Mixer type.' The volume control now works.  I have no idea why it didn't take the first time.

**Comment by luxus** [comment]
i have a similar problem...
I changed to a different dac and back.. then I got the software mixer.. but I don't get any sound
