### ISSUE TITLE
Random / Shuffle not working on 2.001 (R-Pi2)

### ISSUE THREAD

**Issue by P-Longshanks** [volumio/Volumio2#783]
Hello!

"Random" (or Shuffle) Play does not work on my R-PI2. 
When a song is finished it just plays the next track from the playlist, not a random on. 
When I skip a song manually it plays a random song from the playlist correctly. 

For context: I have 10.000+ songs in my library which should all be played random.

_____
Thanks for your great work!

**Comment by Callenberg** [comment]
I can add:

1. Consume does not consume. 
2. The text "Consume playlist" shouldn't that be change to "Consume queue" instead?
3. Repeat does not repeat at end of the queue.
4. Emptying the queue by using the trash can button does not reset the playing order of the (new) queue. 

Regarding Playlists:
1. Applying Play for a playlist means Clear and play.
2. Applying Clear and play, empties the queue correctly, but the playlist is not added. The UI is also not refreshed so you get a little confused.

These bugs are also mentioned in the forum:
[https://volumio.org/forum/volumio-final-release-very-near-pre-test-needed-t4709-100.html]

Thanks a lot.
