### ISSUE TITLE
Mixer Type does not work

### ISSUE THREAD

**Issue by Bergmann1** [volumio/Volumio2#788]
Hello,

In Volumio 2.001 on RB2+ Mixer Type menu does not work well, the only selection that I am getting is "Hardware". I tried to select the Mixer Type with Output Device "Audio Jack", "HDMI" and "DAC", but nothing has changed...the Mixer Type only gives only option "Hardware".

**Comment by balbuze** [comment]
what is the problem for you of having "hardware" mixer ? It is porposed because your dac supports it! So don't need a software mixer.

**Comment by Bergmann1** [comment]
I do not have any problems with having the hardware mixer, but it does not work. When I increase or decrease the volume by volume bar, nothing happens, the sound volume is constant.

**Comment by Bergmann1** [comment]
I had the same problem in 1.55, so I was using the software mixer instead the hardware one.

**Comment by balbuze** [comment]
what is your dac ?

**Comment by Bergmann1** [comment]
HRT Music Streamer II

**Comment by balbuze** [comment]
I see... USB dac. I 've got the same problem with a usb FDA (fx audio 802). Alsa gives a pcm mixer with no effect... I made a test with Ubuntu with the same behaviour. It seems something in wrong in alsa...

**Comment by Bergmann1** [comment]
Strange...did 1.55 use also alsa?

**Comment by balbuze** [comment]
Yes but when choosing software mixer in 1.55 it was managed by mpd. The problem was with other app such as -spop (for Spotify) that don't use mpd and then no mixer
