### ISSUE TITLE
Wrong UI refresh after deleting webradio favorite

### ISSUE THREAD

**Issue by jo-me** [volumio/Volumio2#792]
when I'm in "Browse" -> "Web Radio" -> "Favorite Radios" and delete an entry there via "Remove from Radio favorites" the UI does not stay in the webradio favorite screen but jumps to the global "Favorites" section of the libarary which does not contain webradios.

I'm using verrsion 2.001

The associated forum thread is here: https://volumio.org/forum/issue-when-deleting-webradio-favorite-t4846.html

**Comment by volumio** [comment]
You're right... Going to fix this one, will need some time tough...
