### ISSUE TITLE
Deleting webradio item deletes all with same URL

### ISSUE THREAD

**Issue by jo-me** [volumio/Volumio2#793]
when I'm in "Browse" -> "Web Radio" -> "Favorite Radios" and delete an entry there via "Remove from Radio favorites" any webradio station with the same URL is deleted along with the selected entry.

So in my case I accidentally added a station twice which was created with a different name (in that case a name including the currently playing song). When I deleted the duplicate entry, the original entry disappeared with it. So then I had to re-add the station to the favorites.

The associated forum thread is here: https://volumio.org/forum/issue-when-deleting-webradio-favorite-t4846.html

**Comment by jo-me** [comment]
PlaylistManager.prototype.commonRemoveFromPlaylist() checks only equality of URI and serviceName ("webradio" in this case) when deleting stations.

**Comment by volumio** [comment]
We should send also the name to this function, which will probably break something ...
Unfortunately this will go NOFIX...
