### ISSUE TITLE
IQAudio Digiamp+ unmute

### ISSUE THREAD

**Issue by eggerph** [volumio/Volumio2#799]
Hi
Just wanted to report a small issue. I have a IQAudio Digimp+ and when I set the I2S DAC in the settings the first time and the system reboots the DigiAmp+ is also unmuted correctly. A reboot apparently still keeps pin 22 high and it is still unmuted. However when it is disconnected from the power source and booted up again the Digiamp+ is stays muted. I solved to problem currently by adding 
echo "22" > /sys/class/gpio/export
echo "out" >/sys/class/gpio/gpio22/direction
echo "1" >/sys/class/gpio/gpio22/value
to the rc.local file. However it would be nice if this would work without doing so.
cheers and thanks in advance!
Philipp

**Comment by volumio** [comment]
Hi philipp I just solved this issue. Please try this image and tell me if that works:
http://updates.volumio.org/pi/volumio/2.004/volumio-2.004-2016-10-21-pi.img.zip

**Comment by eggerph** [comment]
Hi, thanks for the quick reply. I tested the 2.004 and seems to work fine. Unplugged it once and Amp still worked after that. However the webUI has problems on my laptop. It doesn't load anymore. (attached a screenshot)
![volumio_problem](https://cloud.githubusercontent.com/assets/17647632/19647358/0ff79324-9a41-11e6-84fb-a420c54e3dc2.PNG)
 Works fine on my tablet though. Is this known? 
But the actual issue seems to be solved!
