### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by jomo** [volumio/Volumio2#8]
I noticed there's tabs and spaces mixed all over the place. Can we agree on a style to use everywhere?
My editor (sublime text + eslint) also starts highlighting every other line because there's missing semicolons or other issues.

![screenshot](https://i.imgur.com/M1FEr3n.png)

I personally prefer 2 spaces for indentation, I think that's what most node projects seem to use as well.
I recommend that everyone uses [eslint](https://github.com/eslint). There are lots of [integrations for different editors](http://eslint.org/docs/user-guide/integrations).

**Comment by rmccawl** [comment]
Another recommendation would be to use something like an .editorconfig file where you can specify how the text-editor handles specific file types based on the extensions.

You can configure tabbing, spaces, line-endings and much more.

http://editorconfig.org/

**Comment by jomo** [comment]
indeed, editorconfig is really nice :+1:

**Comment by hans-sperling** [comment]
Right! "editorconfig is really nice" :+1:
