### ISSUE TITLE
volumio CLI not working for playback commands

### ISSUE THREAD

**Issue by jo-me** [volumio/Volumio2#810]
The "volumio" command line interface throws errors on all commands that are handled by the "playback.js" file, so play / pause / next / etc.

Example:

volumio@volumio:~$ volumio play
Sending play
/volumio/app/plugins/system_controller/volumio_command_line_client/volumio.sh: /volumio/app/plugins/system_controller/volumio_command_line_client/commands/playback.js: /bin/node^M: bad interpreter: No such file or directory

The reason is in fact some invisible illegal character in the first line.

**Comment by jgarriga78** [comment]
Hi,
open /volumio/app/plugins/system_controller/volumio_command_line_client/commands/playback.js in nano, save it with: ctrl+x -- YES -- alt+M to save it in Ms-Dos mode.

**Comment by jo-me** [comment]
thanks, the fix is already in the current release.
