### ISSUE TITLE
Webradio track title not updated

### ISSUE THREAD

**Issue by cgtobi** [volumio/Volumio2#819]
I'm currently running v2.011. I compared the same stream (http://streams.radiobob.de/bob-alternat ... ediaplayer) in Theremin (macOS mpd client), VLC, MPoD (iOS mpd client) and Volumio. MPoD, VLC and Theremin update the currently playing title fine and VLC (macOS) as well as MPoD v2.1 (iOS) show the stream title, whereas Volumio stops updating the currently playing title and doesn't display the stream title at all.

![bildschirmfoto 2016-10-27 um 21 59 39](https://cloud.githubusercontent.com/assets/856782/19872104/6837ba6a-9fb8-11e6-98ab-99bdc68c29e8.png)

**Comment by daeavelwyn** [comment]
hi here,

as mentionned in the forum ([https://volumio.org/forum/001-webradio-track-name-not-updated-t4925.html](https://volumio.org/forum/001-webradio-track-name-not-updated-t4925.html), this bug is still present in the 2.029 update :)

**Comment by Loader23** [comment]
Also present in 2.031.

**Comment by cgtobi** [comment]
As far as I can tell volumio knows all about what's beeing played, so it must be some communication or display issue in the front end that the tracks are not updated correctly.

e.g.
`Nov 28 21:24:52 volumio volumio[816]: info: STATE SERVICE {"status":"play","position":0,"seek":2444678,"duration":0,"samplerate":"44.1 KHz","bitdepth":"24 bit","channels":2,"random":false,"updatedb":false,"repeat":false,"isStreaming":false,"title":"Faith No More - I'm Easy","artist":null,"album":null,"uri":"http://streams.radiobob.de/bob-kuschelrock/mp3-192/mediaplayer","trackType":"de/bob-kuschelrock/mp3-192/mediaplayer"}
`

**Comment by Loader23** [comment]
Still present in 2.041...

**Comment by biva** [comment]
Still present in 2.118. Any update? Available for testing if needed.

**Comment by xipmix** [comment]
There is one thing that doesn't look right to me:
 *  ```"trackType":"de/bob-kuschelrock/mp3-192/mediaplayer"}```
This seems to be the same symptom that I noticed in #1116. 

A similar issue was fixed between 2.099 and 2.114 (somewhere between 29 Feb and 6 Mar) for the 'Artist' field, but here we have ```"artist":null```. This is probably a property of the webradio source so volumio is probably doing the right thing for that field.

**Comment by volumio** [comment]
It now works

**Comment by jlagden** [comment]
I am finding the title is not getting updated when I play internet radio streams.
eg. http://138.201.248.219:8018/stream

If I play in winamp on a pc desktop the title gets updated, however it doesn't in volumio.
I noticed if I do a `mpc status` mpd is not updating the title either, so this is probably a mpd problem.

I am using Volumio 2.389 (latest)

Any thoughts?
