### ISSUE TITLE
Can't reach webserver after update

### ISSUE THREAD

**Issue by Bonnee** [volumio/Volumio2#824]
After I updated to RC2 through the WebUI I encountered this error in the systemd status output for volumio.service:

> volumio[2843]: Discovery: StartAdv! false
> volumio[2843]: Discovery: Started advertising... Volumio - false
> volumio[2843]: Discovery: ecc TypeError: Cannot read property '0' of undefined

This error comes up repeatedly when I try to load the WebUI inside a browser.
Is there a way to fix this? I'll post more if someone instructs me on what to do

Thanks!

**Comment by volumio** [comment]
This is a dns related error. Remove power and turn it on again, it should disappear

**Comment by Bonnee** [comment]
Unfortunately I rebooted many times and the error didn't disappear. I also noticed that my / and /static partitions are full. Can that be the cause?

**Comment by heis2201** [comment]
I'd recommend you start with a newer release than RC2. For example, 2.001: https://volumio.org/get-started

**Comment by Bonnee** [comment]
That's just what I did yesterday and now it works!
Thanks for the help!
