### ISSUE TITLE
Help tooltip is settings for "DSD over PCM" 

### ISSUE THREAD

**Issue by arthurlutz** [volumio/Volumio2#836]
I'm a bit new to the whole HiFi scene and so some of the options in the playback settings are a bit obscure to me. It would be nice to have a tooltip to explain some of the options or a link to the documentation. In my case "DSD over PCM" is a bit of an unknown and is on by default. 

Thanks.

**Comment by xipmix** [comment]
It's a pretty [common](http://www.dcsltd.co.uk/support/what-is-dop-dsd-over-pcm) [term](https://en.wikipedia.org/w/index.php?title=Direct_Stream_Digital&section=10#DSD_over_USB) though I agree it's somewhat opaque to a newcomer.

I don't see any place that extended explanations could go. I tried updating the doc: string in https://github.com/volumio/Volumio2/blob/master/app/plugins/audio_interface/alsa_controller/UIConfig.json but I don't see how that information gets displayed.
