### ISSUE TITLE
Plugin manager: uninstall.sh not used

### ISSUE THREAD

**Issue by macmpi** [volumio/Volumio2#851]
It seems plugin uninstall procedure does not execute eventual `uninstall.sh` script some plugin may need for proper clean-up.

**Comment by jo-me** [comment]
Associated forum thread: https://volumio.org/forum/plugin-config-file-remains-after-uninstall-t5281.html

**Comment by volumio** [comment]
https://github.com/volumio/Volumio2/commit/c21785b0877305c02ee26eb8fce7c92443d19e4c
