### ISSUE TITLE
Back button in BROWSE environment for Spotify What's new goes to far back

### ISSUE THREAD

**Issue by WalterBorgstein** [volumio/Volumio2#860]
While searching for music in the browse section, in Spotify, What's new. You can follow a path down to a specific number of an album (see screenshots below). If however you decide you want one step back. back to the album overview, the back button will start at the beginnen of the browser view. This makes browsing thru new music in Spotify not user friendly.

This only seems to happen in the What's new section of Spotify.

**edit:** It also happens if your are at the song level of the Genre & Moods section. If your in the playlist (song level) and push back, you will be directed to the highest level of the spotify browser.

I saw not difference using Google Element inspector. But I'm not a dev.

<img width="263" alt="screen shot 2016-11-20 at 15 40 52" src="https://cloud.githubusercontent.com/assets/15366175/20463638/088d05ea-af38-11e6-9008-bfd87a836097.png">
<img width="320" alt="screen shot 2016-11-20 at 15 40 33" src="https://cloud.githubusercontent.com/assets/15366175/20463624/e48f7e52-af37-11e6-8ccf-0266d55cfa1f.png">
<img width="307" alt="screen shot 2016-11-20 at 15 40 40" src="https://cloud.githubusercontent.com/assets/15366175/20463625/e7f76a78-af37-11e6-9a7d-6d81df9149e9.png">
<img width="273" alt="screen shot 2016-11-20 at 15 40 46" src="https://cloud.githubusercontent.com/assets/15366175/20463627/ea89f0b2-af37-11e6-95b2-6e65bb55c651.png">

**Comment by xipmix** [comment]
possibly related issues: #498, #975

**Comment by volumio** [comment]
Duplicate, closing
