### ISSUE TITLE
multiroom status

### ISSUE THREAD

**Issue by canda** [volumio/Volumio2#889]
I'm just curious on what's the current status in the multi-room support, particularly how the syncing between devices audio may be achieved.

Reading the wiki one may assume that's not yet there 
https://github.com/volumio/Volumio2/wiki#output-stack
But I saw a few PRs and Issues related

Is there any progress in this?

**Comment by gkkpch** [comment]
Multiroom support is planned with Snapcast (already integrated in the build), but this has not been scheduled yet.
