### ISSUE TITLE
Volumio2.031 cannot connect wep wifi.

### ISSUE THREAD

**Issue by nop9dogs** [volumio/Volumio2#894]
I use Volumio2.031 with raspberry pi 2 ,I cannot connect wep wifi at my home,but when I brought them toconnect with wpa wifi ,they can connect easily.Please advice me for solution.

**Comment by apinner** [comment]
Don't use WEP. That's just general advice nothing to do with Volumio. You can crack a WEP password in under 60 seconds with freely available software!
