### ISSUE TITLE
Include ifplugd in base OS?

### ISSUE THREAD

**Issue by leafy7382** [volumio/Volumio2#902]
I have ran into a strange issue where without Ethernet plugged in, WIFI would not connect. I read from https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_ifplugd_package and installed the ifplugd package to put eth0 under the management of the package and it works VERY WELL.

Would you consider putting the package into the base Volumio OS so that folks won't have to debug the weird "No WIFI without Ethernet" issue?

**Comment by volumio** [comment]
Yes, definetely!

**Comment by volumio** [comment]
It is however a build issue, so moved to https://github.com/volumio/Build/issues/111
