### ISSUE TITLE
Fix kernelsource 

### ISSUE THREAD

**Issue by volumio** [volumio/Volumio2#904]
https://volumio.org/forum/volumio-and-kernelsource-t5286.html#p24876

**Comment by xipmix** [comment]
Is it not better to fix the sudoers file?  '/bin/systemctl' is in the NOPASSWD: list already so the 'echo' and the sudo -S seem unnecessary. Also the target scripts all have the right ```#!``` line so all that should be needed is ```chmod a+x``` ... but the execute bit is already set.

I prepared a patch but don't want to bother you with a PR if you are on it already.

**Comment by volumio** [comment]
Please send, it will be useful!

**Comment by xipmix** [comment]
I got a bit overexcited and gave kernelsource.sh a working over. See [kernelsource-part2](https://github.com/xipmix/Volumio2/tree/kernelsource-part2). It builds on the changes in the PR already sent.

**Comment by volumio** [comment]
Ehehe, Ok I will test asap! thx!

**Comment by xipmix** [comment]
I found some problems; calling pull.sh and kernelsource.sh needs sudo -S or changes to the sudoers file. The first can be handled by not requiring root permissions. The second needs [this](https://github.com/xipmix/Build/tree/kernelsource-part2)
