### ISSUE TITLE
Plugin deinstallation leaves config behind

### ISSUE THREAD

**Issue by jo-me** [volumio/Volumio2#905]
After uninstalling a plugin, the config file(s) of the plugin under /data/configuration are not removed.

The method PluginManager.prototype.removePluginFromConfiguration() removes only the in-memory configuration of the plugin but not the files.

Aside from the residue this might cause sideeffects when reinstalling plugins .

**Comment by jo-me** [comment]
Associated forum thread: https://volumio.org/forum/plugin-config-file-remains-after-uninstall-t5281.html

**Comment by jo-me** [comment]
Another plugin deinstallation related issue is here https://github.com/volumio/Volumio2/issues/851

**Comment by macmpi** [comment]
Last I checked, it seemed plugin configuration folder was not removed upon uninstall.
Has this been fixed?

**Comment by macmpi** [comment]
fixed with https://github.com/volumio/Volumio2/commit/e512b5064eff470f696d69612fb11e859d020d92: thanks!
