### ISSUE TITLE
Airplay crashes

### ISSUE THREAD

**Issue by volderette** [volumio/Volumio2#910]
Hi,

when I listen to music from my macbook via Airplay and try to switch to my iPhone to Airplay, the Airplay service crashes. Volumio is gone from the list of Airplay devices then. Have to restart volumio. Can reproduce the problem every time.

Cheers,
Andreas

**Comment by volderette** [comment]
Log says:
airplay.service: main process exited, code=killed, status=11/SEGV
Unit airplay.service entered failed state.

**Comment by volumio** [comment]
Thanks, I know how to fix it then!
