### ISSUE TITLE
Inconsistent and incomplete search results

### ISSUE THREAD

**Issue by retide** [volumio/Volumio2#913]
First of all thanks for this increasingly great piece of software and the work devoted to it. I'm using Volumio 2.031 on a PI3. Music is stored on a USB flash drive (about 500 tracks in 360 albums). I observed the following search behaviour that does not seem to be desirable. 

Case 1:
- There are two albums in the database ("artist - album title"): (1) "Bugge Wesseltoft, Henrik Schwarz & Dan Berglund - Trialogue" and (2) "Bugge Wesseltoft; Henrik Schwarz - Wesseltoft Schwarz Duo".
- If I search for "Schwarz", the search lists the artist of (1) under "Artists", but not the artist of (2).
- If I search for "Bugge", neither (1) nor (2) is found under either artists or albums.

Case 2: 
- There is an album "Sometree - Bending the Willow" and several more tracks and artists that begin with or contain the letter sequence "Some".
- If I type "Some", volumio yields several artists, albums and tracks (e.g. "Bonnie Somerville" or "Somebody Outside"), but not the artist Sometree.
- Once I continue typing the search string "Somet" suddenly yields the desired artist (and another album beginning with "Sometimes" that should have been listed before.)

The first case may be explicable by special characters in the tags ("&" "," ";") yet it would be great if the search was more tolerant here.

Two more issues that are no bugs, but that I at least do not find very intuitive: For one, when I go to "Browse" and then "Albums", entering a search string will not limit the current display, but browse the entire database. I'd rather have it show me the albums that match the search string. And second, if I search for an artist name, it does not list albums by that artist as it only seems to match album titles. (I usually type in an artist name to quick browse to the albums by that artist.)

**Comment by volumio** [comment]
Fixed
