### ISSUE TITLE
[Question] Using PCM5102A DAC via I2S

### ISSUE THREAD

**Issue by codewarriorFX** [volumio/Volumio2#924]
Hello,

I bought this DAC from DIYINHK and plan to use it on a BeagleBone or Rpi with I2S. I see this DAC is asynchronous since it "generate MCK Internally with BCK as reference" (according to the specs). Do I need to setup the I2S manually to not use the MCLK or the board will automatically detect it?

DAC board: http://www.diyinhk.com/shop/audio-kits/31-384khz32bit-pcm5102a-dac-i2s-input-ultra-low-noise-regulator.html

I will use this image to test with the BBB: https://volumio.org/forum/volumio-image-for-bbb-with-miero-kernel-botic-t5248.html

**Comment by gkkpch** [comment]
Please, questions should be posted on the forum, this is reserved for issues.
