### ISSUE TITLE
Add Bluetooth bluez firmware to allow Bluetooth keyboard connection

### ISSUE THREAD

**Issue by whatdoineed2do** [volumio/Volumio2#925]
Add following pkgs to default build

bluez         5.23-2+rpi2
bluez-firmware  1.2-3+rpi1
pi-bluetooth    0.1.1

And enable the hciuart service so  Bluetooth keyboards can be paired/work with volumio

All kernel modules are already in the build so extra disk space considerations for these 3x pkgs is irrelevant

I had to compare bolumio to another distr to figure out why no Bluetooth controller available

**Comment by ashthespy** [comment]
Cleaning up some old issues -- included in https://github.com/volumio/Build/commit/98e528a81fc54bf343616a910a76d7689c17b44e
