### ISSUE TITLE
Volumio starts playing after DLNA source sends 'stop' command

### ISSUE THREAD

**Issue by efwe** [volumio/Volumio2#931]
I recently started using pulseaudio-dlna (https://github.com/masmu/pulseaudio-dlna) to send music to Volumio.

Now i noticed, that whenever a stream finishs Volumio instantly starts playing from the queue.
As long as i listened to mixes or other longer stuff this was ok, but no i tried streaming one album from 'cmus' and this just does not work. After every song cmus stops and the queue starts.

i attach the conversation (pulseaudio-dlna already in debug mode). From what i can see there is a normal(?) 'stop' in line 118 and an immediate 'start' after that.

[volumio_pulse-audio-dlna_conversation.txt](https://github.com/volumio/Volumio2/files/672155/volumio_pulse-audio-dlna_conversation.txt)

Please forgive me any obvious configuration issues - i really tried to read as much as possible, but i'm a little bit lost. I also could provide more details if needed or can try patches.

Thanks in advance and once more a 'keep up the good work!' from me - i use Volumio for 2 years now and it always did what i wanted. I also love the new version and really just started using spotify because of volumio :)

**Comment by biva** [comment]
I'm also experiencing this with Airplay from a smartphone. Any news on this?
Available for testing if needed.
