### ISSUE TITLE
nfs mount

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#94]
To be able to mount a nfs filesystem, nfs-common is required. (apt-get install nfs-common).
But the system still try to mount a cifs fs even if the file "/data/configuration/system_controller/networkfs/config.json" contains "fstype": {
        "type": "string",
        "value": "nfs"
      },
"

**Comment by gkkpch** [comment]
can confirm, nfs mount does not work, it defaults to cifs.
The nfs-common issue has already been addressed by adding it to the build scripts.

**Comment by balbuze** [comment]
I can mount by hand after installing nfs-common. Then the mount appears in the webUI

**Comment by gkkpch** [comment]
Hi,
yes, that is why nfs-common has been added to the 'recipes' which is used to run the first part of the volumio build script. This part more or less takes care of building the debian rootfs, including all common volumio parts, common to all other platforms (I think only PI and C1 in this case).
Are you using the build scripts yet?
In case you do, nfs-common should be covered.
Gé


On 21.11.2015, at 18:30, balbuze <notifications@github.com> wrote:

I can mount by hand after installing nfs-common. Then the mount appears in the webUI

**Comment by balbuze** [comment]
I tried to build a image with build script, but with no success... Lack of instruction for me.
