### ISSUE TITLE
MPD does not communicate with volumio2.

### ISSUE THREAD

**Issue by testalex21** [volumio/Volumio2#950]
Hi. I'm trying to connect volumio with a python script that is using mdp2. 

Starting with 
from mpd import MPDClient

and then, even client.stop() does not work. 

The code works perfectly on pi musicbox which is based on volumio. But the volumio2 client runs a lot better, so I really want to get this working. 

Im using the script that I found here:

https://github.com/fsahli/music-cards/blob/master/box.py

**Comment by volumio** [comment]
Please use websocket api for volumio
https://volumio.github.io/docs/API/WebSocket_APIs.html
