### ISSUE TITLE
command-line script

### ISSUE THREAD

**Issue by Jellby** [volumio/Volumio2#952]
In ``app/plugins/system_controller/volumio_command_line_client/volumio.sh``, line 116 ff., isn't ``start`` duplicated, and in ``restart`` and ``vstop``, shouldn't ``stop`` be replaced with ``vstop``?

I just tried this:

```
$ volumio restart
/volumio/app/plugins/system_controller/volumio_command_line_client/volumio.sh: line 128: stop: command not found
```

However, it doesn't seem to work ``volumio play`` or ``volumio stop`` just get stuck waiting and nothing plays or stop.

**Comment by volumio** [comment]
Fixed
