### ISSUE TITLE
/var/log overflowing

### ISSUE THREAD

**Issue by martin2250** [volumio/Volumio2#960]
So I've left my Volumio running for a few days and it just started going into a sort of 'bootloop' (startup sound would start to play, stop mid-way, repeat every 3 seconds).

`volumio@volumio:$ uptime
 15:48:03 up 5 days,  5:58,  1 user,  load average: 0.49, 0.94, 0.64`
The time might not be accurate as I've been developing on it a few days ago.

Anyways, I've found to problem to be a full /var/log partition:
http://pastebin.com/r9Zw02JN

After clearing /var/log manually, I could start the service again.
Here is the console output from the 'bootloop':
http://pastebin.com/tgkjVgsx

**Comment by volumio** [comment]
Fixed now with this https://github.com/volumio/Volumio2/commit/1595812a99c81593afa56243231c85452fa16b8e
