### ISSUE TITLE
Album name is not urlEncoded in ControllerMpd.prototype.listAlbums

### ISSUE THREAD

**Issue by ValentinMumble** [volumio/Volumio2#969]
Album name is not urlEncoded in ControllerMpd.prototype.listAlbums and thus creates a bug with album titles containing special characters such as % or / (can not add to queue, can not browse album songs).

Fix: in app/plugins/music_service/mpd/index.js:2448

```javascript
var codedAlbumName = nodetools.urlEncode(albumName);
```

**Comment by volumio** [comment]
Thanks!  But cannot find the exact way you want to do that... Any change you'll do a complete PR?

**Comment by ValentinMumble** [comment]
Done! (I think)
https://github.com/volumio/Volumio2/pull/970
