### ISSUE TITLE
Back button jumps back either 2 or 3 menus, not just one

### ISSUE THREAD

**Issue by shawaj** [volumio/Volumio2#975]
Hitting the back button next to the home icon on Volumio UI actually takes you back 2 or 3 pages instead of just one.

**Comment by xipmix** [comment]
To help with reproducing this, can you provide a specific example - what page you were on when you hit the back button and what page you ended up on? It would help also to know the version you are running. To really nail it down,  a copy of ```tail -f /var/log/volumio.log``` from just before pressing the back button would be useful also.

**Comment by shawaj** [comment]
This is version 2.041

This happens on any Spotify page.

For example if I click Spotify -> Genres and Moods -> Rock -> Rock This and
then click back it takes me right back to the main Spotify page.

Thanks


On 26 Jan 2017 12:46 pm, "xipmix" <notifications@github.com> wrote:

To help with reproducing this, can you provide a specific example - what
page you were on when you hit the back button and what page you ended up
on? It would help also to know the version you are running. To really nail
it down, a copy of tail -f /var/log/volumio.log from just before pressing
the back button would be useful also.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/volumio/Volumio2/issues/975#issuecomment-275380329>,
or mute
the thread

**Comment by volumio** [comment]
@skikirkwood do you think we can fix this one? 
We could add in the browser mechanism the property currentPos so back will be populated with this one.
What do you think?

**Comment by skikirkwood** [comment]
Yes, we should definitely fix this.  I've been aware of it from day one and always found it annoying, just didn't know how to to fix it.  Let me know how when currentPos is in and I'll take care of it.
