### ISSUE TITLE
Wireless configuration

### ISSUE THREAD

**Issue by gkkpch** [volumio/Volumio2#98]
Fixed network is OK, but did not find a way to test wireless. Too early?

**Comment by volumio** [comment]
Enable wireless with ifconfig wlan0 up... And you'll see...

**Comment by gkkpch** [comment]
Wireless is enabled, using interfaces and "auto wlan0 inet dhcp", including ssid and key.
Nothing in the network menu, except wired network.

**Comment by gkkpch** [comment]
Noticed there was a fix, is it ready to test?

**Comment by gkkpch** [comment]
I cannot get wireless to work, unless I add 
   allow-hotplug wlan0
   iface wlan0 inet manual
   wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
   iface default inet dhcp
to /etc/network/interfaces

**Comment by gkkpch** [comment]
moved to volumio/Build, Wireless/ Configuration #29
