### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by gkkpch** [volumio/Volumio2#99]
I started a fresh build this morning, seems something is broken since the last commit.
When starting volumio, the boot process complains about a lot of missing modules.
Probably the ones that were updated....

**Edit:**  This is caused by *node_modules_arm.tar.gz*, it contains the volumio folder too, which does not fit the build script (build script steps into /volumio and then unpacks, so node_modules end up in /volumio/volumio/node_modules).

**Comment by volumio** [comment]
sorry, my bad... fixing it now!
