### ISSUE TITLE
Use Volumio as Bluetooth speaker

### ISSUE THREAD

**Issue by Octolinger** [volumio/Volumio2#991]
By using a USB-Bluetooth adapter or a RPi3 connect a phone/tablet/computer and use Volumio as a Bluetooth speaker. You know, for us with Android phones and needs to stream music from our phones to bigger speakers.

**Comment by chsims1** [comment]
Could you use an 'airplay' app connecting via wifi??

**Comment by Octolinger** [comment]
Could, but then only local audio files. I want to cast all sound without voiding my phones warranty by rooting it.

**Comment by xipmix** [comment]
This appears to be a duplicate, see #795.

**Comment by Octolinger** [comment]
Yeah, it is. Did not find anything when I searched for it so I created a new one. Still, this feature should be possible to implement natively in Volumio (with working media controls and song info)
