### ISSUE TITLE
Language strings cause Volumio crash when uninstalling a plugin

### ISSUE THREAD

**Issue by tim-felix-lange** [volumio/Volumio2#992]
I installed the GPIO-Buttons Plugin:
(Sidenote: When Installation was finished, the bar sprung back from 100% to 70% and was stuck, I had to refresh the page) 
When I click uninstall of the deactivated plugin, Volumio crashes with the following log: 

> Feb 04 21:56:27 volumio volumio[1211]: /volumio/app/index.js:1286
Feb 04 21:56:27 volumio volumio[1211]: if(this.i18nStrings[splitted[0]][splitted[1]]!==undefined)
Feb 04 21:56:27 volumio volumio[1211]: ^
Feb 04 21:56:27 volumio volumio[1211]: TypeError: Cannot read property 'CONFIRM_PLUGIN_UNINSTALL' of undefined
Feb 04 21:56:27 volumio volumio[1211]: at CoreCommandRouter.getI18nString (/volumio/app/index.js:1286:41)
Feb 04 21:56:27 volumio volumio[1211]: at Socket.<anonymous> (/volumio/app/plugins/user_interface/websocket/index.js:1488:81)
Feb 04 21:56:27 volumio volumio[1211]: at emitTwo (events.js:106:13)
Feb 04 21:56:27 volumio volumio[1211]: at Socket.emit (events.js:191:7)
Feb 04 21:56:27 volumio volumio[1211]: at Socket.onevent (/volumio/node_modules/socket.io/lib/socket.js:348:8)
Feb 04 21:56:27 volumio volumio[1211]: at Socket.onpacket (/volumio/node_modules/socket.io/lib/socket.js:308:12)
Feb 04 21:56:27 volumio volumio[1211]: at /volumio/node_modules/socket.io/lib/client.js:195:16
Feb 04 21:56:27 volumio volumio[1211]: at _combinedTickCallback (internal/process/next_tick.js:67:7)
Feb 04 21:56:27 volumio volumio[1211]: at process._tickCallback (internal/process/next_tick.js:98:9)
Feb 04 21:56:27 volumio mpd[594]: client: [2] closed

Uninstallation works fine if I set my language back to english, rather than german.

**Comment by Vigo0101** [comment]
Hello,
I am experiencing a similar issue but when installing touchscreen or spotify plugins.
Switching back language to English before proceeding avoid trouble.

**Comment by tim-felix-lange** [comment]
@Vigo0101 the problem seems to be independent of the plugin. As the error message already suggests, the string for "Do you really want to uninstall" is missing. This by itself is not a big problem, the problem is more that Volumio is not catching this error to fall back to english.
