### ISSUE TITLE
Plugin for smartplaylist generation

### ISSUE THREAD

**Issue by dinojr** [volumio/Volumio2#999]
Just a suggestion for a new plugin: I'd like the capability to create a smart/dynamic playlist based on criteria like:
+ song recently added to the database
+ songs never played

At the moment, I'm using mpdspl.py (from https://github.com/sdelafond/mpd) for the former to generate a m3u file but volumio2 can't play it (according to https://github.com/volumio/Volumio2/issues/334)

**Comment by volumio** [comment]
There is a plugin under works

**Comment by dinojr** [comment]
Volumio <notifications@github.com> writes:

> There is a plugin under works 

Great, is there a beta in the volumio-plugins repo at github ?
